import type { ContentInput } from "./schema.js";

// Dữ liệu MVP: 1 xóm, 3 business (bánh mì, trà sữa, phụ kiện), 2 template (docs/PLAN.md §3.1).
// Mọi con số ở đây là điểm khởi đầu để cân bằng bằng tools/balance.

export const data: ContentInput = {
  templates: [
    { id: "FOOD", name: "Đồ ăn · thức uống", perishable: true },
    { id: "RETAIL", name: "Bán lẻ", perishable: false },
  ],

  products: [
    {
      id: "banh_mi",
      template: "FOOD",
      category: "breakfast",
      name: "Bánh mì thịt",
      emoji: "🥖",
      sign: "BÁNH MÌ",
      signColor: "#e4432d",
      unitCost: 8_000,
      refPrice: 15_000,
      elasticity: 3,
      shelfLifeDays: 1,
      interestByHour: {
        "6": 0.13,
        "7": 0.156,
        "8": 0.104,
        "10": 0.039,
        "11": 0.065,
        "13": 0.0325,
        "16": 0.039,
        "18": 0.052,
        "21": 0.0195,
      },
    },
    {
      id: "tra_sua",
      template: "FOOD",
      category: "drink",
      name: "Trà sữa trân châu",
      emoji: "🧋",
      sign: "TRÀ SỮA",
      signColor: "#2f7d4f",
      unitCost: 12_000,
      refPrice: 25_000,
      elasticity: 2.6,
      shelfLifeDays: 1,
      interestByHour: {
        "6": 0.0033,
        "9": 0.013,
        "11": 0.0228,
        "14": 0.039,
        "16": 0.052,
        "19": 0.0455,
        "21": 0.026,
      },
    },
    {
      id: "phu_kien",
      template: "RETAIL",
      category: "accessory",
      name: "Phụ kiện (kẹp tóc, móc khóa)",
      emoji: "🎀",
      sign: "PHỤ KIỆN",
      signColor: "#c2185b",
      unitCost: 15_000,
      refPrice: 35_000,
      elasticity: 2.4,
      shelfLifeDays: null,
      interestByHour: {
        "6": 0.00192,
        "9": 0.0078,
        "12": 0.01164,
        "16": 0.01956,
        "19": 0.02736,
        "21": 0.01956,
      },
    },
  ],

  equipment: [
    {
      id: "xe_banh_mi",
      name: "Xe bánh mì kính",
      price: 320_000,
      products: ["banh_mi"],
      capacityPerHour: 40,
      model: "xe-banh-mi",
    },
    {
      id: "xe_tra_sua",
      name: "Xe đẩy trà sữa",
      price: 380_000,
      products: ["tra_sua"],
      capacityPerHour: 30,
      model: "xe-tra-sua",
    },
    {
      id: "sap_phu_kien",
      name: "Sạp phụ kiện",
      price: 280_000,
      products: ["phu_kien"],
      capacityPerHour: 20,
      model: "sap-phu-kien",
    },
  ],

  trafficProfiles: [
    {
      id: "school",
      name: "Cổng trường",
      peoplePerHour: {
        "6": 160,
        "7": 220,
        "8": 60,
        "10": 30,
        "11": 140,
        "12": 60,
        "14": 40,
        "16": 150,
        "17": 170,
        "18": 60,
        "20": 20,
      },
    },
    {
      id: "office",
      name: "Khu văn phòng",
      peoplePerHour: {
        "6": 40,
        "7": 160,
        "8": 120,
        "10": 50,
        "11": 150,
        "12": 160,
        "13": 60,
        "16": 70,
        "17": 170,
        "18": 90,
        "20": 30,
      },
    },
    {
      id: "residential",
      name: "Trong hẻm",
      peoplePerHour: {
        "6": 60,
        "7": 80,
        "9": 40,
        "12": 40,
        "16": 60,
        "18": 90,
        "19": 100,
        "21": 60,
      },
    },
    {
      id: "market",
      name: "Gần chợ",
      peoplePerHour: {
        "6": 180,
        "7": 200,
        "9": 150,
        "11": 90,
        "14": 50,
        "16": 80,
        "18": 70,
        "20": 30,
      },
    },
    {
      id: "crossroad",
      name: "Ngã tư",
      peoplePerHour: {
        "6": 120,
        "7": 180,
        "9": 110,
        "11": 120,
        "13": 90,
        "16": 140,
        "18": 180,
        "20": 140,
        "21": 90,
      },
    },
  ],

  // Vỉa hè bắc (z ≈ -3) và nam (z ≈ 3) của con phố thử nghiệm (apps/web/game/scene/Street.tsx).
  lots: [
    {
      id: "dau_hem",
      name: "Đầu hẻm 12",
      hint: "Dân trong hẻm, đông chiều tối",
      traffic: "residential",
      trafficScale: 1,
      rentPerDay: 25_000,
      position: { x: -18, z: -2.8 },
      facing: 0,
    },
    {
      id: "cong_truong",
      name: "Cổng trường",
      hint: "Học sinh đông sáng sớm, trưa, chiều",
      traffic: "school",
      trafficScale: 1,
      rentPerDay: 80_000,
      position: { x: -12, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "gan_cho",
      name: "Gần chợ",
      hint: "Sáng rất đông, chiều vắng",
      traffic: "market",
      trafficScale: 1,
      rentPerDay: 65_000,
      position: { x: -4.5, z: -2.8 },
      facing: 0,
    },
    {
      id: "nga_tu",
      name: "Góc ngã tư",
      hint: "Đông cả ngày, thuê đắt",
      traffic: "crossroad",
      trafficScale: 1.1,
      rentPerDay: 150_000,
      position: { x: 2.8, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "van_phong",
      name: "Trước toà văn phòng",
      hint: "Giờ đi làm, giờ trưa, tan tầm",
      traffic: "office",
      trafficScale: 1,
      rentPerDay: 90_000,
      position: { x: 9, z: -2.8 },
      facing: 0,
    },
    {
      id: "goc_cay",
      name: "Dưới gốc cây",
      hint: "Mát, khách lai rai",
      traffic: "residential",
      trafficScale: 0.8,
      rentPerDay: 15_000,
      position: { x: 14, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "cuoi_pho",
      name: "Cuối phố",
      hint: "Vắng, rẻ",
      traffic: "residential",
      trafficScale: 0.6,
      rentPerDay: 10_000,
      position: { x: 20, z: -2.8 },
      facing: 0,
    },
    {
      id: "ben_xe_buyt",
      name: "Trạm xe buýt",
      hint: "Người chờ xe cả ngày",
      traffic: "office",
      trafficScale: 0.9,
      rentPerDay: 50_000,
      position: { x: -22, z: 2.8 },
      facing: Math.PI,
    },
  ],

  npcs: [
    {
      id: "hoc_sinh",
      name: "Học sinh",
      model: "character-female-a",
      likes: { breakfast: 1.2, drink: 1.5, accessory: 1.3 },
    },
    {
      id: "dan_van_phong",
      name: "Dân văn phòng",
      model: "character-male-c",
      likes: { breakfast: 1.3, drink: 1.1, accessory: 0.6 },
    },
    {
      id: "co_chu",
      name: "Cô chú trong xóm",
      model: "character-female-d",
      likes: { breakfast: 1.1, drink: 0.5, accessory: 0.7 },
    },
    {
      id: "khach_vang_lai",
      name: "Khách vãng lai",
      model: "character-male-a",
      likes: { breakfast: 1, drink: 1, accessory: 0.8 },
    },
    {
      id: "reviewer",
      name: "Reviewer",
      model: "character-male-a",
      likes: { breakfast: 1, drink: 1, accessory: 1 },
    },
  ],

  jobs: [
    {
      id: "phu_quan_com",
      name: "Phụ quán cơm",
      wagePerHour: 10_000,
      description: "Bưng bê, rửa chén. Ổn định nhưng không giàu.",
    },
    {
      id: "giao_hang",
      name: "Giao hàng xe máy",
      wagePerHour: 12_000,
      description: "Chạy đơn quanh xóm. Mệt hơn, lương cao hơn.",
    },
  ],

  // Địa điểm có người đứng quầy (docs/PLAN.md Phase 1.5). Toạ độ trên vỉa hè sát mặt tiền nhà.
  places: [
    {
      id: "vua_xe",
      name: "Vựa xe Ông Sáu",
      kind: "equipment_shop",
      sign: "VỰA XE ÔNG SÁU",
      signColor: "#2b2118",
      action: "🛒 Xem xe đẩy",
      keeper: {
        name: "Ông Sáu",
        model: "character-male-c",
        greeting: "Xe nào cũng chắc hết, con coi hợp nghề nào thì lấy nghề đó.",
      },
      position: { x: -21.5, z: -4.9 },
      facing: 0,
      props: [
        { model: "xe-banh-mi", dx: -1.8, dz: 0.3, rot: 0 },
        { model: "xe-tra-sua", dx: 1.8, dz: 0.3, rot: 0 },
        { model: "detail-awning-wide", dx: 0, dz: -1.2, rot: 0 },
      ],
    },
    {
      id: "cho_dau_moi",
      name: "Chợ đầu mối Bà Năm",
      kind: "market",
      sign: "CHỢ ĐẦU MỐI",
      signColor: "#f6b93b",
      action: "🧺 Vào chợ",
      keeper: {
        name: "Bà Năm",
        model: "character-female-d",
        greeting: "Hàng mới về sáng nay nè con. Đồ ăn thì lấy vừa đủ bán, để qua đêm là bỏ.",
      },
      position: { x: -6.5, z: 4.9 },
      facing: Math.PI,
      props: [
        { model: "detail-parasol-a", dx: -1.4, dz: 0, rot: 0 },
        { model: "detail-parasol-b", dx: 1.4, dz: 0.2, rot: 0 },
        { model: "ghe-nhua-do", dx: -0.6, dz: 0.8, rot: 0.4 },
        { model: "detail-awning-wide", dx: 0, dz: 1.2, rot: Math.PI },
      ],
    },
    {
      id: "quan_com",
      name: "Quán cơm Cô Tư",
      kind: "job",
      sign: "CƠM TẤM CÔ TƯ",
      signColor: "#e4432d",
      action: "🍚 Vào quán",
      keeper: {
        name: "Cô Tư",
        model: "character-female-a",
        greeting: "Trưa nay đông lắm, phụ cô một tay đi con!",
      },
      jobs: ["phu_quan_com"],
      position: { x: 15, z: -4.9 },
      facing: 0,
      props: [
        { model: "ghe-nhua-do", dx: -1.6, dz: 0.9, rot: 0.2 },
        { model: "ghe-nhua-do", dx: -0.9, dz: 1.3, rot: -0.3 },
        { model: "ghe-nhua-do", dx: 1.1, dz: 1.1, rot: 0.6 },
        { model: "detail-parasol-a", dx: -1.2, dz: 1.1, rot: 0 },
        { model: "detail-awning-wide", dx: 0, dz: -1.2, rot: 0 },
      ],
    },
    {
      id: "buu_cuc",
      name: "Bưu cục",
      kind: "job",
      sign: "BƯU CỤC",
      signColor: "#2f7d4f",
      action: "📦 Vào bưu cục",
      keeper: {
        name: "Anh Tám",
        model: "character-male-a",
        greeting: "Có xe máy chưa em? Có thì chạy đơn quanh xóm, trả theo giờ.",
      },
      jobs: ["giao_hang"],
      position: { x: 19.5, z: 4.9 },
      facing: Math.PI,
      props: [{ model: "detail-awning-wide", dx: 0, dz: 1.2, rot: Math.PI }],
    },
  ],

  speakers: [
    {
      id: "chu_bay",
      name: "Chú Bảy xe ôm",
      model: "character-male-c",
      position: { x: -8, z: -4.6 },
      facing: Math.PI / 2,
    },
  ],

  // Kịch bản người mới — rẽ nhánh buôn bán / làm thuê.
  tutorial: [
    {
      id: "gap_chu_bay",
      speaker: "chu_bay",
      lines: [
        "Ủa, con là người mới dọn về xóm hả? Chú là Bảy, chạy xe ôm đầu hẻm nè.",
        "Ở xóm này ai cũng tự lo lấy cái nghề. Trong túi con có 500 ngàn — đủ mua một chiếc xe đẩy nhỏ.",
        "Còn chưa chắc tay thì qua quán cơm Cô Tư phụ việc, kiếm vốn trước cũng được.",
      ],
      choices: [
        { text: "Con muốn buôn bán", next: "den_vua_xe" },
        { text: "Con đi làm thuê trước", next: "den_quan_com" },
      ],
    },
    {
      id: "den_vua_xe",
      objective: "Tới vựa xe Ông Sáu mua một chiếc xe đẩy",
      target: "vua_xe",
      until: "has_business",
      next: "ra_cho",
    },
    {
      id: "ra_cho",
      speaker: "chu_bay",
      lines: [
        "Có xe rồi hả? Giờ ra chợ đầu mối Bà Năm nhập hàng. Đồ ăn để qua đêm là hư, nhập vừa đủ thôi nghe!",
      ],
      objective: "Ra chợ đầu mối nhập hàng",
      target: "cho_dau_moi",
      until: "has_stock",
      next: "chon_cho",
    },
    {
      id: "chon_cho",
      speaker: "chu_bay",
      lines: [
        "Giờ chọn chỗ bán. Chỗ đông khách thì thuê đắt — mới làm nên thử Đầu hẻm 12, rẻ mà có khách.",
      ],
      objective: "Chọn chỗ bán trong mục Kinh doanh",
      until: "has_lot",
      next: "ra_quay",
    },
    {
      id: "ra_quay",
      objective: "Đẩy xe tới chỗ bán và mở quầy",
      target: "stall",
      until: "shop_open",
      next: "phuc_vu",
    },
    {
      id: "phuc_vu",
      speaker: "chu_bay",
      lines: [
        "Mở hàng rồi đó! Khách tới thì đưa hàng cho lẹ — khách vui là boa thêm, lại nhớ quầy mình.",
      ],
      objective: "Phục vụ 3 khách đầu tiên (bấm Đưa hàng)",
      target: "stall",
      until: "served_3",
      next: "xong_buon_ban",
    },
    {
      id: "xong_buon_ban",
      speaker: "chu_bay",
      lines: [
        "Được rồi đó con! Nhớ nè: hết hàng thì ra chợ nhập thêm, đừng để khách về tay không.",
        "Tối coi sổ sách cuối ngày cho kỹ. Thôi chú chạy cuốc xe đây, chúc con đắt hàng!",
      ],
      next: "hoan_thanh",
    },
    {
      id: "den_quan_com",
      objective: "Tới quán cơm Cô Tư xin việc",
      target: "quan_com",
      until: "has_job",
      next: "lam_viec",
    },
    {
      id: "lam_viec",
      objective: "Khách gọi món thì bấm Bưng ra (2 lần)",
      target: "quan_com",
      until: "job_tasks_2",
      next: "xong_lam_thue",
    },
    {
      id: "xong_lam_thue",
      speaker: "chu_bay",
      lines: [
        "Siêng dữ ha! Làm thuê thì chắc ăn, lương trả theo giờ.",
        "Khi nào có vốn thì ghé vựa xe Ông Sáu, tự làm chủ cái quầy. Chú đi đây!",
      ],
      next: "hoan_thanh",
    },
    // Hết kịch bản người mới.
    { id: "hoan_thanh" },
  ],

  customerLines: {
    cheap: ["Rẻ vậy! Mai ghé nữa nha", "Giá này hời quá", "Cho thêm ổ nữa được hông?"],
    fair: ["Cho một phần nha", "Bán cho con với", "Như mọi khi nha"],
    pricey: ["Hơi mắc ha…", "Giá này hơi chát", "Bữa sau bớt chút nha"],
    thanks: ["Cảm ơn nha!", "Lẹ ghê, gửi tiền nè", "Ngon! Giữ tiền thối luôn"],
    impatient: ["Lâu quá, thôi đi…", "Đợi hoài…", "Thôi để bữa khác"],
  },

  jobTasks: {
    phu_quan_com: [
      "Bàn 3 gọi 2 dĩa cơm tấm!",
      "Khách bàn ngoài xin thêm trà đá!",
      "Dọn bàn 5 giùm cô!",
    ],
    giao_hang: [
      "Đơn mới: giao bánh bao cho nhà số 7!",
      "Có người gửi gói hàng ra đầu hẻm!",
      "Giao gấp ly cà phê cho văn phòng!",
    ],
  },

  economy: {
    startingMoney: 500_000,
    dayStartMinute: 6 * 60,
    dayEndMinute: 22 * 60,
    economyTickMinutes: 5,
    marketPriceSwing: 0.1,
    outsideOption: 1,
    reputationRate: 0.08,
    startingReputation: 0.5,
    serveWindowMs: 12_000,
    tipRate: 0.08,
    serveReputationBonus: 0.01,
    jobTaskEveryMinutes: 20,
    jobTaskBonus: 3_000,
    interactRadius: 2.5,
  },
};
