import type { ContentInput } from "./schema.js";

/** Vốn khởi nghiệp: 💵 tiền mặt + 🏦 tài khoản (dùng chung cho economy và lời Chú Bảy để không lệch nhau). */
const START_CASH = 1_500_000;
const START_BANK = 1_000_000;
/** 1_500_000 → "1 triệu rưỡi", 1_000_000 → "1 triệu", 500_000 → "500 ngàn" (cách nói ngoài đời). */
const spoken = (n: number) =>
  n >= 1_000_000
    ? n % 1_000_000 === 500_000
      ? `${Math.floor(n / 1_000_000)} triệu rưỡi`
      : `${(n / 1_000_000).toLocaleString("vi-VN")} triệu`
    : `${n / 1000} ngàn`;

// Dữ liệu MVP: 1 xóm, 3 business (bánh mì, trà sữa, phụ kiện), 2 template (docs/PLAN.md §3.1).
// Mọi con số ở đây là điểm khởi đầu để cân bằng bằng tools/balance.

export const data: ContentInput = {
  templates: [
    { id: "FOOD", name: "Đồ ăn · thức uống" },
    { id: "RETAIL", name: "Bán lẻ" },
    { id: "SERVICE", name: "Dịch vụ" },
  ],

  // Mỗi nghề có công thức làm món từng bước (docs/USECASES.md UC-F4…F6).
  products: [
    {
      id: "banh_mi",
      template: "FOOD",
      category: "breakfast",
      name: "Bánh mì",
      emoji: "🥖",
      sign: "BÁNH MÌ",
      signColor: "#e4432d",
      elasticity: 3,
      interestByHour: {
        "6": 0.13,
        "7": 0.156,
        "8": 0.104,
        "10": 0.039,
        "11": 0.065,
        "13": 0.0325,
        "16": 0.039,
        "18": 0.052,
        "21": 0.0195,
      },
      recipe: {
        ask: "Cho con ổ {dish} nha!",
        steps: [
          {
            id: "banh",
            label: "Lấy bánh",
            kind: "single",
            weight: 1,
            options: [
              { id: "banh_mi_phoi", label: "Ổ bánh mì", emoji: "🥖", ingredient: "banh_mi_phoi" },
            ],
          },
          { id: "xe", label: "Xẻ bánh", kind: "action", verb: "🔪 Xẻ bánh" },
          {
            id: "phet",
            label: "Phết",
            kind: "multi",
            options: [
              { id: "pate", label: "Pa-tê", emoji: "🟤", ingredient: "pate" },
              { id: "bo", label: "Bơ", emoji: "🧈", ingredient: "bo", extraPrice: 2_000 },
            ],
          },
          {
            id: "nhan",
            label: "Nhân",
            kind: "single",
            weight: 3,
            options: [
              { id: "thit_nguoi", label: "Thịt nguội", emoji: "🥓", ingredient: "thit_nguoi" },
              { id: "xiu_mai", label: "Xíu mại", emoji: "🧆", ingredient: "xiu_mai" },
              { id: "trung", label: "Trứng ốp la", emoji: "🍳", ingredient: "trung" },
            ],
          },
          {
            id: "rau",
            label: "Rau",
            kind: "multi",
            options: [
              { id: "dua_leo", label: "Dưa leo", emoji: "🥒", ingredient: "dua_leo" },
              { id: "do_chua", label: "Đồ chua", emoji: "🥕", ingredient: "do_chua" },
              { id: "hanh", label: "Hành lá", emoji: "🌱", ingredient: "hanh" },
              { id: "ngo", label: "Ngò", emoji: "🌿", ingredient: "ngo" },
            ],
          },
          {
            id: "ot",
            label: "Ớt",
            kind: "single",
            options: [
              { id: "ot_khong", label: "Không ớt", emoji: "🚫" },
              { id: "ot_vua", label: "Vừa", emoji: "🌶️", ingredient: "ot" },
              { id: "ot_nhieu", label: "Nhiều", emoji: "🔥", ingredient: "ot", qty: 2 },
            ],
          },
          {
            id: "sot",
            label: "Nước sốt",
            kind: "multi",
            options: [{ id: "sot", label: "Nước sốt", emoji: "🥫", ingredient: "sot" }],
          },
          {
            id: "goi",
            label: "Gói giấy",
            kind: "action",
            verb: "📄 Gói giấy",
            ingredient: "giay_goi",
          },
        ],
        defaults: {
          banh: "banh_mi_phoi",
          phet: ["pate"],
          rau: ["dua_leo", "do_chua", "hanh", "ngo"],
          ot: "ot_vua",
          sot: ["sot"],
        },
        variants: [
          {
            id: "banh_mi_thit",
            name: "bánh mì thịt",
            fixed: { nhan: "thit_nguoi" },
            refPrice: 16_000,
            popularity: 3,
          },
          {
            id: "banh_mi_xiu_mai",
            name: "bánh mì xíu mại",
            fixed: { nhan: "xiu_mai" },
            refPrice: 18_000,
            popularity: 2,
          },
          {
            id: "banh_mi_trung",
            name: "bánh mì trứng",
            fixed: { nhan: "trung" },
            refPrice: 14_000,
            popularity: 2,
          },
        ],
        mods: [
          { id: "khong_hanh", step: "rau", remove: "hanh", say: "không hành", chance: 0.3 },
          { id: "khong_ngo", step: "rau", remove: "ngo", say: "không ngò", chance: 0.15 },
          { id: "khong_dua", step: "rau", remove: "dua_leo", say: "không dưa leo", chance: 0.1 },
          { id: "khong_pate", step: "phet", remove: "pate", say: "không pa-tê", chance: 0.1 },
          { id: "them_bo", step: "phet", add: "bo", say: "thêm bơ", chance: 0.12 },
          { id: "ot_nhieu", step: "ot", set: "ot_nhieu", say: "nhiều ớt", chance: 0.2 },
          { id: "ot_khong", step: "ot", set: "ot_khong", say: "không ớt", chance: 0.15 },
        ],
      },
    },
    {
      id: "tra_sua",
      // Quầy trà theo góc nhìn người bán (ảnh tham khảo của chủ dự án): ly M/L · bình trà có vòi · máy dán miệng ly ·
      // ô pha ly + dải đường/đá · lưới khay topping 4×3 · giữ để lắc.
      counter: {
        title: "QUẦY TRÀ",
        zones: [
          { zone: "cups", step: "ly" },
          { zone: "jars", step: "tra" },
          { zone: "sealer", step: "nap" },
          { zone: "chips", step: "duong" },
          { zone: "chips", step: "da" },
          { zone: "grid", step: "topping", slots: 12 },
          { zone: "shaker", step: "lac" },
        ],
      },
      template: "FOOD",
      category: "drink",
      name: "Trà sữa",
      emoji: "🧋",
      sign: "TRÀ SỮA",
      signColor: "#2f7d4f",
      elasticity: 2.6,
      interestByHour: {
        "6": 0.0033,
        "9": 0.013,
        "11": 0.0228,
        "14": 0.039,
        "16": 0.052,
        "19": 0.0455,
        "21": 0.026,
      },
      recipe: {
        ask: "Cho em một ly {dish} nha!",
        steps: [
          {
            id: "ly",
            label: "Chọn ly",
            kind: "single",
            options: [
              { id: "ly_m", label: "Size M", emoji: "🥤", ingredient: "ly_m" },
              {
                id: "ly_l",
                label: "Size L",
                emoji: "🥤",
                ingredient: "ly_l",
                extraPrice: 5_000,
                say: "size L",
              },
            ],
            pick: { ly_m: 0.65, ly_l: 0.35 },
          },
          {
            id: "tra",
            label: "Trà nền",
            kind: "single",
            weight: 3,
            options: [
              { id: "cot_tra_sua", label: "Trà sữa", emoji: "🍵", ingredient: "cot_tra_sua" },
              { id: "cot_tra_xanh", label: "Trà xanh", emoji: "🍃", ingredient: "cot_tra_xanh" },
              { id: "cot_hong_tra", label: "Hồng trà", emoji: "🍂", ingredient: "cot_hong_tra" },
            ],
          },
          {
            id: "duong",
            label: "Đường",
            kind: "single",
            options: [
              // Nhãn theo cách khách nói (góp ý chơi thử: chỉ ghi % thì khó biết nhiều hay ít).
              { id: "duong_0", label: "Không đường · 0%", emoji: "⚪", say: "không đường" },
              { id: "duong_30", label: "Ít đường · 30%", emoji: "🍬", say: "ít đường" },
              { id: "duong_50", label: "Nửa đường · 50%", emoji: "🍬", say: "nửa đường" },
              { id: "duong_70", label: "Bình thường · 70%", emoji: "🍬" },
              { id: "duong_100", label: "Ngọt nhiều · 100%", emoji: "🍯", say: "nhiều đường" },
            ],
            pick: { duong_0: 0.08, duong_30: 0.17, duong_50: 0.2, duong_70: 0.4, duong_100: 0.15 },
          },
          {
            id: "da",
            label: "Đá",
            kind: "single",
            options: [
              { id: "da_khong", label: "Không đá", emoji: "🚫", say: "không đá" },
              { id: "da_it", label: "Ít đá", emoji: "🧊", ingredient: "da", say: "ít đá" },
              { id: "da_bt", label: "Bình thường", emoji: "🧊", ingredient: "da", qty: 2 },
            ],
            pick: { da_khong: 0.1, da_it: 0.3, da_bt: 0.6 },
          },
          {
            id: "topping",
            label: "Topping",
            kind: "multi",
            weight: 2,
            options: [
              { id: "tc_den", label: "Trân châu đen", emoji: "⚫", ingredient: "tran_chau_den" },
              {
                id: "tc_trang",
                label: "Trân châu trắng",
                emoji: "⚪",
                ingredient: "tran_chau_trang",
                extraPrice: 5_000,
              },
              {
                id: "thach",
                label: "Thạch trái cây",
                emoji: "🟩",
                ingredient: "thach",
                extraPrice: 5_000,
              },
              {
                id: "pudding",
                label: "Pudding",
                emoji: "🍮",
                ingredient: "pudding",
                extraPrice: 5_000,
              },
            ],
          },
          { id: "lac", label: "Lắc đều", kind: "hold", verb: "🫨 Giữ để lắc" },
          {
            id: "nap",
            label: "Dán nắp",
            kind: "action",
            verb: "🔘 Dán nắp",
            ingredient: "mang_nap",
          },
        ],
        defaults: { ly: "ly_m", duong: "duong_70", da: "da_bt", topping: ["tc_den"] },
        variants: [
          {
            id: "tra_sua_truyen_thong",
            name: "trà sữa truyền thống",
            fixed: { tra: "cot_tra_sua" },
            refPrice: 25_000,
            popularity: 3,
          },
          {
            id: "tra_xanh_sua",
            name: "trà xanh sữa",
            fixed: { tra: "cot_tra_xanh" },
            refPrice: 25_000,
            popularity: 1.5,
          },
          {
            id: "hong_tra_sua",
            name: "hồng trà sữa",
            fixed: { tra: "cot_hong_tra" },
            refPrice: 27_000,
            popularity: 1.5,
          },
        ],
        mods: [
          {
            id: "them_tc_trang",
            step: "topping",
            add: "tc_trang",
            say: "thêm trân châu trắng",
            chance: 0.18,
          },
          { id: "them_thach", step: "topping", add: "thach", say: "thêm thạch", chance: 0.15 },
          { id: "them_pudding", step: "topping", add: "pudding", say: "thêm pudding", chance: 0.2 },
          {
            id: "khong_tc_den",
            step: "topping",
            remove: "tc_den",
            say: "không trân châu đen",
            chance: 0.08,
          },
        ],
      },
    },
    {
      id: "phu_kien",
      template: "RETAIL",
      category: "accessory",
      name: "Phụ kiện",
      emoji: "🎀",
      sign: "PHỤ KIỆN",
      signColor: "#c2185b",
      elasticity: 2.4,
      interestByHour: {
        "6": 0.00192,
        "9": 0.0078,
        "12": 0.01164,
        "16": 0.01956,
        "19": 0.02736,
        "21": 0.01956,
      },
      recipe: {
        ask: "Có {dish} hông?",
        steps: [
          {
            id: "chon",
            label: "Tìm món",
            kind: "single",
            weight: 3,
            options: [
              { id: "kep_hong", label: "Kẹp tóc hồng", emoji: "🎀", ingredient: "kep_hong" },
              { id: "kep_xanh", label: "Kẹp tóc xanh", emoji: "💠", ingredient: "kep_xanh" },
              { id: "moc_meo", label: "Móc khóa mèo", emoji: "🐱", ingredient: "moc_meo" },
              { id: "moc_cun", label: "Móc khóa cún", emoji: "🐶", ingredient: "moc_cun" },
              { id: "day_buoc", label: "Dây buộc tóc", emoji: "🧶", ingredient: "day_buoc" },
            ],
          },
          {
            id: "goi",
            label: "Gói quà",
            kind: "single",
            options: [
              { id: "goi_khong", label: "Không gói", emoji: "🛍️" },
              {
                id: "goi_qua",
                label: "Gói quà",
                emoji: "🎁",
                ingredient: "giay_qua",
                say: "gói quà giùm",
              },
            ],
            pick: { goi_khong: 0.7, goi_qua: 0.3 },
          },
        ],
        defaults: { goi: "goi_khong" },
        variants: [
          {
            id: "kep_hong",
            name: "kẹp tóc hồng",
            fixed: { chon: "kep_hong" },
            refPrice: 30_000,
            popularity: 2,
          },
          {
            id: "kep_xanh",
            name: "kẹp tóc xanh",
            fixed: { chon: "kep_xanh" },
            refPrice: 30_000,
            popularity: 1.5,
          },
          {
            id: "moc_meo",
            name: "móc khóa mèo",
            fixed: { chon: "moc_meo" },
            refPrice: 35_000,
            popularity: 2,
          },
          {
            id: "moc_cun",
            name: "móc khóa cún",
            fixed: { chon: "moc_cun" },
            refPrice: 35_000,
            popularity: 1.5,
          },
          {
            id: "day_buoc",
            name: "dây buộc tóc",
            fixed: { chon: "day_buoc" },
            refPrice: 20_000,
            popularity: 1.5,
          },
        ],
      },
    },
    {
      // Tiệm sửa xe (docs/NGHE.md §3.1, UC-G2…G4): khách kể triệu chứng, chủ tiệm kiểm tra bộ phận,
      // chọn đúng cách sửa, lấy phụ tùng trong kho, khách nổ máy chạy thử.
      id: "sua_xe",
      template: "SERVICE",
      category: "repair",
      name: "Sửa xe",
      emoji: "🔧",
      sign: "SỬA XE",
      signColor: "#37474f",
      elasticity: 1.6,
      interestByHour: {
        "6": 0.0075,
        "7": 0.015,
        "9": 0.01,
        "12": 0.0075,
        "16": 0.0125,
        "17": 0.0175,
        "19": 0.01,
        "21": 0.005,
      },
      diagnosis: {
        checkMs: 1200,
        ok: "Bình thường, không có gì",
        stillBroken: "Ủa chạy thử vẫn y chang à… chưa đúng bệnh rồi!",
        parts: [
          { id: "lop_truoc", label: "Lốp trước", emoji: "🛞" },
          { id: "lop_sau", label: "Lốp sau", emoji: "🛞" },
          { id: "bugi", label: "Bugi", emoji: "⚡" },
          { id: "xich", label: "Xích", emoji: "⛓️" },
          { id: "phanh", label: "Phanh", emoji: "🛑" },
          { id: "den", label: "Đèn", emoji: "💡" },
        ],
      },
      recipe: {
        ask: "{dish}",
        steps: [
          { id: "thao", label: "Tháo ra", kind: "action", verb: "🔧 Tháo ra", weight: 0.5 },
          {
            id: "sua",
            label: "Cách sửa",
            kind: "single",
            weight: 4,
            options: [
              { id: "va_ruot", label: "Vá ruột", emoji: "🩹", ingredient: "mieng_va" },
              { id: "thay_ruot", label: "Thay ruột", emoji: "⭕", ingredient: "ruot_xe" },
              { id: "bom_hoi", label: "Bơm hơi", emoji: "💨" },
              { id: "thay_bugi", label: "Thay bugi", emoji: "⚡", ingredient: "bugi" },
              { id: "thay_phanh", label: "Thay má phanh", emoji: "🛑", ingredient: "ma_phanh" },
              { id: "thay_den", label: "Thay bóng đèn", emoji: "💡", ingredient: "bong_den" },
              { id: "tang_xich", label: "Tăng xích", emoji: "⛓️" },
            ],
          },
          { id: "lap", label: "Lắp lại", kind: "action", verb: "🔩 Lắp lại", weight: 0.5 },
          { id: "thu", label: "Nổ máy thử", kind: "action", verb: "🛵 Nổ máy thử", weight: 0.5 },
        ],
        defaults: {},
        variants: [
          {
            id: "lop_dinh",
            name: "lủng lốp sau (đinh)",
            fixed: { sua: "va_ruot" },
            refPrice: 30_000,
            popularity: 3,
            symptoms: ["Bánh sau xẹp lép rồi con ơi", "Chạy cán trúng gì mà bánh sau xẹp quá"],
            findings: { lop_sau: "Có cây đinh cắm ở lốp sau, lỗ nhỏ — vá được 🔍" },
          },
          {
            id: "ruot_nat",
            name: "rách ruột sau",
            fixed: { sua: "thay_ruot" },
            refPrice: 100_000,
            popularity: 1,
            symptoms: ["Bánh sau xẹp lép rồi con ơi", "Bánh sau mới vá hôm qua lại xẹp nữa"],
            findings: { lop_sau: "Ruột rách một đường dài, vá không nổi — phải thay ruột" },
          },
          {
            id: "non_hoi",
            name: "lốp non hơi",
            fixed: { sua: "bom_hoi" },
            refPrice: 5_000,
            popularity: 2,
            symptoms: ["Chạy thấy bánh nặng nặng sao á", "Xe chạy ì ì, bánh hơi lún"],
            findings: {
              lop_truoc: "Lốp trước non hơi, không thủng",
              lop_sau: "Lốp sau non hơi, không thủng",
            },
          },
          {
            id: "bugi_hong",
            name: "hỏng bugi",
            fixed: { sua: "thay_bugi" },
            refPrice: 70_000,
            popularity: 2,
            symptoms: ["Đạp hoài không nổ máy", "Sáng giờ đề không lên, đạp muốn rụng chân"],
            findings: { bugi: "Bugi đen sì, đánh lửa yếu ⚡" },
          },
          {
            id: "mon_phanh",
            name: "mòn má phanh",
            fixed: { sua: "thay_phanh" },
            refPrice: 80_000,
            popularity: 1.5,
            symptoms: ["Bóp thắng không ăn, sợ quá", "Thắng kêu két két mỗi lần bóp"],
            findings: { phanh: "Má phanh mòn sát gót" },
          },
          {
            id: "chay_den",
            name: "cháy bóng đèn",
            fixed: { sua: "thay_den" },
            refPrice: 35_000,
            popularity: 1,
            symptoms: ["Tối chạy không thấy đường, đèn không sáng"],
            findings: { den: "Bóng đèn đứt dây tóc" },
          },
          {
            id: "chung_xich",
            name: "chùng xích",
            fixed: { sua: "tang_xich" },
            refPrice: 20_000,
            popularity: 1.5,
            symptoms: ["Chạy nghe lạch cạch ở dưới gầm", "Lên ga xe giật giật"],
            findings: { xich: "Xích chùng, chạm vỏ xích" },
          },
        ],
      },
    },
  ],

  // Nguyên liệu / hàng nhập ở chợ Bà Năm (giá gốc mỗi phần; mua theo gói).
  ingredients: [
    {
      id: "banh_mi_phoi",
      name: "Bánh mì phôi",
      emoji: "🥖",
      unit: "ổ",
      packSize: 10,
      costPerUnit: 2_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "pate",
      name: "Pa-tê",
      emoji: "🟤",
      unit: "phần",
      packSize: 20,
      costPerUnit: 1_000,
      shelfLifeDays: 3,
    },
    {
      id: "bo",
      name: "Bơ",
      emoji: "🧈",
      unit: "phần",
      packSize: 20,
      costPerUnit: 800,
      shelfLifeDays: 3,
    },
    {
      id: "thit_nguoi",
      name: "Thịt nguội",
      emoji: "🥓",
      unit: "phần",
      packSize: 10,
      costPerUnit: 3_500,
      shelfLifeDays: 2,
    },
    {
      id: "xiu_mai",
      name: "Xíu mại",
      emoji: "🧆",
      unit: "phần",
      packSize: 10,
      costPerUnit: 4_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "trung",
      name: "Trứng gà",
      emoji: "🥚",
      unit: "quả",
      packSize: 10,
      costPerUnit: 3_000,
      shelfLifeDays: 5,
    },
    {
      id: "dua_leo",
      name: "Dưa leo",
      emoji: "🥒",
      unit: "phần",
      packSize: 20,
      costPerUnit: 300,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "do_chua",
      name: "Đồ chua",
      emoji: "🥕",
      unit: "phần",
      packSize: 20,
      costPerUnit: 300,
      shelfLifeDays: 3,
    },
    {
      id: "hanh",
      name: "Hành lá",
      emoji: "🌱",
      unit: "nhúm",
      packSize: 30,
      costPerUnit: 100,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "ngo",
      name: "Ngò",
      emoji: "🌿",
      unit: "nhúm",
      packSize: 30,
      costPerUnit: 100,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "ot",
      name: "Ớt",
      emoji: "🌶️",
      unit: "phần",
      packSize: 30,
      costPerUnit: 100,
      shelfLifeDays: 3,
    },
    {
      id: "sot",
      name: "Nước sốt",
      emoji: "🥫",
      unit: "phần",
      packSize: 30,
      costPerUnit: 200,
      shelfLifeDays: null,
    },
    {
      id: "giay_goi",
      name: "Giấy gói",
      emoji: "📄",
      unit: "tờ",
      packSize: 50,
      costPerUnit: 200,
      shelfLifeDays: null,
    },
    {
      id: "ly_m",
      name: "Ly nhựa size M",
      emoji: "🥤",
      unit: "ly",
      packSize: 50,
      costPerUnit: 800,
      shelfLifeDays: null,
    },
    {
      id: "ly_l",
      name: "Ly nhựa size L",
      emoji: "🥤",
      unit: "ly",
      packSize: 50,
      costPerUnit: 1_000,
      shelfLifeDays: null,
    },
    {
      id: "cot_tra_sua",
      name: "Cốt trà sữa",
      emoji: "🍵",
      unit: "phần",
      packSize: 10,
      costPerUnit: 7_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "cot_tra_xanh",
      name: "Cốt trà xanh",
      emoji: "🍃",
      unit: "phần",
      packSize: 10,
      costPerUnit: 7_000,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "cot_hong_tra",
      name: "Cốt hồng trà",
      emoji: "🍂",
      unit: "phần",
      packSize: 10,
      costPerUnit: 7_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "da",
      name: "Đá viên",
      emoji: "🧊",
      unit: "phần",
      packSize: 40,
      costPerUnit: 300,
      shelfLifeDays: 1,
    },
    {
      id: "tran_chau_den",
      name: "Trân châu đen",
      emoji: "⚫",
      unit: "phần",
      packSize: 20,
      costPerUnit: 1_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "tran_chau_trang",
      name: "Trân châu trắng",
      emoji: "⚪",
      unit: "phần",
      packSize: 20,
      costPerUnit: 1_800,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "thach",
      name: "Thạch trái cây",
      emoji: "🟩",
      unit: "phần",
      packSize: 20,
      costPerUnit: 1_200,
      shelfLifeDays: 3,
    },
    {
      id: "pudding",
      name: "Pudding trứng",
      emoji: "🍮",
      unit: "phần",
      packSize: 20,
      costPerUnit: 2_000,
      shelfLifeDays: 2,
    },
    {
      id: "mang_nap",
      name: "Màng dán nắp",
      emoji: "🔘",
      unit: "tấm",
      packSize: 100,
      costPerUnit: 100,
      shelfLifeDays: null,
    },
    {
      id: "kep_hong",
      name: "Kẹp tóc hồng",
      emoji: "🎀",
      unit: "cái",
      packSize: 5,
      costPerUnit: 9_000,
      shelfLifeDays: null,
    },
    {
      id: "kep_xanh",
      name: "Kẹp tóc xanh",
      emoji: "💠",
      unit: "cái",
      packSize: 5,
      costPerUnit: 9_000,
      shelfLifeDays: null,
    },
    {
      id: "moc_meo",
      name: "Móc khóa mèo",
      emoji: "🐱",
      unit: "cái",
      packSize: 5,
      costPerUnit: 11_000,
      shelfLifeDays: null,
    },
    {
      id: "moc_cun",
      name: "Móc khóa cún",
      emoji: "🐶",
      unit: "cái",
      packSize: 5,
      costPerUnit: 11_000,
      shelfLifeDays: null,
    },
    {
      id: "day_buoc",
      name: "Dây buộc tóc",
      emoji: "🧶",
      unit: "cái",
      packSize: 10,
      costPerUnit: 5_000,
      shelfLifeDays: null,
    },
    {
      id: "giay_qua",
      name: "Giấy gói quà",
      emoji: "🎁",
      unit: "tờ",
      packSize: 20,
      costPerUnit: 1_500,
      shelfLifeDays: null,
    },
    // Phụ tùng sửa xe (sạp phụ tùng Chú Chín trong chợ): không hỏng nhưng vốn lớn (UC-G1).
    {
      id: "mieng_va",
      name: "Miếng vá",
      emoji: "🩹",
      unit: "miếng",
      packSize: 10,
      costPerUnit: 2_000,
      shelfLifeDays: null,
    },
    {
      id: "ruot_xe",
      name: "Ruột xe",
      emoji: "⭕",
      unit: "cái",
      packSize: 2,
      costPerUnit: 55_000,
      shelfLifeDays: null,
    },
    {
      id: "bugi",
      name: "Bugi",
      emoji: "⚡",
      unit: "cái",
      packSize: 2,
      costPerUnit: 35_000,
      shelfLifeDays: null,
    },
    {
      id: "ma_phanh",
      name: "Má phanh",
      emoji: "🛑",
      unit: "bộ",
      packSize: 2,
      costPerUnit: 40_000,
      shelfLifeDays: null,
    },
    {
      id: "bong_den",
      name: "Bóng đèn xe",
      emoji: "💡",
      unit: "cái",
      packSize: 2,
      costPerUnit: 15_000,
      shelfLifeDays: null,
    },
  ],

  equipment: [
    {
      id: "xe_banh_mi",
      name: "Xe bánh mì kính",
      price: 1_200_000,
      products: ["banh_mi"],
      queueSize: 4,
      model: "xe-banh-mi",
    },
    {
      id: "xe_tra_sua",
      name: "Xe đẩy trà sữa",
      price: 1_300_000,
      products: ["tra_sua"],
      queueSize: 4,
      model: "xe-tra-sua",
    },
    {
      id: "sap_phu_kien",
      name: "Sạp phụ kiện",
      price: 600_000,
      products: ["phu_kien"],
      queueSize: 3,
      model: "sap-phu-kien",
    },
    {
      id: "xe_do_nghe",
      name: "Xe đồ nghề sửa xe",
      price: 900_000,
      products: ["sua_xe"],
      queueSize: 3,
      model: "sap-phu-kien",
    },
  ],

  // Lịch tuần (docs/THEGIOI.md §2): cuối tuần học sinh nghỉ, văn phòng vắng; trong hẻm, gần chợ đông hơn.
  calendar: {
    weekdays: [
      { name: "Thứ Hai", short: "T2" },
      { name: "Thứ Ba", short: "T3" },
      { name: "Thứ Tư", short: "T4" },
      { name: "Thứ Năm", short: "T5" },
      { name: "Thứ Sáu", short: "T6" },
      { name: "Thứ Bảy", short: "T7", weekend: true },
      { name: "Chủ nhật", short: "CN", weekend: true },
    ],
    weekendTraffic: { school: 0.55, office: 0.5, residential: 1.25, market: 1.2 },
  },

  // Vào lại sau ít nhất 10 phút thì tóm tắt "Trong lúc bạn vắng…" (THEGIOI §4).
  away: { minMinutes: 10 },

  // Tiếng khu (THEGIOI §3): khu tụ nhiều quầy cùng nhóm hàng thì có tiếng, người qua lại tăng cho cả nhóm.
  districtFame: {
    perShop: 0.08,
    cap: 0.3,
    minShops: 2,
    groups: [
      { id: "an_uong", name: "khu ăn uống", emoji: "🍜", categories: ["breakfast", "drink"] },
      { id: "mua_sam", name: "khu mua sắm", emoji: "🛍️", categories: ["accessory"] },
      { id: "dich_vu", name: "phố sửa xe", emoji: "🔧", categories: ["repair"] },
    ],
  },

  trafficProfiles: [
    {
      id: "school",
      name: "Cổng trường",
      emoji: "🏫",
      likes: { drink: 1.3, accessory: 1.35, breakfast: 1.1, repair: 0.7 },
      peoplePerHour: {
        "6": 160,
        "7": 220,
        "8": 60,
        "10": 30,
        "11": 140,
        "12": 60,
        "14": 40,
        "16": 150,
        "17": 170,
        "18": 60,
        "20": 20,
      },
    },
    {
      id: "office",
      name: "Khu văn phòng",
      emoji: "🏢",
      likes: { drink: 1.2, breakfast: 1.2, accessory: 0.8, repair: 0.9 },
      peoplePerHour: {
        "6": 40,
        "7": 160,
        "8": 120,
        "10": 50,
        "11": 150,
        "12": 160,
        "13": 60,
        "16": 70,
        "17": 170,
        "18": 90,
        "20": 30,
      },
    },
    {
      id: "residential",
      name: "Trong hẻm",
      emoji: "🏘️",
      likes: { repair: 1.2, breakfast: 1, accessory: 0.9, drink: 0.95 },
      peoplePerHour: {
        "6": 60,
        "7": 80,
        "9": 40,
        "12": 40,
        "16": 60,
        "18": 90,
        "19": 100,
        "21": 60,
      },
    },
    {
      id: "market",
      name: "Gần chợ",
      emoji: "🧺",
      likes: { breakfast: 1.2, repair: 1.15, accessory: 1.05, drink: 0.9 },
      peoplePerHour: {
        "6": 180,
        "7": 200,
        "9": 150,
        "11": 90,
        "14": 50,
        "16": 80,
        "18": 70,
        "20": 30,
      },
    },
    {
      id: "crossroad",
      name: "Ngã tư",
      emoji: "🚦",
      likes: { repair: 1.05, drink: 1.05 },
      peoplePerHour: {
        "6": 120,
        "7": 180,
        "9": 110,
        "11": 120,
        "13": 90,
        "16": 140,
        "18": 180,
        "20": 140,
        "21": 90,
      },
    },
  ],

  // Vỉa hè bắc (z ≈ -3) và nam (z ≈ 3) của con phố thử nghiệm (apps/web/game/scene/Street.tsx).
  lots: [
    {
      id: "dau_hem",
      name: "Đầu hẻm 12",
      hint: "Dân trong hẻm, đông chiều tối",
      traffic: "residential",
      trafficScale: 1,
      rentPerDay: 40_000,
      position: { x: -18, z: -2.8 },
      facing: 0,
    },
    {
      id: "cong_truong",
      name: "Cổng trường",
      hint: "Học sinh đông sáng sớm, trưa, chiều",
      traffic: "school",
      trafficScale: 1,
      rentPerDay: 60_000,
      position: { x: -12, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "gan_cho",
      name: "Gần chợ",
      hint: "Sáng rất đông, chiều vắng",
      traffic: "market",
      trafficScale: 1,
      rentPerDay: 50_000,
      position: { x: -4.5, z: -2.8 },
      facing: 0,
    },
    {
      id: "nga_tu",
      name: "Góc ngã tư",
      hint: "Đông cả ngày, thuê đắt",
      traffic: "crossroad",
      trafficScale: 1.1,
      rentPerDay: 180_000,
      position: { x: 2.8, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "van_phong",
      name: "Trước toà văn phòng",
      hint: "Giờ đi làm, giờ trưa, tan tầm",
      traffic: "office",
      trafficScale: 1,
      rentPerDay: 75_000,
      position: { x: 9, z: -2.8 },
      facing: 0,
    },
    {
      id: "goc_cay",
      name: "Dưới gốc cây",
      hint: "Mát, khách lai rai",
      traffic: "residential",
      trafficScale: 0.8,
      rentPerDay: 20_000,
      position: { x: 14, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "cuoi_pho",
      name: "Cuối phố",
      hint: "Vắng, rẻ",
      traffic: "residential",
      trafficScale: 0.6,
      rentPerDay: 15_000,
      position: { x: 20, z: -2.8 },
      facing: 0,
    },
    {
      id: "ben_xe_buyt",
      name: "Trạm xe buýt",
      hint: "Người chờ xe cả ngày",
      traffic: "office",
      trafficScale: 0.9,
      rentPerDay: 45_000,
      position: { x: -22, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "nha_so_10",
      name: "🏠 Nhà mặt tiền số 10",
      hint: "Có tiệm trong nhà, bàn ghế cho khách ngồi, không lo mưa nắng",
      traffic: "residential",
      trafficScale: 1.5,
      rentPerDay: 105_000,
      position: { x: -12, z: -4.6 },
      facing: 0,
      kind: "house",
      // Ngồi tiệm có mái, ghế, biển hiệu: khách chịu giá cao hơn xe đẩy ~20%.
      priceTolerance: 1.2,
    },
    {
      id: "nha_so_24",
      name: "🏠 Nhà mặt tiền số 24",
      hint: "Tiệm sát ngã tư phía đông, khách đi làm ghé đông",
      traffic: "crossroad",
      trafficScale: 1.25,
      rentPerDay: 210_000,
      position: { x: 24, z: 4.6 },
      facing: Math.PI,
      kind: "house",
      // Ngồi tiệm có mái, ghế, biển hiệu: khách chịu giá cao hơn xe đẩy ~20%.
      priceTolerance: 1.2,
    },
  ],

  npcs: [
    {
      id: "hoc_sinh",
      name: "Học sinh",
      patienceSec: 35,
      transferRate: 0.2,
      model: "character-female-a",
      likes: { breakfast: 1.2, drink: 1.5, accessory: 1.3 },
    },
    {
      id: "dan_van_phong",
      name: "Dân văn phòng",
      patienceSec: 40,
      transferRate: 0.5,
      model: "character-male-c",
      likes: { breakfast: 1.3, drink: 1.1, accessory: 0.6 },
    },
    {
      id: "co_chu",
      name: "Cô chú trong xóm",
      patienceSec: 60,
      transferRate: 0.05,
      model: "character-female-d",
      likes: { breakfast: 1.1, drink: 0.5, accessory: 0.7 },
    },
    {
      id: "khach_vang_lai",
      name: "Khách vãng lai",
      patienceSec: 45,
      transferRate: 0.25,
      model: "character-male-a",
      likes: { breakfast: 1, drink: 1, accessory: 0.8 },
    },
    {
      // Khách VIP (sự kiện cá nhân, content.events): không ghé như khách thường.
      id: "vip",
      name: "Khách sộp",
      patienceSec: 40,
      transferRate: 0.8,
      model: "character-male-c",
      likes: { breakfast: 1, drink: 1, accessory: 1 },
    },
    {
      id: "reviewer",
      name: "Reviewer",
      patienceSec: 50,
      transferRate: 0.3,
      model: "character-male-a",
      likes: { breakfast: 1, drink: 1, accessory: 1 },
    },
  ],

  jobs: [
    {
      id: "phu_quan_com",
      name: "Phụ quán cơm Cô Tư",
      wagePerHour: 10_000,
      description:
        "Vào quán làm một vai: múc cơm, thu ngân hoặc bưng bê. Đông nhất giờ trưa và chiều tối.",
      maxStrikes: 6,
      roles: [
        {
          id: "dung_quay",
          name: "Đứng quầy múc cơm",
          emoji: "🍚",
          description: "Lấy dĩa, múc đúng món khách gọi, đưa dĩa.",
          piecePay: 3_000,
          guide: [
            "Con đứng quầy múc cơm nha. Khách xếp hàng trước quầy, gọi món — chữ hiện trên đầu khách và trên phiếu ở dưới.",
            "Nhìn dòng 'Cần múc' trên phiếu: ghi đủ những gì phải lên dĩa. Cơm sườn là cơm + sườn + dưa leo cà chua + canh; khách dặn thêm/bớt thì đã tính sẵn.",
            "Chạm từng khay để múc lên dĩa. Múc đủ món nào thì món đó có dấu ✓; múc thừa báo đỏ — chạm món trên dĩa để bỏ bớt.",
            "Đủ hết thì bấm '🤲 Đưa món'. Khay hết thì bấm '🔔 Báo bếp', đợi bếp mang khay mới ra.",
            "Khách chờ lâu sẽ than — bấm '🙏 Xin lỗi'. Múc đúng mỗi dĩa được tiền việc, giờ nào có làm thì có lương giờ. Kéo một ngón để xoay góc nhìn.",
          ],
        },
        {
          id: "thu_ngan",
          name: "Thu ngân",
          emoji: "🧾",
          description: "Bấm món lên máy, báo giá, thu tiền, thối tiền. Cuối ca kiểm két.",
          piecePay: 2_500,
          guide: [
            "Con đứng máy tính tiền. Khách ăn xong đứng dậy đi tới quầy, đưa phiếu cho con.",
            "Đọc từng dòng trên phiếu rồi bấm đúng món trên máy: dĩa cơm, thêm trứng/cơm, nước uống. Máy tự cộng TỔNG.",
            "Bấm 'Báo giá'. Khách chuyển khoản thì nhận luôn; đưa tiền mặt thì ghép tờ tiền để thối — cần thì bấm '💡 Tính giúp'.",
            "Tính dư thì khách bắt lỗi; tính thiếu hay thối thiếu thì cuối ca kiểm két, thiếu bao nhiêu trừ lương bấy nhiêu.",
            "Thấy khách đi ra mà chưa trả tiền thì bấm '📢 Gọi lại' liền nha!",
          ],
        },
        {
          id: "bung_be",
          name: "Bưng bê",
          emoji: "🍽️",
          description: "Bưng dĩa ra đúng bàn, dọn bàn khách ăn xong.",
          piecePay: 2_000,
          guide: [
            "Con bưng bê: dĩa múc xong đặt ở CỬA BẾP, mỗi dĩa kẹp số bàn.",
            "Tới cửa bếp (chạm vào đó hoặc bấm '📍 Tới cửa bếp') rồi bấm '🍽️ Lấy dĩa bàn …' — một lần cầm tối đa 2 dĩa.",
            "Bưng tới đúng bàn đó (bấm '📍 Mang dĩa tới bàn …' hoặc chạm cái bàn), tới nơi bấm '🤲 Giao món'. Đặt nhầm bàn là bị nhắc đó.",
            "Khách ăn xong để lại chén dĩa: tới bàn bấm '🧽 Lau bàn' — bàn bẩn thì khách mới không ngồi được.",
            "Bàn nào cãi nhau thì tới bấm '✋ Can ngăn'. Kéo một ngón để xoay góc nhìn, chụm hai ngón để thu/phóng.",
          ],
        },
      ],
    },
    {
      id: "giao_hang",
      name: "Giao hàng bưu cục Anh Tám",
      wagePerHour: 8_000,
      description:
        "Nhận đơn, soạn đúng gói trên kệ, chạy xe đi giao tận nhà, ký nhận, thu tiền hộ, về nộp tiền.",
      maxStrikes: 4,
      roles: [
        {
          id: "giao_hang",
          name: "Giao hàng",
          emoji: "📦",
          description: "Mỗi chuyến tối đa 3 đơn.",
          piecePay: 12_000,
          guide: [
            "Em nhận đơn ở quầy: bấm '📋 Nhận đơn giao', mỗi chuyến tối đa 3 đơn, mỗi đơn có mã XM-….",
            "Các gói trên kệ nhìn giống nhau — đọc kỹ mã rồi chạm đúng gói để soạn, soạn sai là bị nhắc.",
            "Soạn xong bấm '🛵 Ra xe đi giao'. Ngoài phố bấm '🛵 Đi tới' để chạy tới nhà; hàng dễ vỡ thì chạy chậm kẻo móp.",
            "Tới cửa bấm '🔔 Gọi khách', đưa điện thoại cho người ra mở cửa ký, kiểm tên người ký — người lạ thì không giao.",
            "Đơn thu hộ thì thu tiền, thối tiền. Khách vắng: gửi hàng xóm / hẹn lại / hoàn về. Giao xong về bưu cục bấm '💵 Nộp tiền'.",
          ],
        },
      ],
    },
  ],

  restaurant: {
    foods: [
      { id: "com", name: "Cơm", emoji: "🍚", model: "rice-ball" },
      { id: "suon", name: "Sườn nướng", emoji: "🍖", model: "meat-ribs" },
      { id: "bi", name: "Bì", emoji: "🥢", model: "mincemeat-pie" },
      { id: "cha", name: "Chả trứng", emoji: "🟨", model: "pudding" },
      { id: "trung", name: "Trứng ốp la", emoji: "🍳", model: "egg-cooked" },
      { id: "dua", name: "Dưa leo cà chua", emoji: "🥒", model: "tomato-slice" },
      { id: "canh", name: "Canh", emoji: "🥣", model: "bowl-soup" },
    ],
    dishes: [
      {
        id: "com_suon",
        name: "Cơm sườn",
        items: ["com", "suon", "dua", "canh"],
        price: 35_000,
        popularity: 3,
      },
      {
        id: "com_suon_bi_cha",
        name: "Cơm sườn bì chả",
        items: ["com", "suon", "bi", "cha", "dua", "canh"],
        price: 45_000,
        popularity: 2,
      },
      {
        id: "com_suon_trung",
        name: "Cơm sườn trứng",
        items: ["com", "suon", "trung", "dua", "canh"],
        price: 40_000,
        popularity: 2,
      },
      {
        id: "com_cha_trung",
        name: "Cơm chả trứng",
        items: ["com", "cha", "trung", "dua", "canh"],
        price: 32_000,
        popularity: 1,
      },
    ],
    mods: [
      { id: "them_trung", say: "thêm trứng", add: "trung", price: 6_000, chance: 0.2 },
      { id: "them_com", say: "thêm cơm", add: "com", price: 5_000, chance: 0.15 },
      { id: "khong_dua", say: "không dưa", remove: "dua", price: 0, chance: 0.15 },
      { id: "khong_canh", say: "khỏi canh", remove: "canh", price: 0, chance: 0.1 },
    ],
    drinks: [
      { id: "tra_da", name: "Trà đá", emoji: "🧊", price: 3_000, chance: 0.5 },
      { id: "nuoc_ngot", name: "Nước ngọt", emoji: "🥤", price: 12_000, chance: 0.15 },
    ],
    trayPortions: 10,
    refillSec: 15,
    tables: 6,
    customersPerHour: {
      "6": 2,
      "8": 3,
      "10": 5,
      "11": 12,
      "12": 14,
      "13": 7,
      "15": 3,
      "17": 10,
      "18": 11,
      "19": 6,
      "21": 2,
    },
    patienceSec: 45,
    // Quầy cơm ở z = 0 (bếp phía sau, z > 0), phòng ăn phía trước (z < 0), cửa ra vào ở tường trái.
    layout: {
      door: { x: -6.6, z: -2.4 },
      queue: { x: -0.2, z: -1.0 },
      queueStep: { x: -0.75, z: -0.35 },
      pass: { x: -2.4, z: -0.6 },
      cashier: { x: 2.3, z: -1.0 },
      cashierStep: { x: 0.7, z: -0.35 },
      tables: [
        { x: -2.9, z: -3.8 },
        { x: 0, z: -3.8 },
        { x: 2.9, z: -3.8 },
        { x: -2.9, z: -6.4 },
        { x: 0, z: -6.4 },
        { x: 2.9, z: -6.4 },
      ],
    },
  },

  // Bản đồ xóm (UC-B6): phố chính z = 0 (các địa điểm cũ giữ nguyên toạ độ), hai đường dọc x = ±28,
  // hai phố sau z = ±20, hẻm x = 0; công viên (tây bắc), chợ (tây nam), trường học (đông bắc), toà văn phòng + bãi xe (đông nam).
  map: {
    tile: 4,
    origin: { x: -52, z: -28 },
    rows: [
      "HHHHHH|HHHHHHHHHHHHH|HHHHHH",
      "ssssss|sssssssssssss|ssssss",
      "======+=============+======",
      "ssssss|sssssssssssss|ssssss",
      "BPPPPB|BBBBBBaBBBBBB|BKKKKB",
      "BPPPPB|BBBBBBaBBBBBB|BSSSSB",
      "ssssss|sssssssssNsss|ssssss",
      "======+======c======+======",
      "ssssss|sssssNsssssss|ssssss",
      "BMMMMB|BBBBBBaBBBBBB|BTTTTB",
      "BMMMMB|BBBBBBaBBBBBB|BLLLLB",
      "ssssss|sssssssssssss|ssssss",
      "======+=============+======",
      "ssssss|sssssssssssss|ssssss",
      "HHHHHH|HHHHHHHHHHHHH|HHHHHH",
    ],
  },

  // Mẫu khu ghép thêm khi xóm mở rộng (docs/BANDO.md §3 — lưới kiểu Township): đông/tây cao 15 ô, bắc/nam rộng 27 ô; đường ở
  // mép nối với đường của bản đồ gốc. "." = ô đất trống (bước C: thuê / mua / xây).
  chunks: [
    {
      id: "khu_dong",
      name: "Khu phía đông",
      side: "east",
      rows: [
        "HHHHHHH|HHHHHH",
        "sssssss|ssssss",
        "=======+======",
        "sssssss|ssssss",
        "BB..B..|..BB..",
        "BB..B..|..BB..",
        "sssssss|ssssss",
        "=======+======",
        "sssssss|ssssss",
        "..BB..B|B..BBB",
        "..BB..B|B..BBB",
        "sssssss|ssssss",
        "=======+======",
        "sssssss|ssssss",
        "HHHHHHH|HHHHHH",
      ],
    },
    {
      id: "khu_tay",
      name: "Khu phía tây",
      side: "west",
      rows: [
        "HHHHHH|HHHHHHH",
        "ssssss|sssssss",
        "======+=======",
        "ssssss|sssssss",
        "..BB..|..B..BB",
        "..BB..|..B..BB",
        "ssssss|sssssss",
        "======+=======",
        "ssssss|sssssss",
        "BBB..B|B..BB..",
        "BBB..B|B..BB..",
        "ssssss|sssssss",
        "======+=======",
        "ssssss|sssssss",
        "HHHHHH|HHHHHHH",
      ],
    },
    {
      id: "khu_bac",
      name: "Khu phía bắc",
      side: "north",
      rows: [
        "HHHHHH|HHHHHHHHHHHHH|HHHHHH",
        "ssssss|sssssssssssss|ssssss",
        "======+=============+======",
        "ssssss|sssssssssssss|ssssss",
        "HHHHHH|HHHHHHHHHHHHH|HHHHHH",
      ],
    },
    {
      id: "khu_nam",
      name: "Khu phía nam",
      side: "south",
      rows: [
        "HHHHHH|HHHHHHHHHHHHH|HHHHHH",
        "ssssss|sssssssssssss|ssssss",
        "======+=============+======",
        "ssssss|sssssssssssss|ssssss",
        "HHHHHH|HHHHHHHHHHHHH|HHHHHH",
      ],
    },
  ],

  // Sạp đồ ăn NPC theo giờ (UC-B9): sáng xôi, phở, cà phê; trưa nước mía; chiều bánh tráng, chè; tối ốc, nướng.
  vendors: [
    {
      id: "xoi_ba_bay",
      name: "Bà Bảy",
      sign: "XÔI BÀ BẢY",
      signColor: "#c0392b",
      model: "sap-phu-kien",
      seller: "character-female-d",
      position: { x: -44, z: -3 },
      facing: 0,
      open: 330,
      close: 600,
      seats: 2,
      cashOnly: true,
      lines: ["Xôi nóng đây con!", "Ăn xôi cho chắc bụng đi học!"],
      items: [
        { id: "xoi_ga", name: "Xôi gà", emoji: "🍗", price: 20_000, food: 55 },
        { id: "xoi_xeo", name: "Xôi xéo", emoji: "🍚", price: 15_000, food: 45 },
      ],
    },
    {
      id: "pho_chu_hai",
      name: "Chú Hai",
      sign: "PHỞ CHÚ HAI",
      signColor: "#8e44ad",
      model: "xe-banh-mi",
      seller: "character-male-c",
      position: { x: -36, z: 3 },
      facing: Math.PI,
      open: 330,
      close: 630,
      seats: 3,
      lines: ["Phở bò tái nạm đây!", "Nước lèo ninh từ khuya đó."],
      items: [
        { id: "pho_tai", name: "Phở tái", emoji: "🍜", price: 40_000, food: 70, drink: 15 },
        { id: "pho_ga", name: "Phở gà", emoji: "🍲", price: 35_000, food: 65, drink: 15 },
      ],
    },
    {
      id: "ca_phe_coc",
      name: "Cô Ba",
      sign: "CÀ PHÊ CÓC",
      signColor: "#6d4c41",
      model: "xe-tra-sua",
      seller: "character-female-a",
      position: { x: 36, z: 3 },
      facing: Math.PI,
      open: 360,
      close: 660,
      seats: 3,
      cashOnly: true,
      lines: ["Cà phê sữa đá hông con?", "Ngồi đây coi người qua lại nè."],
      items: [
        { id: "cf_sua_da", name: "Cà phê sữa đá", emoji: "🧋", price: 18_000, food: 5, drink: 45 },
        { id: "bac_xiu", name: "Bạc xỉu", emoji: "🥛", price: 20_000, food: 10, drink: 45 },
      ],
    },
    {
      id: "nuoc_mia",
      name: "Anh Tư",
      sign: "NƯỚC MÍA",
      signColor: "#27ae60",
      model: "xe-tra-sua",
      seller: "character-male-c",
      position: { x: 32, z: -3 },
      facing: 0,
      open: 600,
      close: 1020,
      seats: 2,
      lines: ["Nước mía tắc đây, mát lạnh!", "Trưa nắng uống ly nước mía đi em."],
      items: [
        { id: "nuoc_mia_ly", name: "Nước mía", emoji: "🥤", price: 12_000, food: 5, drink: 60 },
      ],
    },
    {
      id: "banh_trang_tron",
      name: "Chị Út",
      sign: "BÁNH TRÁNG TRỘN",
      signColor: "#e67e22",
      model: "sap-phu-kien",
      seller: "character-female-a",
      position: { x: 44, z: -3 },
      facing: 0,
      open: 840,
      close: 1140,
      seats: 2,
      lines: ["Bánh tráng trộn nè mấy đứa!", "Tan học ghé chị nha!"],
      items: [
        { id: "banh_trang", name: "Bánh tráng trộn", emoji: "🥗", price: 15_000, food: 30 },
        { id: "banh_trang_nuong", name: "Bánh tráng nướng", emoji: "🫓", price: 18_000, food: 30 },
      ],
    },
    {
      id: "che_co_nam",
      name: "Cô Năm",
      sign: "CHÈ CÔ NĂM",
      signColor: "#d35493",
      model: "xe-tra-sua",
      seller: "character-female-d",
      position: { x: -12, z: 17.5 },
      facing: 0,
      open: 840,
      close: 1230,
      seats: 3,
      lines: ["Chè thái, chè đậu đây!", "Ăn chè cho mát nha con."],
      items: [
        { id: "che_thai", name: "Chè thái", emoji: "🍧", price: 20_000, food: 20, drink: 35 },
        { id: "che_dau", name: "Chè đậu", emoji: "🍨", price: 15_000, food: 20, drink: 30 },
      ],
    },
    {
      id: "oc_dem",
      name: "Anh Sáu",
      sign: "ỐC ĐÊM",
      signColor: "#16a085",
      model: "sap-phu-kien",
      seller: "character-male-c",
      position: { x: -8, z: -17.5 },
      facing: Math.PI,
      open: 1050,
      close: 1320,
      seats: 4,
      lines: ["Ốc hương xào bơ tỏi đây!", "Tối rồi, làm dĩa ốc đi anh em!"],
      items: [
        { id: "oc_huong", name: "Ốc hương xào bơ", emoji: "🐚", price: 50_000, food: 40 },
        { id: "so_diep", name: "Sò điệp nướng", emoji: "🦪", price: 45_000, food: 35 },
      ],
    },
    {
      id: "nuong_dem",
      name: "Chú Tám",
      sign: "NƯỚNG ĐÊM",
      signColor: "#d35400",
      model: "xe-banh-mi",
      seller: "character-male-c",
      position: { x: 12, z: 17.5 },
      facing: 0,
      open: 1080,
      close: 1320,
      seats: 4,
      lines: ["Thịt nướng thơm lừng đây!", "Nướng tới đâu ăn tới đó!"],
      items: [
        { id: "xien_nuong", name: "Xiên nướng", emoji: "🍢", price: 10_000, food: 20 },
        { id: "bap_nuong", name: "Bắp nướng", emoji: "🌽", price: 12_000, food: 25 },
      ],
    },
  ],

  // Nhà trong xóm để giao hàng: trước mặt tiền, hai bên phố (Street.tsx).
  delivery: {
    addresses: [
      { id: "nha_3", label: "Nhà số 3", position: { x: -16, z: -5.2 }, facing: 0 },
      { id: "nha_7", label: "Nhà số 7", position: { x: -8, z: -5.2 }, facing: 0 },
      { id: "nha_12", label: "Nhà số 12", position: { x: 4, z: -5.2 }, facing: 0 },
      { id: "nha_18", label: "Nhà số 18", position: { x: 20, z: -5.2 }, facing: 0 },
      { id: "nha_5", label: "Nhà số 5", position: { x: -20, z: 5.2 }, facing: Math.PI },
      { id: "nha_9", label: "Nhà số 9", position: { x: -2, z: 5.2 }, facing: Math.PI },
      { id: "nha_15", label: "Nhà số 15", position: { x: 8, z: 5.2 }, facing: Math.PI },
      { id: "nha_21", label: "Nhà số 21", position: { x: 16, z: 5.2 }, facing: Math.PI },
    ],
    recipients: [
      "Anh Hùng",
      "Chị Mai",
      "Cô Lan",
      "Chú Tư",
      "Bạn Minh",
      "Chị Thảo",
      "Anh Khoa",
      "Bà Sáu",
    ],
    relatives: ["vợ", "chồng", "con", "em"],
    items: [
      { name: "Áo thun", fragile: false, value: 120_000 },
      { name: "Sách", fragile: false, value: 85_000 },
      { name: "Nồi cơm điện", fragile: true, value: 450_000 },
      { name: "Bộ chén sứ", fragile: true, value: 180_000 },
      { name: "Giày thể thao", fragile: false, value: 350_000 },
      { name: "Ốp điện thoại", fragile: false, value: 60_000 },
    ],
    absentRate: 0.15,
    codRate: 0.6,
    fragileDamageFast: 0.35,
    maxPerTrip: 3,
    shelfSize: 6,
  },

  // Địa điểm có người đứng quầy (docs/PLAN.md Phase 1.5). Toạ độ trên vỉa hè sát mặt tiền nhà.
  places: [
    {
      id: "vua_xe",
      name: "Vựa xe Ông Sáu",
      kind: "equipment_shop",
      sign: "VỰA XE ÔNG SÁU",
      signColor: "#2b2118",
      action: "🛒 Xem xe đẩy",
      keeper: {
        name: "Ông Sáu",
        model: "character-male-c",
        greeting: "Xe nào cũng chắc hết, con coi hợp nghề nào thì lấy nghề đó.",
        talk: {
          price: [
            "Xe bánh mì 320, xe trà sữa 380, sạp phụ kiện 280. Giá gốc, không nói thách.",
            "Xe cũ mang lại ông mua nửa giá, sòng phẳng.",
          ],
          gossip: [
            "Hồi trước ông cũng đẩy xe bán hủ tiếu gõ ở đầu hẻm này đó.",
            "Ngã tư đông mà tiền thuê cắt cổ, mới làm đừng ham.",
          ],
        },
      },
      position: { x: -21.5, z: -4.9 },
      facing: 0,
      props: [
        { model: "xe-banh-mi", dx: -1.8, dz: 0.3, rot: 0 },
        { model: "xe-tra-sua", dx: 1.8, dz: 0.3, rot: 0 },
        { model: "detail-awning-wide", dx: 0, dz: -1.2, rot: 0 },
      ],
    },
    {
      id: "cho_dau_moi",
      name: "Chợ đầu mối Bà Năm",
      kind: "market",
      sign: "CHỢ ĐẦU MỐI",
      signColor: "#f6b93b",
      action: "🧺 Vào chợ",
      keeper: {
        name: "Bà Năm",
        model: "character-female-d",
        greeting: "Hàng mới về sáng nay nè con. Đồ ăn thì lấy vừa đủ bán, để qua đêm là bỏ.",
        talk: {
          price: [
            "Sáng giá gốc, qua trưa đồ tươi là bà lấy thêm chút vì hàng còn ít.",
            "Mua từ 5 gói trở lên bà bớt cho.",
          ],
          gossip: [
            "Nghe nói mai trường tan sớm đó, bán ở cổng trường là trúng.",
            "Mấy bữa nay trà sữa bán chạy dữ lắm, tụi nhỏ mê trân châu trắng.",
          ],
        },
      },
      position: { x: -6.5, z: 4.9 },
      facing: Math.PI,
      props: [
        { model: "detail-parasol-a", dx: -1.4, dz: 0, rot: 0 },
        { model: "detail-parasol-b", dx: 1.4, dz: 0.2, rot: 0 },
        { model: "ghe-nhua-do", dx: -0.6, dz: 0.8, rot: 0.4 },
        { model: "detail-awning-wide", dx: 0, dz: 1.2, rot: Math.PI },
      ],
    },
    {
      id: "quan_com",
      name: "Quán cơm Cô Tư",
      kind: "job",
      sign: "CƠM TẤM CÔ TƯ",
      signColor: "#e4432d",
      action: "🍚 Vào quán",
      keeper: {
        name: "Cô Tư",
        model: "character-female-a",
        greeting: "Trưa nay đông lắm, phụ cô một tay đi con!",
        talk: {
          price: [
            "Cơm tấm cô bán 30 ngàn một dĩa, phụ quán cô trả 10 ngàn một giờ.",
            "Làm siêng cô thưởng thêm.",
          ],
          gossip: [
            "Dân văn phòng trưa nào cũng kéo qua đây, 11 giờ là đông nghẹt.",
            "Con bé bán bánh mì đầu hẻm dạo này đông khách ghê.",
          ],
        },
      },
      jobs: ["phu_quan_com"],
      position: { x: 15, z: -4.9 },
      facing: 0,
      props: [
        { model: "ghe-nhua-do", dx: -1.6, dz: 0.9, rot: 0.2 },
        { model: "ghe-nhua-do", dx: -0.9, dz: 1.3, rot: -0.3 },
        { model: "ghe-nhua-do", dx: 1.1, dz: 1.1, rot: 0.6 },
        { model: "detail-parasol-a", dx: -1.2, dz: 1.1, rot: 0 },
        { model: "detail-awning-wide", dx: 0, dz: -1.2, rot: 0 },
      ],
    },
    {
      id: "tram_xe_om",
      name: "Trạm xe ôm gốc me",
      kind: "ride",
      sign: "XE ÔM",
      signColor: "#d4881c",
      action: "🛵 Ra trạm xe ôm",
      keeper: {
        name: "Chú Lực",
        model: "character-male-c",
        greeting: "Muốn chạy xe ôm hả? Chú cho thuê con Wave cũ, xăng tự đổ nghen.",
        talk: {
          price: [
            "Xe chú cho thuê 30 ngàn một ngày, xăng con tự lo.",
            "Nói thách vừa thôi, khách quen người ta biết giá hết đó.",
          ],
          gossip: [
            "Giờ tan tầm đường lớn kẹt cứng, chui hẻm cho lẹ.",
            "Trời mưa khách dễ chịu giá, mà hẻm trơn lắm, chạy từ từ.",
          ],
        },
      },
      jobs: [],
      position: { x: -32, z: -3.6 },
      facing: 0,
      props: [
        { model: "road-sign-street", dx: 1.2, dz: 0.2, rot: 0 },
        { model: "ghe-nhua-do", dx: -1, dz: 0.3, rot: 0.6 },
      ],
    },
    {
      id: "buu_cuc",
      name: "Bưu cục",
      kind: "job",
      sign: "BƯU CỤC",
      signColor: "#2f7d4f",
      action: "📦 Vào bưu cục",
      keeper: {
        name: "Anh Tám",
        model: "character-male-a",
        greeting: "Có xe máy chưa em? Có thì chạy đơn quanh xóm, trả theo giờ.",
        talk: {
          price: [
            "Chạy đơn anh trả 12 ngàn một giờ, giao lẹ có thưởng.",
            "Cuối tuần đơn nhiều lắm.",
          ],
          gossip: [
            "Chiều nay có mưa đó, lo mà che hàng.",
            "Văn phòng đầu phố hay đặt trà sữa buổi chiều.",
          ],
        },
      },
      jobs: ["giao_hang"],
      position: { x: 19.5, z: 4.9 },
      facing: Math.PI,
      props: [{ model: "detail-awning-wide", dx: 0, dz: 1.2, rot: Math.PI }],
    },
  ],

  speakers: [
    {
      id: "chu_bay",
      name: "Chú Bảy xe ôm",
      model: "character-male-c",
      position: { x: -8, z: -4.6 },
      facing: Math.PI / 2,
    },
  ],

  // Kịch bản người mới — rẽ nhánh buôn bán / làm thuê.
  tutorial: [
    {
      id: "gap_chu_bay",
      speaker: "chu_bay",
      lines: [
        "Ủa, con là người mới dọn về xóm hả? Chú là Bảy, chạy xe ôm đầu hẻm nè.",
        `Ở xóm này ai cũng tự lo lấy cái nghề. Trong túi con có ${spoken(START_CASH)} tiền mặt, thêm ${spoken(START_BANK)} trong tài khoản ngân hàng.`,
        "Đủ sắm một chiếc xe đẩy, nhập hàng mà vẫn còn dư phòng thân — tiền ngân hàng rút ở cây ATM nha.",
        "Còn chưa chắc tay thì qua quán cơm Cô Tư phụ việc, kiếm vốn trước cũng được.",
      ],
      choices: [
        { text: "Con muốn buôn bán", next: "den_vua_xe" },
        { text: "Con đi làm thuê trước", next: "den_quan_com" },
        { text: "Con tự lo được, cảm ơn chú", next: "hoan_thanh" },
      ],
    },
    {
      id: "den_vua_xe",
      objective: "Tới vựa xe Ông Sáu mua một chiếc xe đẩy",
      target: "vua_xe",
      until: "has_business",
      next: "ra_cho",
    },
    {
      id: "ra_cho",
      speaker: "chu_bay",
      lines: [
        "Có xe rồi hả? Giờ ra chợ đầu mối Bà Năm mua nguyên liệu — món nào cần gì thì mua nấy.",
        "Bánh mì thì phải có ổ bánh, nhân, rau, gia vị, giấy gói. Đồ tươi để qua đêm là hư, mua vừa đủ thôi nghe!",
      ],
      objective: "Ra chợ mua đủ nguyên liệu cho một món",
      target: "cho_dau_moi",
      until: "has_stock",
      next: "chon_cho",
    },
    {
      id: "chon_cho",
      speaker: "chu_bay",
      lines: [
        "Giờ chọn chỗ bán. Chỗ đông khách thì thuê đắt — mới làm nên thử Đầu hẻm 12, rẻ mà có khách.",
      ],
      objective: "Chọn chỗ bán (☰ Menu → 📍 Chỗ bán)",
      until: "has_lot",
      next: "ra_quay",
    },
    {
      id: "ra_quay",
      objective: "Đẩy xe tới chỗ bán và mở quầy",
      target: "stall",
      until: "shop_open",
      next: "phuc_vu",
    },
    {
      id: "phuc_vu",
      speaker: "chu_bay",
      lines: [
        "Mở hàng rồi đó! Khách tới sẽ dặn món, con nghe cho kỹ: không hành là không hành nghe chưa.",
        "Làm xong thì tính tiền, thối tiền cho đúng. Làm lẹ, làm đúng là khách boa, lại nhớ quầy mình.",
      ],
      objective: "Phục vụ 3 khách: làm đúng món, thối đúng tiền",
      target: "stall",
      until: "served_3",
      next: "xong_buon_ban",
    },
    {
      id: "xong_buon_ban",
      speaker: "chu_bay",
      lines: [
        "Được rồi đó con! Nhớ nè: hết hàng thì ra chợ nhập thêm, đừng để khách về tay không.",
        "Tối coi sổ sách cuối ngày cho kỹ. Thôi chú chạy cuốc xe đây, chúc con đắt hàng!",
      ],
      next: "hoan_thanh",
    },
    {
      id: "den_quan_com",
      objective: "Tới quán cơm Cô Tư, bước vào và chọn một việc",
      target: "quan_com",
      until: "has_job",
      next: "lam_viec",
    },
    {
      id: "lam_viec",
      objective: "Làm đúng 2 việc trong quán (múc dĩa, tính tiền hay bưng bàn)",
      target: "quan_com",
      until: "job_tasks_2",
      next: "xong_lam_thue",
    },
    {
      id: "xong_lam_thue",
      speaker: "chu_bay",
      lines: [
        "Siêng dữ ha! Làm thuê thì chắc ăn: có lương giờ, làm đúng việc nào ăn tiền việc đó.",
        "Khi nào có vốn thì ghé vựa xe Ông Sáu, tự làm chủ cái quầy. Chú đi đây!",
      ],
      next: "hoan_thanh",
    },
    // Hết kịch bản người mới.
    { id: "hoan_thanh" },
  ],

  quickPhrases: [
    { id: "rao_hang", text: "Mời ghé ủng hộ nha! Nóng giòn đây!", shout: true },
    { id: "chao", text: "Chào cả xóm!" },
    { id: "cam_on", text: "Cảm ơn nha!" },
    { id: "xin_loi_het", text: "Xin lỗi, hết hàng rồi!" },
    { id: "cho_chut", text: "Đợi xíu nha, có liền!" },
    { id: "vui", text: "😄" },
    { id: "vay_tay", text: "👋" },
  ],

  // Khung đứng trước quầy hàng xóm (UC-E5): lời chào / xác nhận món hiện cạnh chân dung chủ quầy.
  counterLines: {
    hello: [
      "Ghé quầy nè! Ăn gì nói mình nha 😄",
      "Chào nha! Món nào cũng làm liền tay.",
      "Mời ghé! Hôm nay đồ tươi lắm.",
    ],
    picked: ["{dish} hả? Có liền, {price} nha!", "Ok {dish}, {price} — đợi xíu là có!"],
    soldOut: "Nay bán hết sạch rồi, ghé lại sau nha!",
  },

  // Đói / khát (UC-B11): no tụt từ 100 xuống 0 trong ~10 giờ game, khát ~7 giờ; ngủ đêm chỉ tính 4 giờ.
  needs: {
    foodPerHour: 10,
    drinkPerHour: 14,
    nightMinutes: 240,
    lowAt: 30,
    slowHold: 1.25,
    byCategory: { breakfast: { food: 45, drink: 0 }, drink: { food: 10, drink: 55 } },
    callouts: [
      "Ơi có ai bán không dạ?",
      "Chủ quán đâu rồi ta?",
      "Bán cho con với… có ai không?",
      "Quầy mở mà không thấy ai, thôi đi chỗ khác",
    ],
  },

  // Quỹ xóm + công trình chung (UC-J5). Giá tham khảo công trình nông thôn (đã nén như mọi số tiền trong game).
  fund: { feeShare: 0.6, voteMinutes: 240, donateStep: 10_000 },
  crew: {
    keeper: "Cai Lâm",
    // Ngoài đời phụ hồ 300–450k/ngày, một ngày trộn ~25–30 mẻ vữa → ~12k/mẻ.
    laborShare: 0.25,
    wagePerMix: 12_000,
    mixMinutes: 10,
    waterTolerance: 0.15,
    bags: [1, 3],
    // Định mức hay dùng ở công trình (1 bao xi măng 50 kg : thùng cát 18 lít : lít nước).
    mixes: [
      {
        id: "vua_xay",
        name: "Vữa xây tường",
        use: "xây tường 110, 220",
        sandPerBag: 9,
        waterPerBag: 20,
      },
      {
        id: "vua_trat",
        name: "Vữa trát tường",
        use: "tô trát mặt tường",
        sandPerBag: 8,
        waterPerBag: 20,
      },
      {
        id: "vua_mac75",
        name: "Vữa mác 75",
        use: "tường chịu lực nhẹ, lót nền",
        sandPerBag: 10,
        waterPerBag: 22,
      },
    ],
  },
  projects: [
    {
      id: "lat_hem_12",
      name: "Lát bê tông hẻm 12",
      emoji: "🛣️",
      description: "Đổ bê tông con hẻm đất đầu xóm, mưa không còn sình lầy.",
      why: "Mưa xuống hẻm sình, khách ngại vô đầu hẻm mua đồ.",
      cost: 600_000,
      buildDays: 2,
      demand: { lots: ["dau_hem", "goc_cay"], mult: 1.15 },
    },
    {
      id: "den_duong",
      name: "Đèn đường năng lượng mặt trời",
      emoji: "💡",
      description: "Dựng 6 trụ đèn dọc trục chính, tối đi lại sáng sủa.",
      why: "Chiều tối đường tối thui, người ta ngại ra đường ăn uống.",
      cost: 900_000,
      buildDays: 2,
      demand: { lots: ["nga_tu", "ben_xe_buyt", "nha_so_10", "nha_so_24"], mult: 1.08 },
    },
    {
      id: "mo_rong_cho",
      name: "Mở rộng mái che chợ",
      emoji: "⛺",
      description: "Dựng thêm mái tôn che nắng mưa quanh chợ đầu mối.",
      why: "Trời mưa là khách chạy hết, sạp gần chợ vắng hoe.",
      cost: 1_200_000,
      buildDays: 3,
      demand: { lots: ["gan_cho"], mult: 1.2 },
    },
    {
      id: "cau_tre",
      name: "Cầu tre qua mương cuối phố",
      emoji: "🌉",
      description: "Bắc cầu tre qua con mương, bà con xóm bên kia sang mua bán được.",
      why: "Cuối phố vắng vì xóm bên kia phải đi vòng cả cây số.",
      cost: 800_000,
      buildDays: 3,
      demand: { lots: ["cuoi_pho"], mult: 1.35 },
    },
    {
      id: "cau_be_tong",
      name: "Nâng cầu tre thành cầu bê tông",
      emoji: "🌁",
      description: "Thay cầu tre bằng cầu bê tông, xe máy chạy qua được.",
      why: "Cầu tre chỉ đi bộ được, xe chở hàng không qua nổi.",
      cost: 2_500_000,
      buildDays: 5,
      demand: { lots: ["cuoi_pho", "goc_cay"], mult: 1.2 },
      requires: "cau_tre",
    },
    {
      id: "ao_ca",
      name: "Đào ao cá + ghế đá công viên",
      emoji: "🎣",
      description: "Đào cái ao nhỏ thả cá, đặt ghế đá — chiều chiều người ta ra hóng mát.",
      why: "Xóm chưa có chỗ ngồi chơi, chiều tối ai cũng ở nhà.",
      cost: 1_500_000,
      buildDays: 4,
      demand: { lots: ["cong_truong", "van_phong", "goc_cay"], mult: 1.1 },
    },
  ],

  // Bảng giải của xóm (UC-P2): 7 ngày gần nhất, mỗi hạng mục một kiểu người chơi — không chỉ người giàu nhất.
  awards: [
    {
      id: "doanh_nhan",
      emoji: "💰",
      name: "Doanh nhân của tuần",
      description: "Doanh thu bán hàng 7 ngày",
      metric: "revenue",
    },
    {
      id: "lai_gioi",
      emoji: "🧮",
      name: "Buôn có lời nhất",
      description: "Lãi sau tiền hàng, thuê chỗ, phí",
      metric: "profit",
    },
    {
      id: "dong_khach",
      emoji: "👥",
      name: "Đông khách nhất",
      description: "Số món đã bán 7 ngày",
      metric: "served",
    },
    {
      id: "duoc_tin",
      emoji: "⭐",
      name: "Quầy được tin nhất",
      description: "Điểm đánh giá trung bình (ít nhất 3 đánh giá)",
      metric: "rating",
      min: 3,
    },
    {
      id: "tang_nhanh",
      emoji: "📈",
      name: "Lên như diều",
      description: "Doanh thu 3 ngày gần nhất so với 3 ngày trước",
      metric: "growth",
    },
    {
      id: "cham_lam",
      emoji: "💼",
      name: "Chăm làm nhất",
      description: "Tiền công làm thuê 7 ngày",
      metric: "wages",
    },
    {
      id: "than_thien",
      emoji: "🤝",
      name: "Thân thiện nhất",
      description: "Điểm kỹ năng Ăn nói",
      metric: "friendly",
    },
  ],

  // Cư dân có tên (KIENTRUC §1): khách tới quầy là người cụ thể, quầy nhớ họ ghé mấy lần → khách quen ❤️.
  residents: [
    {
      id: "be_su",
      name: "Bé Su",
      archetype: "hoc_sinh",
      favorite: "drink",
      bio: "học lớp 5, mê trà sữa",
    },
    {
      id: "ti_sun",
      name: "Tí Sún",
      archetype: "hoc_sinh",
      favorite: "breakfast",
      bio: "lớp 7, sáng nào cũng trễ học",
    },
    {
      id: "be_na",
      name: "Bé Na",
      archetype: "hoc_sinh",
      favorite: "accessory",
      bio: "lớp 11, có kênh 'Na Ăn Gì'",
    },
    {
      id: "khoa_lop9",
      name: "Khoa lớp 9",
      archetype: "hoc_sinh",
      favorite: "drink",
      bio: "đá banh chiều nào cũng khát",
    },
    {
      id: "bong",
      name: "Bông",
      archetype: "hoc_sinh",
      favorite: "accessory",
      bio: "sưu tầm móc khóa",
    },
    {
      id: "chi_thao",
      name: "Chị Thảo",
      archetype: "dan_van_phong",
      favorite: "breakfast",
      bio: "kế toán, ăn sáng vội",
    },
    {
      id: "anh_duy",
      name: "Anh Duy",
      archetype: "dan_van_phong",
      favorite: "drink",
      bio: "dân IT, cà phê thay nước",
    },
    {
      id: "chi_mai",
      name: "Chị Mai",
      archetype: "dan_van_phong",
      favorite: "breakfast",
      bio: "làm ngân hàng đầu phố",
    },
    {
      id: "anh_vu",
      name: "Anh Vũ",
      archetype: "dan_van_phong",
      favorite: "repair",
      bio: "chạy sale, xe hay hư",
    },
    {
      id: "chi_quyen",
      name: "Chị Quyên",
      archetype: "dan_van_phong",
      favorite: "drink",
      bio: "ghiền trà sữa ít đường",
    },
    {
      id: "ba_tu",
      name: "Bà Tư",
      archetype: "co_chu",
      favorite: "breakfast",
      bio: "bán vé số đầu hẻm",
    },
    {
      id: "chu_phuc",
      name: "Chú Phúc",
      archetype: "co_chu",
      favorite: "breakfast",
      bio: "bảo vệ trường làng",
    },
    {
      id: "co_hanh",
      name: "Cô Hạnh",
      archetype: "co_chu",
      favorite: "drink",
      bio: "giáo viên dạy văn",
    },
    {
      id: "ong_tam",
      name: "Ông Tám",
      archetype: "co_chu",
      favorite: "breakfast",
      bio: "hưu trí, đi bộ mỗi sáng",
    },
    {
      id: "di_ut",
      name: "Dì Út",
      archetype: "co_chu",
      favorite: "breakfast",
      bio: "bán rau ở chợ",
    },
    {
      id: "chu_luc",
      name: "Chú Lực",
      archetype: "co_chu",
      favorite: "repair",
      bio: "chạy xe ôm gốc me",
    },
    {
      id: "bac_hai",
      name: "Bác Hai",
      archetype: "co_chu",
      favorite: "repair",
      bio: "thợ mộc, xe Cub cũ",
    },
    {
      id: "co_lan",
      name: "Cô Lan",
      archetype: "co_chu",
      favorite: "accessory",
      bio: "thợ may, mua quà cho cháu",
    },
  ],

  regulars: {
    greetAt: 3,
    regularAt: 5,
    patienceMul: 1.3,
    friendChance: 0.2,
    angryStreak: 2,
    returning: ["Bữa nay ghé nữa nè!", "Lại là tui nè!", "Ghé quầy quen nè!"],
    usual: ["Như mọi khi nha!", "Món quen nha con!", "Cũ người cũ món nha!"],
  },

  // Nhân viên thuê đứng quầy thay (KIENTRUC §2): bán khi chủ rời quầy / thoát game, tới hết ca; trả lương theo giờ.
  shopSetup: {
    depositDays: 3,
    reserveDays: 2,
    license: { office: "UBND phường", fee: 100_000, minutes: 180 },
    foodCert: { templates: ["FOOD"], trainingFee: 150_000, inspectAfter: 90, inspectWindow: 60 },
    signFee: 200_000,
    name: { min: 3, max: 24 },
    // Đòi tiền nhà (UC-F13): 17h chủ nhà tới nhắc, chưa hẹn thì hạn 20h cùng ngày; hẹn theo NGÀY (cả ngày hẹn trả được,
    // qua ngày hẹn là thất hẹn). Quá hạn / thất hẹn → trừ cọc + phí trễ; trễ lần 3 → dẹp tiệm.
    rent: {
      remindMinute: 17 * 60,
      dueMinute: 20 * 60,
      maxPromiseDays: 2,
      lateFeePct: 10,
      evictAfterStrikes: 3,
      trustLate: 5,
      landlords: [
        {
          id: "co_tu_huong",
          name: "Cô Tư Hường",
          tag: "Chủ nhà số 10",
          model: "character-female-d",
          lotIds: ["nha_so_10"],
          lines: {
            remind: [
              "Con ơi, tiền nhà {owed} nghen. Cô ghé lấy luôn cho tiện, khỏi con chạy qua.",
              "Bữa nay tới kỳ tiền nhà rồi đó con, {owed}. Cô không hối, mà cô cũng phải đóng tiền điện.",
              "Buôn bán được hông con? Tiền nhà {owed} nha. Kẹt thì nói cô, cô cho hẹn ngày.",
            ],
            promised: [
              "Hôm nay tới hẹn rồi nghen con: {owed}, cộng phí trễ {fee}. Cô tin con mới cho hẹn đó.",
              "Hẹn hôm nay mà con. {owed} với phí trễ {fee}, trong bữa nay đưa cô là được.",
            ],
            promise: [
              "Thôi được, cô cho con tới {day}. Nhớ nha, phí trễ {fee} đó.",
              "Ừ, {day} nghen. Cô ghi sổ rồi, đừng để cô phải tới lần nữa.",
            ],
            paid: [
              "Đủ rồi, cô cảm ơn nghen. Buôn may bán đắt nha con!",
              "Rồi, cô ghi sổ. Có gì hư hỏng trong nhà cứ nói cô.",
            ],
            late: [
              "Cô chờ hoài không thấy con… Cô trừ {owed} vô tiền cọc nghen. Lần sau vậy nữa là cô lấy nhà đó.",
              "Quá hạn rồi con. Cô trừ cọc {owed}, kể cả phí trễ. Cô cũng khó lắm chớ bộ.",
            ],
            evict: [
              "Thôi con ơi, trễ hoài vầy cô chịu hết nổi. Cô lấy lại nhà, đồ nghề cô dọn ra vỉa hè rồi đó.",
              "Cọc hết, hẹn cũng không giữ… Cô cho người khác thuê. Con dọn đồ giùm cô.",
            ],
          },
        },
        {
          id: "chu_nam_loc",
          name: "Chú Năm Lộc",
          tag: "Chủ nhà số 24",
          model: "character-male-c",
          lotIds: ["nha_so_24"],
          lines: {
            remind: [
              "Ê chủ tiệm! Tiền nhà {owed}, chú qua lấy nè. Mặt tiền ngã tư đâu có rẻ.",
              "Tới kỳ rồi nghe, {owed}. Trả gọn trong bữa nay là chú vui.",
              "Tiệm đông dữ ha. Vậy tiền nhà {owed} chắc dễ rồi há?",
            ],
            promised: [
              "Bữa nay hẹn rồi nghe: {owed}, phí trễ {fee}. Chú giữ lời, con cũng giữ lời.",
              "Tới hẹn rồi đó. {owed} cộng {fee} phí trễ, đừng để chú nói nặng.",
            ],
            promise: [
              "Hẹn {day} nghe chưa. Phí trễ {fee}, chú nói trước cho rõ.",
              "Được, {day}. Làm ăn ai cũng có lúc kẹt, nhưng đừng thành thói nghe.",
            ],
            paid: [
              "Sòng phẳng vậy mới làm ăn lâu dài được. Cảm ơn nghe!",
              "Đủ rồi. Mặt tiền chú cho thuê là để người làm ăn đàng hoàng như con.",
            ],
            late: [
              "Quá giờ rồi. Chú trừ {owed} vô cọc. Thêm vài lần nữa là chú lấy nhà, đừng trách.",
              "Không thấy tiền, không thấy người. Trừ cọc {owed} — lần sau chú không nói nhiều vậy đâu.",
            ],
            evict: [
              "Hết nói nổi. Chú lấy lại mặt tiền, đồ nghề để ngoài vỉa hè đó. Hợp đồng chấm dứt.",
              "Cọc hết, hẹn lỡ hoài. Chú dẹp tiệm, cho người khác thuê. Đi đi con.",
            ],
          },
        },
      ],
    },
  },

  rides: {
    stationPlaceId: "tram_xe_om",
    jamProfile: "crossroad",
    bikeRentPerDay: 30_000,
    fuelPer100m: 1_000,
    baseFare: 12_000,
    farePer100m: 8_000,
    minMeters: 18,
    haggle: [
      { ratio: 0.9, label: "Bớt chút" },
      { ratio: 1, label: "Giá chuẩn" },
      { ratio: 1.25, label: "Nhích lên" },
      { ratio: 1.6, label: "Nói thách" },
    ],
    acceptSlope: 1.4,
    rainAcceptBonus: 0.25,
    routes: {
      road: { name: "Đường lớn", speed: 7.5, jamSlow: 0.6 },
      alley: { name: "Đi hẻm", speed: 5.5, rainSlow: 0.35 },
    },
    expectSpeed: 5.5,
    // Cân lại (pnpm balance): 6 phút → ~46 cuốc, lãi ~630k/ngày (gấp 4 làm thuê); 15 → ~23 cuốc, ~300k (gấp 2).
    waitMinutes: 15,
    tip: { five: [2_000, 5_000], four: [0, 2_000] },
    lines: {
      ask: [
        "Chú ơi, chở tui tới {place} bao nhiêu?",
        "Anh xe ôm ơi, ra {place} nhiêu tiền?",
        "Con ơi chở cô về {place}, lấy bao nhiêu?",
      ],
      accept: ["Ừ, đi lẹ giùm cái.", "Được, chạy đi con.", "Ok chốt, đi thôi!"],
      refuse: [
        "Mắc quá, thôi tui đi bộ cho khoẻ.",
        "Giá cắt cổ vậy ai đi, thôi khỏi!",
        "Hông được đâu, để kêu xe khác.",
      ],
      stars: {
        "5": ["Chạy êm mà lẹ ghê, lần sau kêu nữa nha!", "Tay lái lụa luôn, boa nè."],
        "4": ["Cũng được, cảm ơn nghen.", "Ổn áp, hôm sau đi tiếp."],
        "3": ["Hơi lâu ha, mà thôi cũng tới.", "Lần sau chạy lẹ chút nha."],
        "2": ["Trời đất, đi gì lâu dữ vậy!", "Xóc muốn rớt ruột luôn á."],
        "1": ["Thôi khỏi đi nữa.", "Lần sau tui kêu xe khác."],
      },
    },
  },

  gigs: {
    // Phí ghi sổ nhỏ vào quỹ xóm (Chú Hai giữ sổ, đứng ra phân xử) — money sink.
    feeRate: 0.05,
    feeMin: 2000,
    reviewMinutes: 120,
    disputeLostTrust: 5,
    photo: {
      mentor: "Bé Na (kênh Na Ăn Gì)",
      // Ngoài đời thợ chụp tự do ~150k/giờ, chụp món ~150k/món; quầy nhỏ trong xóm thuê buổi ngắn rẻ hơn.
      rewards: [60000, 100000, 150000],
      hours: [2, 4, 8],
      minTrust: 30,
      cameraRent: 20000,
      sessionMs: 20000,
      moments: 6,
      windowMs: 900,
      perfectMs: 180,
      shots: 8,
      keep: 3,
      passQuality: 55,
      adBoost: 0.6,
      adMinutes: 180,
      kinds: [
        { emoji: "😄", label: "Khách cười tươi" },
        { emoji: "♨️", label: "Món bốc khói" },
        { emoji: "🌤️", label: "Nắng xiên đẹp" },
        { emoji: "🙌", label: "Chủ quầy tạo dáng" },
        { emoji: "🥢", label: "Gắp miếng đầu tiên" },
      ],
    },
  },
  contracts: {
    keeper: "Chú Hai tổ trưởng",
    perDay: 3,
    depositRate: 0.2,
    trust: { start: 50, done: 5, fail: 15, short: 2, lowAt: 30, lockAt: 15, lockDays: 3 },
    templates: [
      {
        id: "truong_banh_mi",
        poster: "Cô Hạnh giáo viên",
        productId: "banh_mi",
        variantId: "banh_mi_thit",
        qty: [5, 8],
        lotId: "cong_truong",
        deadline: 11 * 60,
        priceMul: 1.25,
        minTrust: 0,
        text: "Giao {qty} {dish} cho đội bóng lớp 5 ở {place} trước {deadline}",
      },
      {
        id: "xe_buyt_banh_mi",
        poster: "Chú tài xế tuyến 19",
        productId: "banh_mi",
        variantId: "banh_mi_trung",
        qty: [4, 6],
        lotId: "ben_xe_buyt",
        deadline: 14 * 60,
        priceMul: 1.2,
        minTrust: 0,
        text: "Mang {qty} {dish} ra {place} cho cánh tài xế trước {deadline}",
      },
      {
        id: "tiec_xom_banh_mi",
        poster: "Chú Hai tổ trưởng",
        productId: "banh_mi",
        variantId: "banh_mi_thit",
        qty: [12, 16],
        lotId: "dau_hem",
        deadline: 19 * 60,
        priceMul: 1.35,
        minTrust: 60,
        text: "Họp tổ dân phố: {qty} {dish} giao tới {place} trước {deadline}",
      },
      {
        id: "van_phong_tra_sua",
        poster: "Chị Thảo kế toán",
        productId: "tra_sua",
        variantId: "tra_sua_truyen_thong",
        qty: [5, 8],
        lotId: "van_phong",
        deadline: 16 * 60,
        priceMul: 1.2,
        minTrust: 0,
        text: "Phòng kế toán họp chiều: {qty} ly {dish} giao tới {place} trước {deadline}",
      },
      {
        id: "cho_tra_sua",
        poster: "Bà Năm chợ đầu mối",
        productId: "tra_sua",
        variantId: "hong_tra_sua",
        qty: [4, 6],
        lotId: "gan_cho",
        deadline: 12 * 60,
        priceMul: 1.2,
        minTrust: 0,
        text: "Mấy bà bạn hàng khát nước: {qty} ly {dish} ra {place} trước {deadline}",
      },
      {
        id: "sinh_nhat_phu_kien",
        poster: "Bé Su lớp 5",
        productId: "phu_kien",
        variantId: "kep_hong",
        qty: [4, 6],
        lotId: "cong_truong",
        deadline: 17 * 60,
        priceMul: 1.25,
        minTrust: 40,
        text: "Sinh nhật bạn thân: {qty} {dish} gói sẵn, đưa tới {place} trước {deadline}",
      },
    ],
  },

  staff: {
    shifts: [
      { id: "sang", name: "Ca sáng 6–11h", from: 6 * 60, to: 11 * 60 },
      { id: "trua", name: "Ca trưa 11–14h", from: 11 * 60, to: 14 * 60 },
      { id: "chieu", name: "Ca chiều 14–18h", from: 14 * 60, to: 18 * 60 },
      { id: "toi", name: "Ca tối 18–22h", from: 18 * 60, to: 22 * 60 },
      { id: "ca_ngay", name: "Cả ngày 6–22h", from: 6 * 60, to: 22 * 60 },
    ],
    people: [
      {
        id: "thu",
        name: "Thu",
        bio: "sinh viên năm hai, siêng, cẩn thận",
        model: "character-female-a",
        accuracy: 0.95,
        serveMinutes: 18,
        wagePerHour: 15_000,
      },
      {
        id: "khoa_phu",
        name: "Khoa",
        bio: "lanh tay mà hay quên lời khách dặn",
        model: "character-male-c",
        accuracy: 0.8,
        serveMinutes: 12,
        wagePerHour: 13_000,
      },
      {
        id: "di_sau",
        name: "Dì Sáu",
        bio: "chậm mà kỹ, khách lớn tuổi quý",
        model: "character-female-d",
        accuracy: 0.98,
        serveMinutes: 25,
        wagePerHour: 10_000,
      },
      {
        id: "chi_hoa",
        name: "Chị Hoa",
        bio: "từng bán ở chợ đêm, khéo ăn nói",
        model: "character-female-a",
        accuracy: 0.9,
        serveMinutes: 15,
        wagePerHour: 14_000,
      },
      {
        id: "tuan_anh",
        name: "Tuấn Anh",
        bio: "sinh viên làm thêm buổi tối, lanh lợi",
        model: "character-male-a",
        accuracy: 0.86,
        serveMinutes: 14,
        wagePerHour: 12_000,
      },
    ],
  },

  // Cấp tiệm (docs/IA.md bước E): nâng cấp → đông khách hơn + thuê thêm người. Xe đẩy chỉ cấp 1, cấp 2–3 cần nhà mặt tiền.
  // pnpm balance: ×1,3/×1,6 làm trà sữa tiệm lớn 3 NV lãi 1,36tr/ngày (8,5 lần làm thuê) → ×1,25/×1,45 (~1,18tr, trần tiệm lớn 8 lần).
  shopLevels: [
    { level: 1, name: "Quầy nhỏ", emoji: "🏪", trafficMul: 1, maxStaff: 1, upgradeCost: 0 },
    {
      level: 2,
      name: "Tiệm mở rộng",
      emoji: "🏬",
      trafficMul: 1.25,
      maxStaff: 2,
      upgradeCost: 1_500_000,
      houseOnly: true,
    },
    {
      level: 3,
      name: "Tiệm lớn",
      emoji: "🏢",
      trafficMul: 1.45,
      maxStaff: 3,
      upgradeCost: 3_500_000,
      houseOnly: true,
    },
  ],

  // Chuyện của tôi (docs/THEGIOI.md §1): mốc đời người chơi, server ghi một lần kèm ngày game.
  story: [
    { id: "join", emoji: "🧳", text: "Dọn về xóm với {money} trong túi" },
    { id: "first_cart", emoji: "🛒", text: "Mua {equipment} — bắt đầu đi buôn" },
    { id: "switch_trade", emoji: "🔄", text: "Đổi nghề: bán xe cũ, mua {equipment}" },
    { id: "first_open", emoji: "🎪", text: "Mở quầy {product} đầu tiên ở {lot}" },
    { id: "shop_level", emoji: "⬆️", text: "Nâng tiệm lên {name}" },
    { id: "more_shop", emoji: "🏪", text: "Mở thêm cửa hàng thứ {n}: {equipment}" },
    { id: "first_shop", emoji: "🏠", text: "Thuê nhà mặt tiền {lot}, mở tiệm đàng hoàng" },
    { id: "evicted", emoji: "📦", text: "Bị {landlord} dẹp tiệm ở {lot} vì nợ tiền nhà" },
    { id: "first_job", emoji: "💼", text: "Đi làm thuê lần đầu: {job}" },
    {
      id: "first_donate",
      emoji: "🏗️",
      text: "Lần đầu góp {money} vào quỹ xóm làm công trình chung",
    },
    { id: "first_regular", emoji: "❤️", text: "Có khách quen đầu tiên: {name} ({bio})" },
    { id: "first_hire", emoji: "👩‍🍳", text: "Thuê người đầu tiên: {name} đứng quầy phụ" },
    { id: "first_contract", emoji: "📋", text: "Xong việc đầu tiên trên bảng việc xóm: {text}" },
    { id: "first_license", emoji: "🏛️", text: 'Đăng ký hộ kinh doanh: quán "{name}" ra đời' },
    { id: "first_ride", emoji: "🛵", text: "Chạy cuốc xe ôm đầu tiên: chở {name} tới {place}" },
    { id: "first_gig", emoji: "📸", text: "Lần đầu chụp ảnh thuê: chụp quầy {shop} cho {name}" },
    {
      id: "first_gig_post",
      emoji: "📣",
      text: "Lần đầu thuê {name} chụp ảnh quầy — ảnh đăng lên nhóm xóm",
    },
    { id: "first_crew", emoji: "🏗️", text: "Lần đầu đi phụ hồ: trộn vữa cho {name}" },
  ],

  achievements: [
    {
      id: "mo_hang",
      emoji: "🥖",
      name: "Mở hàng",
      description: "Bán món đầu tiên",
      metric: "served",
      goal: 1,
      story: "Bán được món đầu tiên — tiền lẻ đầu tiên của nghề buôn",
      reward: { xp: 20, money: 10_000 },
    },
    {
      id: "khoi_nghiep",
      emoji: "🍜",
      name: "Khởi nghiệp",
      description: "Bán 100 món",
      metric: "served",
      goal: 100,
      story: "Quầy phục vụ đủ 100 khách",
      reward: { xp: 80, money: 30_000 },
    },
    {
      id: "tay_to",
      emoji: "🔥",
      name: "Tay to",
      description: "Bán 1.000 món",
      metric: "served",
      goal: 1000,
      story: "Quầy đạt 1.000 khách — cả xóm biết mặt",
      reward: { xp: 300, money: 100_000 },
    },
    {
      id: "trieu_dau",
      emoji: "💵",
      name: "Triệu đầu tiên",
      description: "Doanh thu cộng dồn 1.000.000đ",
      metric: "revenue",
      goal: 1_000_000,
      story: "Doanh thu cộng dồn chạm 1 triệu",
      reward: { xp: 60, money: 20_000 },
    },
    {
      id: "chuc_trieu",
      emoji: "💰",
      name: "Chục triệu",
      description: "Doanh thu cộng dồn 10.000.000đ",
      metric: "revenue",
      goal: 10_000_000,
      story: "Doanh thu cộng dồn chạm 10 triệu",
      reward: { xp: 250, money: 80_000 },
    },
    {
      id: "cham_chi",
      emoji: "💼",
      name: "Chăm chỉ",
      description: "Kiếm 300.000đ tiền công làm thuê",
      metric: "wages",
      goal: 300_000,
      story: "Kiếm đủ 300.000đ tiền công làm thuê",
      reward: { xp: 60, money: 20_000 },
    },
    {
      id: "nam_sao",
      emoji: "⭐",
      name: "Năm sao",
      description: "Nhận 10 đánh giá 5★",
      metric: "five_stars",
      goal: 10,
      story: "Nhận đánh giá 5★ thứ 10",
      reward: { xp: 100, money: 30_000 },
    },
    {
      id: "co_tam",
      emoji: "💬",
      name: "Chủ quầy có tâm",
      description: "Trả lời 10 đánh giá",
      metric: "replies",
      goal: 10,
      reward: { xp: 80, money: 20_000 },
    },
    {
      id: "rinh_rang",
      emoji: "🎉",
      name: "Rình rang",
      description: "Tổ chức khai trương lần đầu",
      metric: "events",
      goal: 1,
      reward: { xp: 40, money: 10_000 },
    },
    {
      id: "cap_5",
      emoji: "🌟",
      name: "Lên cấp 5",
      description: "Đạt cấp 5",
      metric: "level",
      goal: 5,
      reward: { xp: 0, money: 50_000 },
    },
    {
      id: "nguoi_quen",
      emoji: "🫶",
      name: "Người quen của xóm",
      description: "Thân với 3 người bán (thân thiết từ 30)",
      metric: "friends",
      goal: 3,
      reward: { xp: 50, money: 10_000 },
    },
  ],

  // Nhiệm vụ hằng ngày (góp ý đợt 2): làm thật mới đủ, thưởng nhỏ, mỗi ngày nhận một lần.
  dailyQuests: [
    {
      id: "ban_5",
      emoji: "🥖",
      text: "Bán 5 món",
      hint: "Mở quầy, làm đúng món, tính tiền",
      metric: "sold",
      goal: 5,
      reward: { xp: 15, money: 3_000 },
    },
    {
      id: "ban_20",
      emoji: "🔥",
      text: "Bán 20 món",
      metric: "sold",
      goal: 20,
      reward: { xp: 40, money: 5_000 },
    },
    {
      id: "lam_thue_50k",
      emoji: "💼",
      text: "Làm thuê kiếm 50.000đ",
      hint: "☰ Menu → 💼 Làm thuê",
      metric: "wages",
      goal: 50_000,
      reward: { xp: 15, money: 3_000 },
    },
    {
      id: "co_ban_choi",
      emoji: "👥",
      text: "Có hàng xóm cùng chơi",
      hint: "☰ Menu → 👥 Hàng xóm → 📨 Mời bạn",
      metric: "neighbors",
      goal: 2,
      reward: { xp: 20, money: 0 },
    },
  ],

  // Sổ đánh giá quầy (UC-F11): câu theo tình huống — giọng khách xóm + chút Gen Z.
  reviews: {
    chance: 0.3,
    lostChance: 0.35,
    replyRep: 0.01,
    maxText: 140,
    names: [
      "Linh",
      "Huy",
      "Trâm",
      "Khoa",
      "Ngọc",
      "Tú",
      "Bảo",
      "My",
      "Đạt",
      "Vy",
      "chú Tư",
      "cô Sáu",
    ],
    lines: {
      fast: [
        "Làm lẹ dữ, chưa kịp lướt xong cái story là có món 😳",
        "Nhanh gọn lẹ, 10 điểm không có nhưng",
        "Đứng chờ chưa tới một phút, mê!",
      ],
      ok: [
        "Ổn áp nha, mai ghé tiếp",
        "Ăn được, giá mềm, chủ quầy dễ thương",
        "Vừa miệng, không có gì để chê",
      ],
      slow: [
        "Chờ hơi lâu nha shop, sáng đi làm trễ luôn 🥲",
        "Ngon mà đợi mỏi chân quá trời",
        "Làm chậm rì, lần sau đặt trước chắc ổn hơn",
      ],
      wrong: [
        "Dặn không hành mà vẫn có hành, buồn ghê 😤",
        "Kêu một đằng làm một nẻo, xỉu",
        "Sai món mà được giảm giá nên thôi bỏ qua",
      ],
      pricey: [
        "Hơi chát so với mặt bằng xóm á",
        "Giá này ở chợ mua được hai cái rồi 💸",
        "Ngon nhưng ví mình khóc nhẹ",
      ],
      cheap: [
        "Rẻ mà chất lượng, kèo thơm 🔥",
        "Giá học sinh, ủng hộ dài dài",
        "Rẻ bất ngờ, ăn xong còn tiền mua trà đá",
      ],
      short: [
        "Thối thiếu tiền nha, phải đòi mới đưa đủ 😒",
        "Tính tiền ẩu quá, check lại giùm cái",
      ],
      lost: [
        "Đứng chờ mòn mỏi không ai làm, thôi đi quán khác",
        "Hàng đông mà một mình làm, bỏ cuộc 🫠",
        "Đợi hoài không tới lượt, bye",
      ],
      vip_good: [
        "Chuẩn vị, làm kỹ, sẽ giới thiệu bạn bè 👍",
        "Quầy nhỏ mà làm có tâm, recommend nha",
      ],
      vip_bad: ["Kỳ vọng nhiều mà hơi thất vọng", "Chưa tới, còn phải luyện thêm"],
    },
    quickReplies: {
      good: ["Cảm ơn bạn nhiều nha! 🥰", "Mai ghé tiếp nha, có món mới đó!"],
      bad: ["Xin lỗi bạn, lần sau mình làm kỹ hơn ạ 🙏", "Cảm ơn góp ý, mình sửa liền nha!"],
    },
    banned: ["đm", "dm", "đmm", "vcl", "vl", "đéo", "địt", "lồn", "cặc", "đĩ"],
  },

  // Giọng thoại theo kiểu khách (#12, USECASES UC-D6). Câu "mặn" nhẹ thôi — người chơi tắt được trong Cài đặt.
  voice: {
    voices: [
      {
        archetype: "hoc_sinh",
        ask: [
          "Shop ơi cho em {dish} nha 🥺",
          "Cho e {dish} vớiii, nhanh nhanh e trễ học r",
          "Chị ơi {dish} một cái nha, hôm nay đói xỉu ngang",
          "1 {dish} nha shop, ko lấy bịch đâu ạ",
        ],
        cheap: [
          "Rẻ vãi, mai em rủ cả lớp ra 🤩",
          "Giá học sinh luôn, iu shop",
          "U là trời rẻ dữ dzậy",
        ],
        pricey: [
          "Hơi chát á shop, tiền tiêu vặt e có nhiêu đâu 🥲",
          "Mắc dữ, tuần này nhịn trà sữa luôn",
          "Ủa sao mắc z trời",
        ],
        thanks: [
          "Ngon xỉu, 10 điểm ko có nhưng 💯",
          "Iu shop, mai ghé tiếp nha",
          "Đỉnh của chóp luôn á",
          "Tks shop nhaaa",
        ],
        impatient: [
          "Trễ học r, thôi em đi đây 😭",
          "Lâu vãi, thôi khum chờ nữa",
          "Chờ mòn mỏi luôn á, bye",
        ],
      },
      {
        archetype: "dan_van_phong",
        ask: [
          "Cho anh {dish}, nhanh giúp anh nha, 8h chấm công rồi",
          "Em ơi {dish} nha, chuyển khoản được không?",
          "Một {dish}, anh lấy mang đi",
          "Cho chị {dish} nha, deadline dí quá chưa kịp ăn",
        ],
        cheap: ["Giá này hợp lý ghê, mai anh dẫn team ra", "Rẻ mà chất lượng, recommend"],
        pricey: [
          "Giá hơi cao so với mặt bằng chung á em",
          "Ngang giá quán máy lạnh luôn rồi đó",
          "Lương chưa về mà giá này hơi căng",
        ],
        thanks: [
          "Ok em, chuyển rồi nha",
          "Ngon, cứu đói buổi sáng",
          "Nhanh gọn, 5 sao",
          "Ổn áp, mai ghé",
        ],
        impatient: [
          "Trễ giờ rồi, thôi anh đi",
          "Sếp gọi rồi, để bữa khác nha",
          "Đợi lâu quá, chịu không nổi",
        ],
      },
      {
        archetype: "co_chu",
        ask: [
          "Bán cho cô {dish} nghen con",
          "Con ơi lấy chú {dish}, đừng có cay nha",
          "Cho cô {dish}, gói kỹ kỹ cô mang về cho thằng cháu",
          "Con bé ơi, {dish} một phần coi",
        ],
        cheap: ["Rẻ vậy con, để cô giới thiệu mấy bà trong xóm", "Giá vậy là có lương tâm nè"],
        pricey: [
          "Hồi xưa có mấy ngàn hà, giờ mắc quá con ơi",
          "Mắc dữ vậy con, bớt cho cô chút coi",
          "Giá này chợ bán rẻ hơn á nghen",
        ],
        thanks: [
          "Cảm ơn con nghen, con làm khéo ghê",
          "Được đó con, mai cô ghé",
          "Ngon, giữ tiền lẻ luôn con",
        ],
        impatient: [
          "Thôi cô đi chợ đã, lát ghé",
          "Đợi lâu quá con, cô về nấu cơm đây",
          "Thôi để bữa khác nghen",
        ],
      },
      {
        archetype: "khach_vang_lai",
        ask: [
          "Cho mình {dish} nhé",
          "{dish} một phần, bạn ơi",
          "Ở đây có {dish} không bạn? Cho mình một cái",
        ],
        pricey: ["Hơi mắc nha bạn", "Giá này hơi chát á", "Chà, giá du lịch ha"],
        thanks: ["Cảm ơn bạn nha!", "Ok, ngon đó", "Lẹ ghê, cảm ơn nhé"],
        impatient: ["Thôi mình đi, gấp quá", "Lâu quá bạn ơi", "Đợi hoài, thôi đi tiếp"],
      },
      {
        archetype: "reviewer",
        ask: [
          "Cho mình {dish}, mình quay clip review xíu được hông? 📸",
          "Hello shop, {dish} nha, nghe bảo hot lắm",
        ],
        cheap: [
          "Giá này mà chất lượng vậy là deal hời đó mọi người 🔥",
          "Rẻ mà ngon, quẹo lựa nha",
        ],
        pricey: ["Hơi đắt so với chất lượng nha, 6/10", "Mức giá này thì cần cải thiện thêm"],
        thanks: [
          "Ngon nha, chấm 8.5/10, sẽ quay lại",
          "Okela, lên clip liền",
          "Chất lượng ổn, phục vụ nhanh, ủng hộ!",
        ],
        impatient: [
          "Chờ lâu quá, cái này phải ghi vào review rồi",
          "Hơi lâu nha shop, trừ điểm phục vụ",
        ],
      },
    ],
    soften: {
      vãi: "quá",
      "xỉu ngang": "lắm luôn",
      "đỉnh của chóp": "tuyệt",
      "u là trời": "trời ơi",
      "chịu không nổi": "hết chờ nổi",
    },
  },

  customerLines: {
    cheap: ["Rẻ vậy! Mai ghé nữa nha", "Giá này hời quá", "Cho thêm ổ nữa được hông?"],
    fair: ["Cho một phần nha", "Bán cho con với", "Như mọi khi nha"],
    pricey: ["Hơi mắc ha…", "Giá này hơi chát", "Bữa sau bớt chút nha"],
    thanks: ["Cảm ơn nha!", "Lẹ ghê, gửi tiền nè", "Ngon! Giữ tiền thối luôn"],
    impatient: ["Lâu quá, thôi đi…", "Đợi hoài…", "Thôi để bữa khác"],
  },

  economy: {
    startingMoney: START_CASH,
    // Góp ý chơi thử: mua xe xong còn ~300k, khó sống → mở sẵn tài khoản có 1tr dự phòng.
    startingBank: START_BANK,
    dayStartMinute: 6 * 60,
    dayEndMinute: 22 * 60,
    economyTickMinutes: 5,
    marketPriceSwing: 0.1,
    outsideOption: 1,
    // Nhịp chơi (góp ý chơi thử: khách thưa, đứng chờ lâu): quầy đông gấp đôi lưu lượng "thật".
    demandScale: 1.6,
    reputationRate: 0.08,
    startingReputation: 0.5,
    afternoonMarkup: 0.2,
    shoutBoost: 1.25,
    shoutMinutes: 60,
    shoutCooldownMinutes: 30,
    bulkPacks: 5,
    // Chuyển kho giữa các cửa hàng của mình: bấm chuyển, chở tới sau 30 phút game (đang chở thì chưa bán được).
    transferMinutes: 30,
    xomResidents: 40,
    xomOnline: 30,
    bulkDiscount: 0.05,
    resaleRate: 0.4,
    friendDiscountAt: 30,
    friendDiscount: 0.05,
    tipRate: 0.08,
    // Phí chợ/thuế khoán: xe đẩy 5k/ngày, tiệm 15k/ngày; tiệm còn trả điện nước 3k mỗi giờ mở cửa.
    fees: { daily: { cart: 5_000, house: 15_000 }, utilitiesPerHour: 3_000 },
    // Mòn ~0,6% mỗi món: bán ~80 món là xe ọp ẹp (khách bớt 15%, giữ nút lâu hơn 60%); 100% thì phải sửa mới mở được.
    // Sửa hết mòn tốn 12% giá xe (xe bánh mì 1,2tr → ~144k, như thay bánh xe + kính + sơn ở tiệm sửa xe).
    maintenance: {
      wearPerServe: 0.006,
      slowAt: 0.5,
      slowDemand: 0.85,
      slowHold: 1.6,
      repairRate: 0.12,
    },
    // Lãi 0,2%/ngày cho số dư từ 100k, tối đa 3.000đ/ngày — có cũng vui, không sống bằng lãi được (Luật 2.3).
    bank: {
      interestRate: 0.002,
      interestCap: 3_000,
      interestMin: 100_000,
      withdrawStep: 10_000,
      depositStep: 10_000,
      // Mua lặt vặt (dưới 200k) thì móc tiền mặt; mua xe, trả tiền nhà thì quét mã chuyển khoản.
      cashFirstBelow: 200_000,
      // Rút ATM mất phí như ngoài đời; sai PIN 3 lần máy nuốt thẻ (UC-I6).
      withdrawFee: 1_000,
      pinTries: 3,
    },
    serveReputationBonus: 0.01,
    interactRadius: 2.5,
  },

  // Kỹ năng (DESIGN §4): làm thật mới lên — bán kịp, làm đúng lời dặn, chào hỏi/khách vui.
  skills: [
    {
      id: "tay_nhanh",
      name: "Tay nhanh",
      emoji: "⚡",
      description: "Phục vụ kịp giờ thì lên. Mỗi bậc: giữ nút (lắc, giữ…) nhanh hơn 8%.",
      per: 15,
      max: 5,
      effect: 0.08,
    },
    {
      id: "nho_mon",
      name: "Nhớ món",
      emoji: "🧠",
      description:
        "Làm đúng món có lời dặn thì lên. Từ bậc 1: màn làm món nhắc lại lời dặn của khách.",
      per: 10,
      max: 5,
      effect: 1,
    },
    {
      id: "an_noi",
      name: "Ăn nói",
      emoji: "💬",
      description: "Chào hỏi, khách vui vẻ ra về thì lên. Mỗi bậc: khách kiên nhẫn thêm 5%.",
      per: 12,
      max: 5,
      effect: 0.05,
    },
  ],
  // Mở khoá theo cấp (Luật 4.2): làm thật mới mở — không mua bằng tiền thật.
  unlocks: [{ id: "event_host", level: 2, label: "Tổ chức khai trương" }],

  // Xóm quê (góp ý chủ dự án 10/2026): ít nhà cao tầng; nhà dân phần lớn là nhà cấp 4 mái ngói, vài nhà tranh,
  // lác đác nhà ống — sau này người chơi mua/xây nhà thì nâng cấp dần lên (DESIGN §5).
  housing: {
    tiers: [
      { id: "nha_tranh", name: "Nhà tranh vách tre", models: ["nha-tranh"], start: 0.25 },
      { id: "cap4", name: "Nhà cấp 4 mái ngói", models: ["nha-cap4", "nha-cap4-xanh"], start: 0.6 },
      { id: "ong1", name: "Nhà ống 1 lầu", models: ["nha-ong-1-lau"], start: 0.15 },
      { id: "ong2", name: "Nhà ống 2 lầu", models: ["nha-ong-2-lau"], start: 0 },
    ],
    shops: ["tiem-tap-hoa", "tiem-tap-hoa-trang", "nha-cap4", "nha-ong-1-lau"],
    office: "uy-ban",
    school: "truong-lang",
  },

  // Sự kiện (docs/USECASES.md UC-B5, nhóm K; DESIGN §9): người chơi tạo (khai trương), cá nhân (khách VIP), toàn xóm (mưa lớn).
  events: [
    {
      id: "khai_truong",
      name: "Khai trương",
      emoji: "🎉",
      scope: "player",
      minutes: 180,
      trigger: {
        kind: "player",
        cooldownDays: 3,
        costs: [
          { id: "phao_giay", label: "Pháo giấy", emoji: "🎊", price: 40_000 },
          { id: "bong_bong", label: "Chùm bong bóng", emoji: "🎈", price: 25_000 },
          { id: "bang_ron", label: "Băng rôn", emoji: "🪧", price: 35_000 },
        ],
      },
      effects: { demand: 1.8, discount: 0.1 },
      news: "🎉 {name} khai trương {shop} — giảm 10%, ghé ủng hộ nha!",
    },
    {
      id: "khach_vip",
      name: "Khách VIP",
      emoji: "🕴️",
      scope: "personal",
      minutes: 1,
      trigger: { kind: "per_hour", perHour: 0.35 },
      effects: {
        vip: { minMods: 2, patience: 0.8, tipMult: 5, repWin: 0.04, repLose: 0.05 },
      },
      news: "🕴️ Có khách sộp ghé {shop} — dặn kỹ lắm, làm chuẩn là được boa đậm",
    },
    {
      // Chợ đêm thứ Bảy (THEGIOI §2): cả xóm ra đường, quầy ăn vặt / đồ uống / phụ kiện đông hẳn.
      id: "cho_dem",
      name: "Chợ đêm thứ Bảy",
      emoji: "🏮",
      scope: "neighborhood",
      minutes: 240,
      trigger: { kind: "weekly", weekdays: [5], from: 18 * 60 },
      effects: { categoryDemand: { breakfast: 1.4, drink: 1.7, accessory: 1.8 } },
      news: "🏮 Tối nay chợ đêm thứ Bảy — 18:00 tới 22:00, bày hàng ra là đông!",
    },
    {
      id: "mua_lon",
      name: "Mưa lớn toàn xóm",
      emoji: "⛈️",
      scope: "server",
      minutes: 90,
      trigger: { kind: "daily", chance: 0.15, from: 13 * 60, to: 19 * 60 },
      effects: { weather: "storm" },
      news: "⛈️ Đài báo chiều nay mưa lớn toàn xóm — lo dọn hàng vô trong",
    },
  ],

  // Thời tiết (docs/USECASES.md UC-B4, DESIGN §8): trời đổi theo khối 2 giờ, chiều hay mưa (kiểu Sài Gòn mùa mưa).
  // Mưa/bão: khách ngoài vỉa hè thưa hẳn, tiệm có mái đông hơn; nắng gắt: đồ uống lạnh bán chạy.
  weather: {
    blockMinutes: 120,
    persist: 0.5,
    forecastMinutes: 90,
    weights: {
      sunny: { "6": 4, "10": 6, "13": 5, "16": 3, "19": 2, "21": 2 },
      cloudy: { "6": 3, "12": 2, "16": 3, "21": 3 },
      rain: { "6": 1, "11": 1, "14": 3, "17": 3, "20": 1 },
      storm: { "6": 0, "12": 0.2, "16": 0.6, "19": 0.2, "21": 0 },
    },
    kinds: [
      {
        id: "sunny",
        name: "Nắng",
        emoji: "☀️",
        outdoor: 1,
        indoor: 1,
        category: { drink: 1.2 },
        delivery: { speed: 1, surcharge: 0, damage: 1 },
        dim: 0,
        rain: 0,
        news: "☀️ Trời nắng gắt — nước mát, trà sữa bán chạy",
        forecast: "☀️ Khoảng {time} trời hửng nắng lại",
      },
      {
        id: "cloudy",
        name: "Âm u",
        emoji: "☁️",
        outdoor: 0.9,
        indoor: 1,
        category: {},
        delivery: { speed: 1, surcharge: 0, damage: 1 },
        dim: 0.18,
        rain: 0,
        news: "☁️ Trời âm u, người ta ít ra đường hơn",
        forecast: "☁️ Khoảng {time} trời kéo mây âm u",
      },
      {
        id: "rain",
        name: "Mưa",
        emoji: "🌧️",
        outdoor: 0.5,
        indoor: 1.15,
        category: { drink: 0.8, breakfast: 1.15 },
        delivery: { speed: 0.8, surcharge: 0.2, damage: 1.6 },
        dim: 0.35,
        rain: 0.55,
        news: "🌧️ Trời đổ mưa — xe đẩy vắng khách, tiệm có mái đông lên",
        forecast: "🌧️ Khoảng {time} có mưa — chuẩn bị dời vô chỗ có mái",
      },
      {
        id: "storm",
        name: "Bão",
        emoji: "⛈️",
        outdoor: 0.2,
        indoor: 1,
        category: { drink: 0.6, breakfast: 1.2 },
        delivery: { speed: 0.6, surcharge: 0.5, damage: 2.5 },
        dim: 0.55,
        rain: 1,
        news: "⛈️ Mưa bão! Ngoài đường gần như không ai, giao hàng có phụ phí bão",
        forecast: "⛈️ Khoảng {time} có giông bão — dọn hàng vô trong cho kịp",
      },
    ],
  },
};
