import type { ContentInput } from "./schema.js";

// Dữ liệu MVP: 1 xóm, 3 business (bánh mì, trà sữa, phụ kiện), 2 template (docs/PLAN.md §3.1).
// Mọi con số ở đây là điểm khởi đầu để cân bằng bằng tools/balance.

export const data: ContentInput = {
  templates: [
    { id: "FOOD", name: "Đồ ăn · thức uống" },
    { id: "RETAIL", name: "Bán lẻ" },
  ],

  // Mỗi nghề có công thức làm món từng bước (docs/USECASES.md UC-F4…F6).
  products: [
    {
      id: "banh_mi",
      template: "FOOD",
      category: "breakfast",
      name: "Bánh mì",
      emoji: "🥖",
      sign: "BÁNH MÌ",
      signColor: "#e4432d",
      elasticity: 3,
      interestByHour: {
        "6": 0.13,
        "7": 0.156,
        "8": 0.104,
        "10": 0.039,
        "11": 0.065,
        "13": 0.0325,
        "16": 0.039,
        "18": 0.052,
        "21": 0.0195,
      },
      recipe: {
        ask: "Cho con ổ {dish} nha!",
        steps: [
          {
            id: "banh",
            label: "Lấy bánh",
            kind: "single",
            weight: 1,
            options: [
              { id: "banh_mi_phoi", label: "Ổ bánh mì", emoji: "🥖", ingredient: "banh_mi_phoi" },
            ],
          },
          { id: "xe", label: "Xẻ bánh", kind: "action", verb: "🔪 Xẻ bánh" },
          {
            id: "phet",
            label: "Phết",
            kind: "multi",
            options: [
              { id: "pate", label: "Pa-tê", emoji: "🟤", ingredient: "pate" },
              { id: "bo", label: "Bơ", emoji: "🧈", ingredient: "bo", extraPrice: 2_000 },
            ],
          },
          {
            id: "nhan",
            label: "Nhân",
            kind: "single",
            weight: 3,
            options: [
              { id: "thit_nguoi", label: "Thịt nguội", emoji: "🥓", ingredient: "thit_nguoi" },
              { id: "xiu_mai", label: "Xíu mại", emoji: "🧆", ingredient: "xiu_mai" },
              { id: "trung", label: "Trứng ốp la", emoji: "🍳", ingredient: "trung" },
            ],
          },
          {
            id: "rau",
            label: "Rau",
            kind: "multi",
            options: [
              { id: "dua_leo", label: "Dưa leo", emoji: "🥒", ingredient: "dua_leo" },
              { id: "do_chua", label: "Đồ chua", emoji: "🥕", ingredient: "do_chua" },
              { id: "hanh", label: "Hành lá", emoji: "🌱", ingredient: "hanh" },
              { id: "ngo", label: "Ngò", emoji: "🌿", ingredient: "ngo" },
            ],
          },
          {
            id: "ot",
            label: "Ớt",
            kind: "single",
            options: [
              { id: "ot_khong", label: "Không ớt", emoji: "🚫" },
              { id: "ot_vua", label: "Vừa", emoji: "🌶️", ingredient: "ot" },
              { id: "ot_nhieu", label: "Nhiều", emoji: "🔥", ingredient: "ot", qty: 2 },
            ],
          },
          {
            id: "sot",
            label: "Nước sốt",
            kind: "multi",
            options: [{ id: "sot", label: "Nước sốt", emoji: "🥫", ingredient: "sot" }],
          },
          {
            id: "goi",
            label: "Gói giấy",
            kind: "action",
            verb: "📄 Gói giấy",
            ingredient: "giay_goi",
          },
        ],
        defaults: {
          banh: "banh_mi_phoi",
          phet: ["pate"],
          rau: ["dua_leo", "do_chua", "hanh", "ngo"],
          ot: "ot_vua",
          sot: ["sot"],
        },
        variants: [
          {
            id: "banh_mi_thit",
            name: "bánh mì thịt",
            fixed: { nhan: "thit_nguoi" },
            refPrice: 16_000,
            popularity: 3,
          },
          {
            id: "banh_mi_xiu_mai",
            name: "bánh mì xíu mại",
            fixed: { nhan: "xiu_mai" },
            refPrice: 18_000,
            popularity: 2,
          },
          {
            id: "banh_mi_trung",
            name: "bánh mì trứng",
            fixed: { nhan: "trung" },
            refPrice: 14_000,
            popularity: 2,
          },
        ],
        mods: [
          { id: "khong_hanh", step: "rau", remove: "hanh", say: "không hành", chance: 0.3 },
          { id: "khong_ngo", step: "rau", remove: "ngo", say: "không ngò", chance: 0.15 },
          { id: "khong_dua", step: "rau", remove: "dua_leo", say: "không dưa leo", chance: 0.1 },
          { id: "khong_pate", step: "phet", remove: "pate", say: "không pa-tê", chance: 0.1 },
          { id: "them_bo", step: "phet", add: "bo", say: "thêm bơ", chance: 0.12 },
          { id: "ot_nhieu", step: "ot", set: "ot_nhieu", say: "nhiều ớt", chance: 0.2 },
          { id: "ot_khong", step: "ot", set: "ot_khong", say: "không ớt", chance: 0.15 },
        ],
      },
    },
    {
      id: "tra_sua",
      // Quầy trà theo góc nhìn người bán (ảnh tham khảo của chủ dự án): ly M/L · bình trà có vòi · máy dán miệng ly ·
      // ô pha ly + dải đường/đá · lưới khay topping 4×3 · giữ để lắc.
      counter: {
        title: "QUẦY TRÀ",
        zones: [
          { zone: "cups", step: "ly" },
          { zone: "jars", step: "tra" },
          { zone: "sealer", step: "nap" },
          { zone: "chips", step: "duong" },
          { zone: "chips", step: "da" },
          { zone: "grid", step: "topping", slots: 12 },
          { zone: "shaker", step: "lac" },
        ],
      },
      template: "FOOD",
      category: "drink",
      name: "Trà sữa",
      emoji: "🧋",
      sign: "TRÀ SỮA",
      signColor: "#2f7d4f",
      elasticity: 2.6,
      interestByHour: {
        "6": 0.0033,
        "9": 0.013,
        "11": 0.0228,
        "14": 0.039,
        "16": 0.052,
        "19": 0.0455,
        "21": 0.026,
      },
      recipe: {
        ask: "Cho em một ly {dish} nha!",
        steps: [
          {
            id: "ly",
            label: "Chọn ly",
            kind: "single",
            options: [
              { id: "ly_m", label: "Size M", emoji: "🥤", ingredient: "ly_m" },
              {
                id: "ly_l",
                label: "Size L",
                emoji: "🥤",
                ingredient: "ly_l",
                extraPrice: 5_000,
                say: "size L",
              },
            ],
            pick: { ly_m: 0.65, ly_l: 0.35 },
          },
          {
            id: "tra",
            label: "Trà nền",
            kind: "single",
            weight: 3,
            options: [
              { id: "cot_tra_sua", label: "Trà sữa", emoji: "🍵", ingredient: "cot_tra_sua" },
              { id: "cot_tra_xanh", label: "Trà xanh", emoji: "🍃", ingredient: "cot_tra_xanh" },
              { id: "cot_hong_tra", label: "Hồng trà", emoji: "🍂", ingredient: "cot_hong_tra" },
            ],
          },
          {
            id: "duong",
            label: "Đường",
            kind: "single",
            options: [
              // Nhãn theo cách khách nói (góp ý chơi thử: chỉ ghi % thì khó biết nhiều hay ít).
              { id: "duong_0", label: "Không đường · 0%", emoji: "⚪", say: "không đường" },
              { id: "duong_30", label: "Ít đường · 30%", emoji: "🍬", say: "ít đường" },
              { id: "duong_50", label: "Nửa đường · 50%", emoji: "🍬", say: "nửa đường" },
              { id: "duong_70", label: "Bình thường · 70%", emoji: "🍬" },
              { id: "duong_100", label: "Ngọt nhiều · 100%", emoji: "🍯", say: "nhiều đường" },
            ],
            pick: { duong_0: 0.08, duong_30: 0.17, duong_50: 0.2, duong_70: 0.4, duong_100: 0.15 },
          },
          {
            id: "da",
            label: "Đá",
            kind: "single",
            options: [
              { id: "da_khong", label: "Không đá", emoji: "🚫", say: "không đá" },
              { id: "da_it", label: "Ít đá", emoji: "🧊", ingredient: "da", say: "ít đá" },
              { id: "da_bt", label: "Bình thường", emoji: "🧊", ingredient: "da", qty: 2 },
            ],
            pick: { da_khong: 0.1, da_it: 0.3, da_bt: 0.6 },
          },
          {
            id: "topping",
            label: "Topping",
            kind: "multi",
            weight: 2,
            options: [
              { id: "tc_den", label: "Trân châu đen", emoji: "⚫", ingredient: "tran_chau_den" },
              {
                id: "tc_trang",
                label: "Trân châu trắng",
                emoji: "⚪",
                ingredient: "tran_chau_trang",
                extraPrice: 5_000,
              },
              {
                id: "thach",
                label: "Thạch trái cây",
                emoji: "🟩",
                ingredient: "thach",
                extraPrice: 5_000,
              },
              {
                id: "pudding",
                label: "Pudding",
                emoji: "🍮",
                ingredient: "pudding",
                extraPrice: 5_000,
              },
            ],
          },
          { id: "lac", label: "Lắc đều", kind: "hold", verb: "🫨 Giữ để lắc" },
          {
            id: "nap",
            label: "Dán nắp",
            kind: "action",
            verb: "🔘 Dán nắp",
            ingredient: "mang_nap",
          },
        ],
        defaults: { ly: "ly_m", duong: "duong_70", da: "da_bt", topping: ["tc_den"] },
        variants: [
          {
            id: "tra_sua_truyen_thong",
            name: "trà sữa truyền thống",
            fixed: { tra: "cot_tra_sua" },
            refPrice: 25_000,
            popularity: 3,
          },
          {
            id: "tra_xanh_sua",
            name: "trà xanh sữa",
            fixed: { tra: "cot_tra_xanh" },
            refPrice: 25_000,
            popularity: 1.5,
          },
          {
            id: "hong_tra_sua",
            name: "hồng trà sữa",
            fixed: { tra: "cot_hong_tra" },
            refPrice: 27_000,
            popularity: 1.5,
          },
        ],
        mods: [
          {
            id: "them_tc_trang",
            step: "topping",
            add: "tc_trang",
            say: "thêm trân châu trắng",
            chance: 0.18,
          },
          { id: "them_thach", step: "topping", add: "thach", say: "thêm thạch", chance: 0.15 },
          { id: "them_pudding", step: "topping", add: "pudding", say: "thêm pudding", chance: 0.2 },
          {
            id: "khong_tc_den",
            step: "topping",
            remove: "tc_den",
            say: "không trân châu đen",
            chance: 0.08,
          },
        ],
      },
    },
    {
      id: "phu_kien",
      template: "RETAIL",
      category: "accessory",
      name: "Phụ kiện",
      emoji: "🎀",
      sign: "PHỤ KIỆN",
      signColor: "#c2185b",
      elasticity: 2.4,
      interestByHour: {
        "6": 0.00192,
        "9": 0.0078,
        "12": 0.01164,
        "16": 0.01956,
        "19": 0.02736,
        "21": 0.01956,
      },
      recipe: {
        ask: "Có {dish} hông?",
        steps: [
          {
            id: "chon",
            label: "Tìm món",
            kind: "single",
            weight: 3,
            options: [
              { id: "kep_hong", label: "Kẹp tóc hồng", emoji: "🎀", ingredient: "kep_hong" },
              { id: "kep_xanh", label: "Kẹp tóc xanh", emoji: "💠", ingredient: "kep_xanh" },
              { id: "moc_meo", label: "Móc khóa mèo", emoji: "🐱", ingredient: "moc_meo" },
              { id: "moc_cun", label: "Móc khóa cún", emoji: "🐶", ingredient: "moc_cun" },
              { id: "day_buoc", label: "Dây buộc tóc", emoji: "🧶", ingredient: "day_buoc" },
            ],
          },
          {
            id: "goi",
            label: "Gói quà",
            kind: "single",
            options: [
              { id: "goi_khong", label: "Không gói", emoji: "🛍️" },
              {
                id: "goi_qua",
                label: "Gói quà",
                emoji: "🎁",
                ingredient: "giay_qua",
                say: "gói quà giùm",
              },
            ],
            pick: { goi_khong: 0.7, goi_qua: 0.3 },
          },
        ],
        defaults: { goi: "goi_khong" },
        variants: [
          {
            id: "kep_hong",
            name: "kẹp tóc hồng",
            fixed: { chon: "kep_hong" },
            refPrice: 30_000,
            popularity: 2,
          },
          {
            id: "kep_xanh",
            name: "kẹp tóc xanh",
            fixed: { chon: "kep_xanh" },
            refPrice: 30_000,
            popularity: 1.5,
          },
          {
            id: "moc_meo",
            name: "móc khóa mèo",
            fixed: { chon: "moc_meo" },
            refPrice: 35_000,
            popularity: 2,
          },
          {
            id: "moc_cun",
            name: "móc khóa cún",
            fixed: { chon: "moc_cun" },
            refPrice: 35_000,
            popularity: 1.5,
          },
          {
            id: "day_buoc",
            name: "dây buộc tóc",
            fixed: { chon: "day_buoc" },
            refPrice: 20_000,
            popularity: 1.5,
          },
        ],
      },
    },
  ],

  // Nguyên liệu / hàng nhập ở chợ Bà Năm (giá gốc mỗi phần; mua theo gói).
  ingredients: [
    {
      id: "banh_mi_phoi",
      name: "Bánh mì phôi",
      emoji: "🥖",
      unit: "ổ",
      packSize: 10,
      costPerUnit: 2_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "pate",
      name: "Pa-tê",
      emoji: "🟤",
      unit: "phần",
      packSize: 20,
      costPerUnit: 1_000,
      shelfLifeDays: 3,
    },
    {
      id: "bo",
      name: "Bơ",
      emoji: "🧈",
      unit: "phần",
      packSize: 20,
      costPerUnit: 800,
      shelfLifeDays: 3,
    },
    {
      id: "thit_nguoi",
      name: "Thịt nguội",
      emoji: "🥓",
      unit: "phần",
      packSize: 10,
      costPerUnit: 3_500,
      shelfLifeDays: 2,
    },
    {
      id: "xiu_mai",
      name: "Xíu mại",
      emoji: "🧆",
      unit: "phần",
      packSize: 10,
      costPerUnit: 4_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "trung",
      name: "Trứng gà",
      emoji: "🥚",
      unit: "quả",
      packSize: 10,
      costPerUnit: 3_000,
      shelfLifeDays: 5,
    },
    {
      id: "dua_leo",
      name: "Dưa leo",
      emoji: "🥒",
      unit: "phần",
      packSize: 20,
      costPerUnit: 300,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "do_chua",
      name: "Đồ chua",
      emoji: "🥕",
      unit: "phần",
      packSize: 20,
      costPerUnit: 300,
      shelfLifeDays: 3,
    },
    {
      id: "hanh",
      name: "Hành lá",
      emoji: "🌱",
      unit: "nhúm",
      packSize: 30,
      costPerUnit: 100,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "ngo",
      name: "Ngò",
      emoji: "🌿",
      unit: "nhúm",
      packSize: 30,
      costPerUnit: 100,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "ot",
      name: "Ớt",
      emoji: "🌶️",
      unit: "phần",
      packSize: 30,
      costPerUnit: 100,
      shelfLifeDays: 3,
    },
    {
      id: "sot",
      name: "Nước sốt",
      emoji: "🥫",
      unit: "phần",
      packSize: 30,
      costPerUnit: 200,
      shelfLifeDays: null,
    },
    {
      id: "giay_goi",
      name: "Giấy gói",
      emoji: "📄",
      unit: "tờ",
      packSize: 50,
      costPerUnit: 200,
      shelfLifeDays: null,
    },
    {
      id: "ly_m",
      name: "Ly nhựa size M",
      emoji: "🥤",
      unit: "ly",
      packSize: 50,
      costPerUnit: 800,
      shelfLifeDays: null,
    },
    {
      id: "ly_l",
      name: "Ly nhựa size L",
      emoji: "🥤",
      unit: "ly",
      packSize: 50,
      costPerUnit: 1_000,
      shelfLifeDays: null,
    },
    {
      id: "cot_tra_sua",
      name: "Cốt trà sữa",
      emoji: "🍵",
      unit: "phần",
      packSize: 10,
      costPerUnit: 7_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "cot_tra_xanh",
      name: "Cốt trà xanh",
      emoji: "🍃",
      unit: "phần",
      packSize: 10,
      costPerUnit: 7_000,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "cot_hong_tra",
      name: "Cốt hồng trà",
      emoji: "🍂",
      unit: "phần",
      packSize: 10,
      costPerUnit: 7_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "da",
      name: "Đá viên",
      emoji: "🧊",
      unit: "phần",
      packSize: 40,
      costPerUnit: 300,
      shelfLifeDays: 1,
    },
    {
      id: "tran_chau_den",
      name: "Trân châu đen",
      emoji: "⚫",
      unit: "phần",
      packSize: 20,
      costPerUnit: 1_500,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "tran_chau_trang",
      name: "Trân châu trắng",
      emoji: "⚪",
      unit: "phần",
      packSize: 20,
      costPerUnit: 1_800,
      shelfLifeDays: 1,
      fresh: true,
    },
    {
      id: "thach",
      name: "Thạch trái cây",
      emoji: "🟩",
      unit: "phần",
      packSize: 20,
      costPerUnit: 1_200,
      shelfLifeDays: 3,
    },
    {
      id: "pudding",
      name: "Pudding trứng",
      emoji: "🍮",
      unit: "phần",
      packSize: 20,
      costPerUnit: 2_000,
      shelfLifeDays: 2,
    },
    {
      id: "mang_nap",
      name: "Màng dán nắp",
      emoji: "🔘",
      unit: "tấm",
      packSize: 100,
      costPerUnit: 100,
      shelfLifeDays: null,
    },
    {
      id: "kep_hong",
      name: "Kẹp tóc hồng",
      emoji: "🎀",
      unit: "cái",
      packSize: 5,
      costPerUnit: 9_000,
      shelfLifeDays: null,
    },
    {
      id: "kep_xanh",
      name: "Kẹp tóc xanh",
      emoji: "💠",
      unit: "cái",
      packSize: 5,
      costPerUnit: 9_000,
      shelfLifeDays: null,
    },
    {
      id: "moc_meo",
      name: "Móc khóa mèo",
      emoji: "🐱",
      unit: "cái",
      packSize: 5,
      costPerUnit: 11_000,
      shelfLifeDays: null,
    },
    {
      id: "moc_cun",
      name: "Móc khóa cún",
      emoji: "🐶",
      unit: "cái",
      packSize: 5,
      costPerUnit: 11_000,
      shelfLifeDays: null,
    },
    {
      id: "day_buoc",
      name: "Dây buộc tóc",
      emoji: "🧶",
      unit: "cái",
      packSize: 10,
      costPerUnit: 5_000,
      shelfLifeDays: null,
    },
    {
      id: "giay_qua",
      name: "Giấy gói quà",
      emoji: "🎁",
      unit: "tờ",
      packSize: 20,
      costPerUnit: 1_500,
      shelfLifeDays: null,
    },
  ],

  equipment: [
    {
      id: "xe_banh_mi",
      name: "Xe bánh mì kính",
      price: 1_200_000,
      products: ["banh_mi"],
      queueSize: 4,
      model: "xe-banh-mi",
    },
    {
      id: "xe_tra_sua",
      name: "Xe đẩy trà sữa",
      price: 1_300_000,
      products: ["tra_sua"],
      queueSize: 4,
      model: "xe-tra-sua",
    },
    {
      id: "sap_phu_kien",
      name: "Sạp phụ kiện",
      price: 600_000,
      products: ["phu_kien"],
      queueSize: 3,
      model: "sap-phu-kien",
    },
  ],

  trafficProfiles: [
    {
      id: "school",
      name: "Cổng trường",
      peoplePerHour: {
        "6": 160,
        "7": 220,
        "8": 60,
        "10": 30,
        "11": 140,
        "12": 60,
        "14": 40,
        "16": 150,
        "17": 170,
        "18": 60,
        "20": 20,
      },
    },
    {
      id: "office",
      name: "Khu văn phòng",
      peoplePerHour: {
        "6": 40,
        "7": 160,
        "8": 120,
        "10": 50,
        "11": 150,
        "12": 160,
        "13": 60,
        "16": 70,
        "17": 170,
        "18": 90,
        "20": 30,
      },
    },
    {
      id: "residential",
      name: "Trong hẻm",
      peoplePerHour: {
        "6": 60,
        "7": 80,
        "9": 40,
        "12": 40,
        "16": 60,
        "18": 90,
        "19": 100,
        "21": 60,
      },
    },
    {
      id: "market",
      name: "Gần chợ",
      peoplePerHour: {
        "6": 180,
        "7": 200,
        "9": 150,
        "11": 90,
        "14": 50,
        "16": 80,
        "18": 70,
        "20": 30,
      },
    },
    {
      id: "crossroad",
      name: "Ngã tư",
      peoplePerHour: {
        "6": 120,
        "7": 180,
        "9": 110,
        "11": 120,
        "13": 90,
        "16": 140,
        "18": 180,
        "20": 140,
        "21": 90,
      },
    },
  ],

  // Vỉa hè bắc (z ≈ -3) và nam (z ≈ 3) của con phố thử nghiệm (apps/web/game/scene/Street.tsx).
  lots: [
    {
      id: "dau_hem",
      name: "Đầu hẻm 12",
      hint: "Dân trong hẻm, đông chiều tối",
      traffic: "residential",
      trafficScale: 1,
      rentPerDay: 25_000,
      position: { x: -18, z: -2.8 },
      facing: 0,
    },
    {
      id: "cong_truong",
      name: "Cổng trường",
      hint: "Học sinh đông sáng sớm, trưa, chiều",
      traffic: "school",
      trafficScale: 1,
      rentPerDay: 40_000,
      position: { x: -12, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "gan_cho",
      name: "Gần chợ",
      hint: "Sáng rất đông, chiều vắng",
      traffic: "market",
      trafficScale: 1,
      rentPerDay: 35_000,
      position: { x: -4.5, z: -2.8 },
      facing: 0,
    },
    {
      id: "nga_tu",
      name: "Góc ngã tư",
      hint: "Đông cả ngày, thuê đắt",
      traffic: "crossroad",
      trafficScale: 1.1,
      rentPerDay: 120_000,
      position: { x: 2.8, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "van_phong",
      name: "Trước toà văn phòng",
      hint: "Giờ đi làm, giờ trưa, tan tầm",
      traffic: "office",
      trafficScale: 1,
      rentPerDay: 50_000,
      position: { x: 9, z: -2.8 },
      facing: 0,
    },
    {
      id: "goc_cay",
      name: "Dưới gốc cây",
      hint: "Mát, khách lai rai",
      traffic: "residential",
      trafficScale: 0.8,
      rentPerDay: 15_000,
      position: { x: 14, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "cuoi_pho",
      name: "Cuối phố",
      hint: "Vắng, rẻ",
      traffic: "residential",
      trafficScale: 0.6,
      rentPerDay: 10_000,
      position: { x: 20, z: -2.8 },
      facing: 0,
    },
    {
      id: "ben_xe_buyt",
      name: "Trạm xe buýt",
      hint: "Người chờ xe cả ngày",
      traffic: "office",
      trafficScale: 0.9,
      rentPerDay: 30_000,
      position: { x: -22, z: 2.8 },
      facing: Math.PI,
    },
    {
      id: "nha_so_10",
      name: "🏠 Nhà mặt tiền số 10",
      hint: "Có tiệm trong nhà, bàn ghế cho khách ngồi, không lo mưa nắng",
      traffic: "residential",
      trafficScale: 1.15,
      rentPerDay: 70_000,
      position: { x: -12, z: -4.6 },
      facing: 0,
      kind: "house",
    },
    {
      id: "nha_so_24",
      name: "🏠 Nhà mặt tiền số 24",
      hint: "Tiệm sát ngã tư phía đông, khách đi làm ghé đông",
      traffic: "crossroad",
      trafficScale: 1.05,
      rentPerDay: 140_000,
      position: { x: 24, z: 4.6 },
      facing: Math.PI,
      kind: "house",
    },
  ],

  npcs: [
    {
      id: "hoc_sinh",
      name: "Học sinh",
      patienceSec: 35,
      transferRate: 0.2,
      model: "character-female-a",
      likes: { breakfast: 1.2, drink: 1.5, accessory: 1.3 },
    },
    {
      id: "dan_van_phong",
      name: "Dân văn phòng",
      patienceSec: 40,
      transferRate: 0.5,
      model: "character-male-c",
      likes: { breakfast: 1.3, drink: 1.1, accessory: 0.6 },
    },
    {
      id: "co_chu",
      name: "Cô chú trong xóm",
      patienceSec: 60,
      transferRate: 0.05,
      model: "character-female-d",
      likes: { breakfast: 1.1, drink: 0.5, accessory: 0.7 },
    },
    {
      id: "khach_vang_lai",
      name: "Khách vãng lai",
      patienceSec: 45,
      transferRate: 0.25,
      model: "character-male-a",
      likes: { breakfast: 1, drink: 1, accessory: 0.8 },
    },
    {
      // Khách VIP (sự kiện cá nhân, content.events): không ghé như khách thường.
      id: "vip",
      name: "Khách sộp",
      patienceSec: 40,
      transferRate: 0.8,
      model: "character-male-c",
      likes: { breakfast: 1, drink: 1, accessory: 1 },
    },
    {
      id: "reviewer",
      name: "Reviewer",
      patienceSec: 50,
      transferRate: 0.3,
      model: "character-male-a",
      likes: { breakfast: 1, drink: 1, accessory: 1 },
    },
  ],

  jobs: [
    {
      id: "phu_quan_com",
      name: "Phụ quán cơm Cô Tư",
      wagePerHour: 10_000,
      description:
        "Vào quán làm một vai: múc cơm, thu ngân hoặc bưng bê. Đông nhất giờ trưa và chiều tối.",
      maxStrikes: 6,
      roles: [
        {
          id: "dung_quay",
          name: "Đứng quầy múc cơm",
          emoji: "🍚",
          description: "Lấy dĩa, múc đúng món khách gọi, đưa dĩa.",
          piecePay: 3_000,
          guide: [
            "Con đứng quầy múc cơm nha. Khách xếp hàng trước quầy, gọi món — chữ hiện trên đầu khách và trên phiếu ở dưới.",
            "Nhìn dòng 'Cần múc' trên phiếu: ghi đủ những gì phải lên dĩa. Cơm sườn là cơm + sườn + dưa leo cà chua + canh; khách dặn thêm/bớt thì đã tính sẵn.",
            "Chạm từng khay để múc lên dĩa. Múc đủ món nào thì món đó có dấu ✓; múc thừa báo đỏ — chạm món trên dĩa để bỏ bớt.",
            "Đủ hết thì bấm '🤲 Đưa món'. Khay hết thì bấm '🔔 Báo bếp', đợi bếp mang khay mới ra.",
            "Khách chờ lâu sẽ than — bấm '🙏 Xin lỗi'. Múc đúng mỗi dĩa được tiền việc, giờ nào có làm thì có lương giờ. Kéo một ngón để xoay góc nhìn.",
          ],
        },
        {
          id: "thu_ngan",
          name: "Thu ngân",
          emoji: "🧾",
          description: "Bấm món lên máy, báo giá, thu tiền, thối tiền. Cuối ca kiểm két.",
          piecePay: 2_500,
          guide: [
            "Con đứng máy tính tiền. Khách ăn xong đứng dậy đi tới quầy, đưa phiếu cho con.",
            "Đọc từng dòng trên phiếu rồi bấm đúng món trên máy: dĩa cơm, thêm trứng/cơm, nước uống. Máy tự cộng TỔNG.",
            "Bấm 'Báo giá'. Khách chuyển khoản thì nhận luôn; đưa tiền mặt thì ghép tờ tiền để thối — cần thì bấm '💡 Tính giúp'.",
            "Tính dư thì khách bắt lỗi; tính thiếu hay thối thiếu thì cuối ca kiểm két, thiếu bao nhiêu trừ lương bấy nhiêu.",
            "Thấy khách đi ra mà chưa trả tiền thì bấm '📢 Gọi lại' liền nha!",
          ],
        },
        {
          id: "bung_be",
          name: "Bưng bê",
          emoji: "🍽️",
          description: "Bưng dĩa ra đúng bàn, dọn bàn khách ăn xong.",
          piecePay: 2_000,
          guide: [
            "Con bưng bê: dĩa múc xong đặt ở CỬA BẾP, mỗi dĩa kẹp số bàn.",
            "Tới cửa bếp (chạm vào đó hoặc bấm '📍 Tới cửa bếp') rồi bấm '🍽️ Lấy dĩa bàn …' — một lần cầm tối đa 2 dĩa.",
            "Bưng tới đúng bàn đó (bấm '📍 Mang dĩa tới bàn …' hoặc chạm cái bàn), tới nơi bấm '🤲 Giao món'. Đặt nhầm bàn là bị nhắc đó.",
            "Khách ăn xong để lại chén dĩa: tới bàn bấm '🧽 Lau bàn' — bàn bẩn thì khách mới không ngồi được.",
            "Bàn nào cãi nhau thì tới bấm '✋ Can ngăn'. Kéo một ngón để xoay góc nhìn, chụm hai ngón để thu/phóng.",
          ],
        },
      ],
    },
    {
      id: "giao_hang",
      name: "Giao hàng bưu cục Anh Tám",
      wagePerHour: 8_000,
      description:
        "Nhận đơn, soạn đúng gói trên kệ, chạy xe đi giao tận nhà, ký nhận, thu tiền hộ, về nộp tiền.",
      maxStrikes: 4,
      roles: [
        {
          id: "giao_hang",
          name: "Giao hàng",
          emoji: "📦",
          description: "Mỗi chuyến tối đa 3 đơn.",
          piecePay: 12_000,
          guide: [
            "Em nhận đơn ở quầy: bấm '📋 Nhận đơn giao', mỗi chuyến tối đa 3 đơn, mỗi đơn có mã XM-….",
            "Các gói trên kệ nhìn giống nhau — đọc kỹ mã rồi chạm đúng gói để soạn, soạn sai là bị nhắc.",
            "Soạn xong bấm '🛵 Ra xe đi giao'. Ngoài phố bấm '🛵 Đi tới' để chạy tới nhà; hàng dễ vỡ thì chạy chậm kẻo móp.",
            "Tới cửa bấm '🔔 Gọi khách', đưa điện thoại cho người ra mở cửa ký, kiểm tên người ký — người lạ thì không giao.",
            "Đơn thu hộ thì thu tiền, thối tiền. Khách vắng: gửi hàng xóm / hẹn lại / hoàn về. Giao xong về bưu cục bấm '💵 Nộp tiền'.",
          ],
        },
      ],
    },
  ],

  restaurant: {
    foods: [
      { id: "com", name: "Cơm", emoji: "🍚", model: "rice-ball" },
      { id: "suon", name: "Sườn nướng", emoji: "🍖", model: "meat-ribs" },
      { id: "bi", name: "Bì", emoji: "🥢", model: "mincemeat-pie" },
      { id: "cha", name: "Chả trứng", emoji: "🟨", model: "pudding" },
      { id: "trung", name: "Trứng ốp la", emoji: "🍳", model: "egg-cooked" },
      { id: "dua", name: "Dưa leo cà chua", emoji: "🥒", model: "tomato-slice" },
      { id: "canh", name: "Canh", emoji: "🥣", model: "bowl-soup" },
    ],
    dishes: [
      {
        id: "com_suon",
        name: "Cơm sườn",
        items: ["com", "suon", "dua", "canh"],
        price: 35_000,
        popularity: 3,
      },
      {
        id: "com_suon_bi_cha",
        name: "Cơm sườn bì chả",
        items: ["com", "suon", "bi", "cha", "dua", "canh"],
        price: 45_000,
        popularity: 2,
      },
      {
        id: "com_suon_trung",
        name: "Cơm sườn trứng",
        items: ["com", "suon", "trung", "dua", "canh"],
        price: 40_000,
        popularity: 2,
      },
      {
        id: "com_cha_trung",
        name: "Cơm chả trứng",
        items: ["com", "cha", "trung", "dua", "canh"],
        price: 32_000,
        popularity: 1,
      },
    ],
    mods: [
      { id: "them_trung", say: "thêm trứng", add: "trung", price: 6_000, chance: 0.2 },
      { id: "them_com", say: "thêm cơm", add: "com", price: 5_000, chance: 0.15 },
      { id: "khong_dua", say: "không dưa", remove: "dua", price: 0, chance: 0.15 },
      { id: "khong_canh", say: "khỏi canh", remove: "canh", price: 0, chance: 0.1 },
    ],
    drinks: [
      { id: "tra_da", name: "Trà đá", emoji: "🧊", price: 3_000, chance: 0.5 },
      { id: "nuoc_ngot", name: "Nước ngọt", emoji: "🥤", price: 12_000, chance: 0.15 },
    ],
    trayPortions: 10,
    refillSec: 15,
    tables: 6,
    customersPerHour: {
      "6": 2,
      "8": 3,
      "10": 5,
      "11": 12,
      "12": 14,
      "13": 7,
      "15": 3,
      "17": 10,
      "18": 11,
      "19": 6,
      "21": 2,
    },
    patienceSec: 45,
    // Quầy cơm ở z = 0 (bếp phía sau, z > 0), phòng ăn phía trước (z < 0), cửa ra vào ở tường trái.
    layout: {
      door: { x: -6.6, z: -2.4 },
      queue: { x: -0.2, z: -1.0 },
      queueStep: { x: -0.75, z: -0.35 },
      pass: { x: -2.4, z: -0.6 },
      cashier: { x: 2.3, z: -1.0 },
      cashierStep: { x: 0.7, z: -0.35 },
      tables: [
        { x: -2.9, z: -3.8 },
        { x: 0, z: -3.8 },
        { x: 2.9, z: -3.8 },
        { x: -2.9, z: -6.4 },
        { x: 0, z: -6.4 },
        { x: 2.9, z: -6.4 },
      ],
    },
  },

  // Bản đồ xóm (UC-B6): phố chính z = 0 (các địa điểm cũ giữ nguyên toạ độ), hai đường dọc x = ±28,
  // hai phố sau z = ±20, hẻm x = 0; công viên (tây bắc), chợ (tây nam), trường học (đông bắc), toà văn phòng + bãi xe (đông nam).
  map: {
    tile: 4,
    origin: { x: -52, z: -28 },
    rows: [
      "HHHHHH|HHHHHHHHHHHHH|HHHHHH",
      "ssssss|sssssssssssss|ssssss",
      "======+=============+======",
      "ssssss|sssssssssssss|ssssss",
      "BPPPPB|BBBBBBaBBBBBB|BKKKKB",
      "BPPPPB|BBBBBBaBBBBBB|BSSSSB",
      "ssssss|sssssssssNsss|ssssss",
      "======+======c======+======",
      "ssssss|sssssNsssssss|ssssss",
      "BMMMMB|BBBBBBaBBBBBB|BTTTTB",
      "BMMMMB|BBBBBBaBBBBBB|BLLLLB",
      "ssssss|sssssssssssss|ssssss",
      "======+=============+======",
      "ssssss|sssssssssssss|ssssss",
      "HHHHHH|HHHHHHHHHHHHH|HHHHHH",
    ],
  },

  // Sạp đồ ăn NPC theo giờ (UC-B9): sáng xôi, phở, cà phê; trưa nước mía; chiều bánh tráng, chè; tối ốc, nướng.
  vendors: [
    {
      id: "xoi_ba_bay",
      name: "Bà Bảy",
      sign: "XÔI BÀ BẢY",
      signColor: "#c0392b",
      model: "sap-phu-kien",
      position: { x: -44, z: -3 },
      facing: 0,
      open: 330,
      close: 600,
      seats: 2,
      cashOnly: true,
      lines: ["Xôi nóng đây con!", "Ăn xôi cho chắc bụng đi học!"],
      items: [
        { id: "xoi_ga", name: "Xôi gà", emoji: "🍗", price: 20_000, food: 55 },
        { id: "xoi_xeo", name: "Xôi xéo", emoji: "🍚", price: 15_000, food: 45 },
      ],
    },
    {
      id: "pho_chu_hai",
      name: "Chú Hai",
      sign: "PHỞ CHÚ HAI",
      signColor: "#8e44ad",
      model: "xe-banh-mi",
      position: { x: -36, z: 3 },
      facing: Math.PI,
      open: 330,
      close: 630,
      seats: 3,
      lines: ["Phở bò tái nạm đây!", "Nước lèo ninh từ khuya đó."],
      items: [
        { id: "pho_tai", name: "Phở tái", emoji: "🍜", price: 40_000, food: 70, drink: 15 },
        { id: "pho_ga", name: "Phở gà", emoji: "🍲", price: 35_000, food: 65, drink: 15 },
      ],
    },
    {
      id: "ca_phe_coc",
      name: "Cô Ba",
      sign: "CÀ PHÊ CÓC",
      signColor: "#6d4c41",
      model: "xe-tra-sua",
      position: { x: 36, z: 3 },
      facing: Math.PI,
      open: 360,
      close: 660,
      seats: 3,
      cashOnly: true,
      lines: ["Cà phê sữa đá hông con?", "Ngồi đây coi người qua lại nè."],
      items: [
        { id: "cf_sua_da", name: "Cà phê sữa đá", emoji: "🧋", price: 18_000, food: 5, drink: 45 },
        { id: "bac_xiu", name: "Bạc xỉu", emoji: "🥛", price: 20_000, food: 10, drink: 45 },
      ],
    },
    {
      id: "nuoc_mia",
      name: "Anh Tư",
      sign: "NƯỚC MÍA",
      signColor: "#27ae60",
      model: "xe-tra-sua",
      position: { x: 32, z: -3 },
      facing: 0,
      open: 600,
      close: 1020,
      seats: 2,
      lines: ["Nước mía tắc đây, mát lạnh!", "Trưa nắng uống ly nước mía đi em."],
      items: [
        { id: "nuoc_mia_ly", name: "Nước mía", emoji: "🥤", price: 12_000, food: 5, drink: 60 },
      ],
    },
    {
      id: "banh_trang_tron",
      name: "Chị Út",
      sign: "BÁNH TRÁNG TRỘN",
      signColor: "#e67e22",
      model: "sap-phu-kien",
      position: { x: 44, z: -3 },
      facing: 0,
      open: 840,
      close: 1140,
      seats: 2,
      lines: ["Bánh tráng trộn nè mấy đứa!", "Tan học ghé chị nha!"],
      items: [
        { id: "banh_trang", name: "Bánh tráng trộn", emoji: "🥗", price: 15_000, food: 30 },
        { id: "banh_trang_nuong", name: "Bánh tráng nướng", emoji: "🫓", price: 18_000, food: 30 },
      ],
    },
    {
      id: "che_co_nam",
      name: "Cô Năm",
      sign: "CHÈ CÔ NĂM",
      signColor: "#d35493",
      model: "xe-tra-sua",
      position: { x: -12, z: 17.5 },
      facing: 0,
      open: 840,
      close: 1230,
      seats: 3,
      lines: ["Chè thái, chè đậu đây!", "Ăn chè cho mát nha con."],
      items: [
        { id: "che_thai", name: "Chè thái", emoji: "🍧", price: 20_000, food: 20, drink: 35 },
        { id: "che_dau", name: "Chè đậu", emoji: "🍨", price: 15_000, food: 20, drink: 30 },
      ],
    },
    {
      id: "oc_dem",
      name: "Anh Sáu",
      sign: "ỐC ĐÊM",
      signColor: "#16a085",
      model: "sap-phu-kien",
      position: { x: -8, z: -17.5 },
      facing: Math.PI,
      open: 1050,
      close: 1320,
      seats: 4,
      lines: ["Ốc hương xào bơ tỏi đây!", "Tối rồi, làm dĩa ốc đi anh em!"],
      items: [
        { id: "oc_huong", name: "Ốc hương xào bơ", emoji: "🐚", price: 50_000, food: 40 },
        { id: "so_diep", name: "Sò điệp nướng", emoji: "🦪", price: 45_000, food: 35 },
      ],
    },
    {
      id: "nuong_dem",
      name: "Chú Tám",
      sign: "NƯỚNG ĐÊM",
      signColor: "#d35400",
      model: "xe-banh-mi",
      position: { x: 12, z: 17.5 },
      facing: 0,
      open: 1080,
      close: 1320,
      seats: 4,
      lines: ["Thịt nướng thơm lừng đây!", "Nướng tới đâu ăn tới đó!"],
      items: [
        { id: "xien_nuong", name: "Xiên nướng", emoji: "🍢", price: 10_000, food: 20 },
        { id: "bap_nuong", name: "Bắp nướng", emoji: "🌽", price: 12_000, food: 25 },
      ],
    },
  ],

  // Nhà trong xóm để giao hàng: trước mặt tiền, hai bên phố (Street.tsx).
  delivery: {
    addresses: [
      { id: "nha_3", label: "Nhà số 3", position: { x: -16, z: -5.2 }, facing: 0 },
      { id: "nha_7", label: "Nhà số 7", position: { x: -8, z: -5.2 }, facing: 0 },
      { id: "nha_12", label: "Nhà số 12", position: { x: 4, z: -5.2 }, facing: 0 },
      { id: "nha_18", label: "Nhà số 18", position: { x: 20, z: -5.2 }, facing: 0 },
      { id: "nha_5", label: "Nhà số 5", position: { x: -20, z: 5.2 }, facing: Math.PI },
      { id: "nha_9", label: "Nhà số 9", position: { x: -2, z: 5.2 }, facing: Math.PI },
      { id: "nha_15", label: "Nhà số 15", position: { x: 8, z: 5.2 }, facing: Math.PI },
      { id: "nha_21", label: "Nhà số 21", position: { x: 16, z: 5.2 }, facing: Math.PI },
    ],
    recipients: [
      "Anh Hùng",
      "Chị Mai",
      "Cô Lan",
      "Chú Tư",
      "Bạn Minh",
      "Chị Thảo",
      "Anh Khoa",
      "Bà Sáu",
    ],
    relatives: ["vợ", "chồng", "con", "em"],
    items: [
      { name: "Áo thun", fragile: false, value: 120_000 },
      { name: "Sách", fragile: false, value: 85_000 },
      { name: "Nồi cơm điện", fragile: true, value: 450_000 },
      { name: "Bộ chén sứ", fragile: true, value: 180_000 },
      { name: "Giày thể thao", fragile: false, value: 350_000 },
      { name: "Ốp điện thoại", fragile: false, value: 60_000 },
    ],
    absentRate: 0.15,
    codRate: 0.6,
    fragileDamageFast: 0.35,
    maxPerTrip: 3,
    shelfSize: 6,
  },

  // Địa điểm có người đứng quầy (docs/PLAN.md Phase 1.5). Toạ độ trên vỉa hè sát mặt tiền nhà.
  places: [
    {
      id: "vua_xe",
      name: "Vựa xe Ông Sáu",
      kind: "equipment_shop",
      sign: "VỰA XE ÔNG SÁU",
      signColor: "#2b2118",
      action: "🛒 Xem xe đẩy",
      keeper: {
        name: "Ông Sáu",
        model: "character-male-c",
        greeting: "Xe nào cũng chắc hết, con coi hợp nghề nào thì lấy nghề đó.",
        talk: {
          price: [
            "Xe bánh mì 320, xe trà sữa 380, sạp phụ kiện 280. Giá gốc, không nói thách.",
            "Xe cũ mang lại ông mua nửa giá, sòng phẳng.",
          ],
          gossip: [
            "Hồi trước ông cũng đẩy xe bán hủ tiếu gõ ở đầu hẻm này đó.",
            "Ngã tư đông mà tiền thuê cắt cổ, mới làm đừng ham.",
          ],
        },
      },
      position: { x: -21.5, z: -4.9 },
      facing: 0,
      props: [
        { model: "xe-banh-mi", dx: -1.8, dz: 0.3, rot: 0 },
        { model: "xe-tra-sua", dx: 1.8, dz: 0.3, rot: 0 },
        { model: "detail-awning-wide", dx: 0, dz: -1.2, rot: 0 },
      ],
    },
    {
      id: "cho_dau_moi",
      name: "Chợ đầu mối Bà Năm",
      kind: "market",
      sign: "CHỢ ĐẦU MỐI",
      signColor: "#f6b93b",
      action: "🧺 Vào chợ",
      keeper: {
        name: "Bà Năm",
        model: "character-female-d",
        greeting: "Hàng mới về sáng nay nè con. Đồ ăn thì lấy vừa đủ bán, để qua đêm là bỏ.",
        talk: {
          price: [
            "Sáng giá gốc, qua trưa đồ tươi là bà lấy thêm chút vì hàng còn ít.",
            "Mua từ 5 gói trở lên bà bớt cho.",
          ],
          gossip: [
            "Nghe nói mai trường tan sớm đó, bán ở cổng trường là trúng.",
            "Mấy bữa nay trà sữa bán chạy dữ lắm, tụi nhỏ mê trân châu trắng.",
          ],
        },
      },
      position: { x: -6.5, z: 4.9 },
      facing: Math.PI,
      props: [
        { model: "detail-parasol-a", dx: -1.4, dz: 0, rot: 0 },
        { model: "detail-parasol-b", dx: 1.4, dz: 0.2, rot: 0 },
        { model: "ghe-nhua-do", dx: -0.6, dz: 0.8, rot: 0.4 },
        { model: "detail-awning-wide", dx: 0, dz: 1.2, rot: Math.PI },
      ],
    },
    {
      id: "quan_com",
      name: "Quán cơm Cô Tư",
      kind: "job",
      sign: "CƠM TẤM CÔ TƯ",
      signColor: "#e4432d",
      action: "🍚 Vào quán",
      keeper: {
        name: "Cô Tư",
        model: "character-female-a",
        greeting: "Trưa nay đông lắm, phụ cô một tay đi con!",
        talk: {
          price: [
            "Cơm tấm cô bán 30 ngàn một dĩa, phụ quán cô trả 10 ngàn một giờ.",
            "Làm siêng cô thưởng thêm.",
          ],
          gossip: [
            "Dân văn phòng trưa nào cũng kéo qua đây, 11 giờ là đông nghẹt.",
            "Con bé bán bánh mì đầu hẻm dạo này đông khách ghê.",
          ],
        },
      },
      jobs: ["phu_quan_com"],
      position: { x: 15, z: -4.9 },
      facing: 0,
      props: [
        { model: "ghe-nhua-do", dx: -1.6, dz: 0.9, rot: 0.2 },
        { model: "ghe-nhua-do", dx: -0.9, dz: 1.3, rot: -0.3 },
        { model: "ghe-nhua-do", dx: 1.1, dz: 1.1, rot: 0.6 },
        { model: "detail-parasol-a", dx: -1.2, dz: 1.1, rot: 0 },
        { model: "detail-awning-wide", dx: 0, dz: -1.2, rot: 0 },
      ],
    },
    {
      id: "buu_cuc",
      name: "Bưu cục",
      kind: "job",
      sign: "BƯU CỤC",
      signColor: "#2f7d4f",
      action: "📦 Vào bưu cục",
      keeper: {
        name: "Anh Tám",
        model: "character-male-a",
        greeting: "Có xe máy chưa em? Có thì chạy đơn quanh xóm, trả theo giờ.",
        talk: {
          price: [
            "Chạy đơn anh trả 12 ngàn một giờ, giao lẹ có thưởng.",
            "Cuối tuần đơn nhiều lắm.",
          ],
          gossip: [
            "Chiều nay có mưa đó, lo mà che hàng.",
            "Văn phòng đầu phố hay đặt trà sữa buổi chiều.",
          ],
        },
      },
      jobs: ["giao_hang"],
      position: { x: 19.5, z: 4.9 },
      facing: Math.PI,
      props: [{ model: "detail-awning-wide", dx: 0, dz: 1.2, rot: Math.PI }],
    },
  ],

  speakers: [
    {
      id: "chu_bay",
      name: "Chú Bảy xe ôm",
      model: "character-male-c",
      position: { x: -8, z: -4.6 },
      facing: Math.PI / 2,
    },
  ],

  // Kịch bản người mới — rẽ nhánh buôn bán / làm thuê.
  tutorial: [
    {
      id: "gap_chu_bay",
      speaker: "chu_bay",
      lines: [
        "Ủa, con là người mới dọn về xóm hả? Chú là Bảy, chạy xe ôm đầu hẻm nè.",
        "Ở xóm này ai cũng tự lo lấy cái nghề. Trong túi con có 500 ngàn — đủ mua một chiếc xe đẩy nhỏ.",
        "Còn chưa chắc tay thì qua quán cơm Cô Tư phụ việc, kiếm vốn trước cũng được.",
      ],
      choices: [
        { text: "Con muốn buôn bán", next: "den_vua_xe" },
        { text: "Con đi làm thuê trước", next: "den_quan_com" },
      ],
    },
    {
      id: "den_vua_xe",
      objective: "Tới vựa xe Ông Sáu mua một chiếc xe đẩy",
      target: "vua_xe",
      until: "has_business",
      next: "ra_cho",
    },
    {
      id: "ra_cho",
      speaker: "chu_bay",
      lines: [
        "Có xe rồi hả? Giờ ra chợ đầu mối Bà Năm mua nguyên liệu — món nào cần gì thì mua nấy.",
        "Bánh mì thì phải có ổ bánh, nhân, rau, gia vị, giấy gói. Đồ tươi để qua đêm là hư, mua vừa đủ thôi nghe!",
      ],
      objective: "Ra chợ mua đủ nguyên liệu cho một món",
      target: "cho_dau_moi",
      until: "has_stock",
      next: "chon_cho",
    },
    {
      id: "chon_cho",
      speaker: "chu_bay",
      lines: [
        "Giờ chọn chỗ bán. Chỗ đông khách thì thuê đắt — mới làm nên thử Đầu hẻm 12, rẻ mà có khách.",
      ],
      objective: "Chọn chỗ bán trong mục Kinh doanh",
      until: "has_lot",
      next: "ra_quay",
    },
    {
      id: "ra_quay",
      objective: "Đẩy xe tới chỗ bán và mở quầy",
      target: "stall",
      until: "shop_open",
      next: "phuc_vu",
    },
    {
      id: "phuc_vu",
      speaker: "chu_bay",
      lines: [
        "Mở hàng rồi đó! Khách tới sẽ dặn món, con nghe cho kỹ: không hành là không hành nghe chưa.",
        "Làm xong thì tính tiền, thối tiền cho đúng. Làm lẹ, làm đúng là khách boa, lại nhớ quầy mình.",
      ],
      objective: "Phục vụ 3 khách: làm đúng món, thối đúng tiền",
      target: "stall",
      until: "served_3",
      next: "xong_buon_ban",
    },
    {
      id: "xong_buon_ban",
      speaker: "chu_bay",
      lines: [
        "Được rồi đó con! Nhớ nè: hết hàng thì ra chợ nhập thêm, đừng để khách về tay không.",
        "Tối coi sổ sách cuối ngày cho kỹ. Thôi chú chạy cuốc xe đây, chúc con đắt hàng!",
      ],
      next: "hoan_thanh",
    },
    {
      id: "den_quan_com",
      objective: "Tới quán cơm Cô Tư, bước vào và chọn một việc",
      target: "quan_com",
      until: "has_job",
      next: "lam_viec",
    },
    {
      id: "lam_viec",
      objective: "Làm đúng 2 việc trong quán (múc dĩa, tính tiền hay bưng bàn)",
      target: "quan_com",
      until: "job_tasks_2",
      next: "xong_lam_thue",
    },
    {
      id: "xong_lam_thue",
      speaker: "chu_bay",
      lines: [
        "Siêng dữ ha! Làm thuê thì chắc ăn: có lương giờ, làm đúng việc nào ăn tiền việc đó.",
        "Khi nào có vốn thì ghé vựa xe Ông Sáu, tự làm chủ cái quầy. Chú đi đây!",
      ],
      next: "hoan_thanh",
    },
    // Hết kịch bản người mới.
    { id: "hoan_thanh" },
  ],

  quickPhrases: [
    { id: "rao_hang", text: "Mời ghé ủng hộ nha! Nóng giòn đây!", shout: true },
    { id: "chao", text: "Chào cả xóm!" },
    { id: "cam_on", text: "Cảm ơn nha!" },
    { id: "xin_loi_het", text: "Xin lỗi, hết hàng rồi!" },
    { id: "cho_chut", text: "Đợi xíu nha, có liền!" },
    { id: "vui", text: "😄" },
    { id: "vay_tay", text: "👋" },
  ],

  // Đói / khát (UC-B11): no tụt từ 100 xuống 0 trong ~10 giờ game, khát ~7 giờ; ngủ đêm chỉ tính 4 giờ.
  needs: {
    foodPerHour: 10,
    drinkPerHour: 14,
    nightMinutes: 240,
    lowAt: 30,
    slowHold: 1.25,
    byCategory: { breakfast: { food: 45, drink: 0 }, drink: { food: 10, drink: 55 } },
    callouts: [
      "Ơi có ai bán không dạ?",
      "Chủ quán đâu rồi ta?",
      "Bán cho con với… có ai không?",
      "Quầy mở mà không thấy ai, thôi đi chỗ khác",
    ],
  },

  // Quỹ xóm + công trình chung (UC-J5). Giá tham khảo công trình nông thôn (đã nén như mọi số tiền trong game).
  fund: { feeShare: 0.6, voteMinutes: 240, donateStep: 10_000 },
  projects: [
    {
      id: "lat_hem_12",
      name: "Lát bê tông hẻm 12",
      emoji: "🛣️",
      description: "Đổ bê tông con hẻm đất đầu xóm, mưa không còn sình lầy.",
      why: "Mưa xuống hẻm sình, khách ngại vô đầu hẻm mua đồ.",
      cost: 600_000,
      buildDays: 2,
      demand: { lots: ["dau_hem", "goc_cay"], mult: 1.15 },
    },
    {
      id: "den_duong",
      name: "Đèn đường năng lượng mặt trời",
      emoji: "💡",
      description: "Dựng 6 trụ đèn dọc trục chính, tối đi lại sáng sủa.",
      why: "Chiều tối đường tối thui, người ta ngại ra đường ăn uống.",
      cost: 900_000,
      buildDays: 2,
      demand: { lots: ["nga_tu", "ben_xe_buyt", "nha_so_10", "nha_so_24"], mult: 1.08 },
    },
    {
      id: "mo_rong_cho",
      name: "Mở rộng mái che chợ",
      emoji: "⛺",
      description: "Dựng thêm mái tôn che nắng mưa quanh chợ đầu mối.",
      why: "Trời mưa là khách chạy hết, sạp gần chợ vắng hoe.",
      cost: 1_200_000,
      buildDays: 3,
      demand: { lots: ["gan_cho"], mult: 1.2 },
    },
    {
      id: "cau_tre",
      name: "Cầu tre qua mương cuối phố",
      emoji: "🌉",
      description: "Bắc cầu tre qua con mương, bà con xóm bên kia sang mua bán được.",
      why: "Cuối phố vắng vì xóm bên kia phải đi vòng cả cây số.",
      cost: 800_000,
      buildDays: 3,
      demand: { lots: ["cuoi_pho"], mult: 1.35 },
    },
    {
      id: "cau_be_tong",
      name: "Nâng cầu tre thành cầu bê tông",
      emoji: "🌁",
      description: "Thay cầu tre bằng cầu bê tông, xe máy chạy qua được.",
      why: "Cầu tre chỉ đi bộ được, xe chở hàng không qua nổi.",
      cost: 2_500_000,
      buildDays: 5,
      demand: { lots: ["cuoi_pho", "goc_cay"], mult: 1.2 },
      requires: "cau_tre",
    },
    {
      id: "ao_ca",
      name: "Đào ao cá + ghế đá công viên",
      emoji: "🎣",
      description: "Đào cái ao nhỏ thả cá, đặt ghế đá — chiều chiều người ta ra hóng mát.",
      why: "Xóm chưa có chỗ ngồi chơi, chiều tối ai cũng ở nhà.",
      cost: 1_500_000,
      buildDays: 4,
      demand: { lots: ["cong_truong", "van_phong", "goc_cay"], mult: 1.1 },
    },
  ],

  // Bảng giải của xóm (UC-P2): 7 ngày gần nhất, mỗi hạng mục một kiểu người chơi — không chỉ người giàu nhất.
  awards: [
    {
      id: "doanh_nhan",
      emoji: "💰",
      name: "Doanh nhân của tuần",
      description: "Doanh thu bán hàng 7 ngày",
      metric: "revenue",
    },
    {
      id: "lai_gioi",
      emoji: "🧮",
      name: "Buôn có lời nhất",
      description: "Lãi sau tiền hàng, thuê chỗ, phí",
      metric: "profit",
    },
    {
      id: "dong_khach",
      emoji: "👥",
      name: "Đông khách nhất",
      description: "Số món đã bán 7 ngày",
      metric: "served",
    },
    {
      id: "duoc_tin",
      emoji: "⭐",
      name: "Quầy được tin nhất",
      description: "Điểm đánh giá trung bình (ít nhất 3 đánh giá)",
      metric: "rating",
      min: 3,
    },
    {
      id: "tang_nhanh",
      emoji: "📈",
      name: "Lên như diều",
      description: "Doanh thu 3 ngày gần nhất so với 3 ngày trước",
      metric: "growth",
    },
    {
      id: "cham_lam",
      emoji: "💼",
      name: "Chăm làm nhất",
      description: "Tiền công làm thuê 7 ngày",
      metric: "wages",
    },
    {
      id: "than_thien",
      emoji: "🤝",
      name: "Thân thiện nhất",
      description: "Điểm kỹ năng Ăn nói",
      metric: "friendly",
    },
  ],

  achievements: [
    {
      id: "mo_hang",
      emoji: "🥖",
      name: "Mở hàng",
      description: "Bán món đầu tiên",
      metric: "served",
      goal: 1,
    },
    {
      id: "khoi_nghiep",
      emoji: "🍜",
      name: "Khởi nghiệp",
      description: "Bán 100 món",
      metric: "served",
      goal: 100,
    },
    {
      id: "tay_to",
      emoji: "🔥",
      name: "Tay to",
      description: "Bán 1.000 món",
      metric: "served",
      goal: 1000,
    },
    {
      id: "trieu_dau",
      emoji: "💵",
      name: "Triệu đầu tiên",
      description: "Doanh thu cộng dồn 1.000.000đ",
      metric: "revenue",
      goal: 1_000_000,
    },
    {
      id: "chuc_trieu",
      emoji: "💰",
      name: "Chục triệu",
      description: "Doanh thu cộng dồn 10.000.000đ",
      metric: "revenue",
      goal: 10_000_000,
    },
    {
      id: "cham_chi",
      emoji: "💼",
      name: "Chăm chỉ",
      description: "Kiếm 300.000đ tiền công làm thuê",
      metric: "wages",
      goal: 300_000,
    },
    {
      id: "nam_sao",
      emoji: "⭐",
      name: "Năm sao",
      description: "Nhận 10 đánh giá 5★",
      metric: "five_stars",
      goal: 10,
    },
    {
      id: "co_tam",
      emoji: "💬",
      name: "Chủ quầy có tâm",
      description: "Trả lời 10 đánh giá",
      metric: "replies",
      goal: 10,
    },
    {
      id: "rinh_rang",
      emoji: "🎉",
      name: "Rình rang",
      description: "Tổ chức khai trương lần đầu",
      metric: "events",
      goal: 1,
    },
    {
      id: "cap_5",
      emoji: "🌟",
      name: "Lên cấp 5",
      description: "Đạt cấp 5",
      metric: "level",
      goal: 5,
    },
    {
      id: "nguoi_quen",
      emoji: "🫶",
      name: "Người quen của xóm",
      description: "Thân với 3 người bán (thân thiết từ 30)",
      metric: "friends",
      goal: 3,
    },
  ],

  // Sổ đánh giá quầy (UC-F11): câu theo tình huống — giọng khách xóm + chút Gen Z.
  reviews: {
    chance: 0.3,
    lostChance: 0.35,
    replyRep: 0.01,
    maxText: 140,
    names: [
      "Linh",
      "Huy",
      "Trâm",
      "Khoa",
      "Ngọc",
      "Tú",
      "Bảo",
      "My",
      "Đạt",
      "Vy",
      "chú Tư",
      "cô Sáu",
    ],
    lines: {
      fast: [
        "Làm lẹ dữ, chưa kịp lướt xong cái story là có món 😳",
        "Nhanh gọn lẹ, 10 điểm không có nhưng",
        "Đứng chờ chưa tới một phút, mê!",
      ],
      ok: [
        "Ổn áp nha, mai ghé tiếp",
        "Ăn được, giá mềm, chủ quầy dễ thương",
        "Vừa miệng, không có gì để chê",
      ],
      slow: [
        "Chờ hơi lâu nha shop, sáng đi làm trễ luôn 🥲",
        "Ngon mà đợi mỏi chân quá trời",
        "Làm chậm rì, lần sau đặt trước chắc ổn hơn",
      ],
      wrong: [
        "Dặn không hành mà vẫn có hành, buồn ghê 😤",
        "Kêu một đằng làm một nẻo, xỉu",
        "Sai món mà được giảm giá nên thôi bỏ qua",
      ],
      pricey: [
        "Hơi chát so với mặt bằng xóm á",
        "Giá này ở chợ mua được hai cái rồi 💸",
        "Ngon nhưng ví mình khóc nhẹ",
      ],
      cheap: [
        "Rẻ mà chất lượng, kèo thơm 🔥",
        "Giá học sinh, ủng hộ dài dài",
        "Rẻ bất ngờ, ăn xong còn tiền mua trà đá",
      ],
      short: [
        "Thối thiếu tiền nha, phải đòi mới đưa đủ 😒",
        "Tính tiền ẩu quá, check lại giùm cái",
      ],
      lost: [
        "Đứng chờ mòn mỏi không ai làm, thôi đi quán khác",
        "Hàng đông mà một mình làm, bỏ cuộc 🫠",
        "Đợi hoài không tới lượt, bye",
      ],
      vip_good: [
        "Chuẩn vị, làm kỹ, sẽ giới thiệu bạn bè 👍",
        "Quầy nhỏ mà làm có tâm, recommend nha",
      ],
      vip_bad: ["Kỳ vọng nhiều mà hơi thất vọng", "Chưa tới, còn phải luyện thêm"],
    },
    quickReplies: {
      good: ["Cảm ơn bạn nhiều nha! 🥰", "Mai ghé tiếp nha, có món mới đó!"],
      bad: ["Xin lỗi bạn, lần sau mình làm kỹ hơn ạ 🙏", "Cảm ơn góp ý, mình sửa liền nha!"],
    },
    banned: ["đm", "dm", "đmm", "vcl", "vl", "đéo", "địt", "lồn", "cặc", "đĩ"],
  },

  // Giọng thoại theo kiểu khách (#12, USECASES UC-D6). Câu "mặn" nhẹ thôi — người chơi tắt được trong Cài đặt.
  voice: {
    voices: [
      {
        archetype: "hoc_sinh",
        ask: [
          "Shop ơi cho em {dish} nha 🥺",
          "Cho e {dish} vớiii, nhanh nhanh e trễ học r",
          "Chị ơi {dish} một cái nha, hôm nay đói xỉu ngang",
          "1 {dish} nha shop, ko lấy bịch đâu ạ",
        ],
        cheap: [
          "Rẻ vãi, mai em rủ cả lớp ra 🤩",
          "Giá học sinh luôn, iu shop",
          "U là trời rẻ dữ dzậy",
        ],
        pricey: [
          "Hơi chát á shop, tiền tiêu vặt e có nhiêu đâu 🥲",
          "Mắc dữ, tuần này nhịn trà sữa luôn",
          "Ủa sao mắc z trời",
        ],
        thanks: [
          "Ngon xỉu, 10 điểm ko có nhưng 💯",
          "Iu shop, mai ghé tiếp nha",
          "Đỉnh của chóp luôn á",
          "Tks shop nhaaa",
        ],
        impatient: [
          "Trễ học r, thôi em đi đây 😭",
          "Lâu vãi, thôi khum chờ nữa",
          "Chờ mòn mỏi luôn á, bye",
        ],
      },
      {
        archetype: "dan_van_phong",
        ask: [
          "Cho anh {dish}, nhanh giúp anh nha, 8h chấm công rồi",
          "Em ơi {dish} nha, chuyển khoản được không?",
          "Một {dish}, anh lấy mang đi",
          "Cho chị {dish} nha, deadline dí quá chưa kịp ăn",
        ],
        cheap: ["Giá này hợp lý ghê, mai anh dẫn team ra", "Rẻ mà chất lượng, recommend"],
        pricey: [
          "Giá hơi cao so với mặt bằng chung á em",
          "Ngang giá quán máy lạnh luôn rồi đó",
          "Lương chưa về mà giá này hơi căng",
        ],
        thanks: [
          "Ok em, chuyển rồi nha",
          "Ngon, cứu đói buổi sáng",
          "Nhanh gọn, 5 sao",
          "Ổn áp, mai ghé",
        ],
        impatient: [
          "Trễ giờ rồi, thôi anh đi",
          "Sếp gọi rồi, để bữa khác nha",
          "Đợi lâu quá, chịu không nổi",
        ],
      },
      {
        archetype: "co_chu",
        ask: [
          "Bán cho cô {dish} nghen con",
          "Con ơi lấy chú {dish}, đừng có cay nha",
          "Cho cô {dish}, gói kỹ kỹ cô mang về cho thằng cháu",
          "Con bé ơi, {dish} một phần coi",
        ],
        cheap: ["Rẻ vậy con, để cô giới thiệu mấy bà trong xóm", "Giá vậy là có lương tâm nè"],
        pricey: [
          "Hồi xưa có mấy ngàn hà, giờ mắc quá con ơi",
          "Mắc dữ vậy con, bớt cho cô chút coi",
          "Giá này chợ bán rẻ hơn á nghen",
        ],
        thanks: [
          "Cảm ơn con nghen, con làm khéo ghê",
          "Được đó con, mai cô ghé",
          "Ngon, giữ tiền lẻ luôn con",
        ],
        impatient: [
          "Thôi cô đi chợ đã, lát ghé",
          "Đợi lâu quá con, cô về nấu cơm đây",
          "Thôi để bữa khác nghen",
        ],
      },
      {
        archetype: "khach_vang_lai",
        ask: [
          "Cho mình {dish} nhé",
          "{dish} một phần, bạn ơi",
          "Ở đây có {dish} không bạn? Cho mình một cái",
        ],
        pricey: ["Hơi mắc nha bạn", "Giá này hơi chát á", "Chà, giá du lịch ha"],
        thanks: ["Cảm ơn bạn nha!", "Ok, ngon đó", "Lẹ ghê, cảm ơn nhé"],
        impatient: ["Thôi mình đi, gấp quá", "Lâu quá bạn ơi", "Đợi hoài, thôi đi tiếp"],
      },
      {
        archetype: "reviewer",
        ask: [
          "Cho mình {dish}, mình quay clip review xíu được hông? 📸",
          "Hello shop, {dish} nha, nghe bảo hot lắm",
        ],
        cheap: [
          "Giá này mà chất lượng vậy là deal hời đó mọi người 🔥",
          "Rẻ mà ngon, quẹo lựa nha",
        ],
        pricey: ["Hơi đắt so với chất lượng nha, 6/10", "Mức giá này thì cần cải thiện thêm"],
        thanks: [
          "Ngon nha, chấm 8.5/10, sẽ quay lại",
          "Okela, lên clip liền",
          "Chất lượng ổn, phục vụ nhanh, ủng hộ!",
        ],
        impatient: [
          "Chờ lâu quá, cái này phải ghi vào review rồi",
          "Hơi lâu nha shop, trừ điểm phục vụ",
        ],
      },
    ],
    soften: {
      vãi: "quá",
      "xỉu ngang": "lắm luôn",
      "đỉnh của chóp": "tuyệt",
      "u là trời": "trời ơi",
      "chịu không nổi": "hết chờ nổi",
    },
  },

  customerLines: {
    cheap: ["Rẻ vậy! Mai ghé nữa nha", "Giá này hời quá", "Cho thêm ổ nữa được hông?"],
    fair: ["Cho một phần nha", "Bán cho con với", "Như mọi khi nha"],
    pricey: ["Hơi mắc ha…", "Giá này hơi chát", "Bữa sau bớt chút nha"],
    thanks: ["Cảm ơn nha!", "Lẹ ghê, gửi tiền nè", "Ngon! Giữ tiền thối luôn"],
    impatient: ["Lâu quá, thôi đi…", "Đợi hoài…", "Thôi để bữa khác"],
  },

  economy: {
    startingMoney: 1_500_000,
    dayStartMinute: 6 * 60,
    dayEndMinute: 22 * 60,
    economyTickMinutes: 5,
    marketPriceSwing: 0.1,
    outsideOption: 1,
    reputationRate: 0.08,
    startingReputation: 0.5,
    afternoonMarkup: 0.2,
    shoutBoost: 1.25,
    shoutMinutes: 60,
    shoutCooldownMinutes: 30,
    bulkPacks: 5,
    bulkDiscount: 0.05,
    resaleRate: 0.4,
    friendDiscountAt: 30,
    friendDiscount: 0.05,
    tipRate: 0.08,
    // Phí chợ/thuế khoán: xe đẩy 5k/ngày, tiệm 15k/ngày; tiệm còn trả điện nước 3k mỗi giờ mở cửa.
    fees: { daily: { cart: 5_000, house: 15_000 }, utilitiesPerHour: 3_000 },
    // Mòn ~0,6% mỗi món: bán ~80 món là xe ọp ẹp (khách bớt 15%, giữ nút lâu hơn 60%); 100% thì phải sửa mới mở được.
    // Sửa hết mòn tốn 12% giá xe (xe bánh mì 1,2tr → ~144k, như thay bánh xe + kính + sơn ở tiệm sửa xe).
    maintenance: {
      wearPerServe: 0.006,
      slowAt: 0.5,
      slowDemand: 0.85,
      slowHold: 1.6,
      repairRate: 0.12,
    },
    // Lãi 0,2%/ngày cho số dư từ 100k, tối đa 3.000đ/ngày — có cũng vui, không sống bằng lãi được (Luật 2.3).
    bank: {
      interestRate: 0.002,
      interestCap: 3_000,
      interestMin: 100_000,
      withdrawStep: 10_000,
      depositStep: 10_000,
      // Mua lặt vặt (dưới 200k) thì móc tiền mặt; mua xe, trả tiền nhà thì quét mã chuyển khoản.
      cashFirstBelow: 200_000,
      // Rút ATM mất phí như ngoài đời; sai PIN 3 lần máy nuốt thẻ (UC-I6).
      withdrawFee: 1_000,
      pinTries: 3,
    },
    serveReputationBonus: 0.01,
    interactRadius: 2.5,
  },

  // Kỹ năng (DESIGN §4): làm thật mới lên — bán kịp, làm đúng lời dặn, chào hỏi/khách vui.
  skills: [
    {
      id: "tay_nhanh",
      name: "Tay nhanh",
      emoji: "⚡",
      description: "Phục vụ kịp giờ thì lên. Mỗi bậc: giữ nút (lắc, giữ…) nhanh hơn 8%.",
      per: 15,
      max: 5,
      effect: 0.08,
    },
    {
      id: "nho_mon",
      name: "Nhớ món",
      emoji: "🧠",
      description:
        "Làm đúng món có lời dặn thì lên. Từ bậc 1: màn làm món nhắc lại lời dặn của khách.",
      per: 10,
      max: 5,
      effect: 1,
    },
    {
      id: "an_noi",
      name: "Ăn nói",
      emoji: "💬",
      description: "Chào hỏi, khách vui vẻ ra về thì lên. Mỗi bậc: khách kiên nhẫn thêm 5%.",
      per: 12,
      max: 5,
      effect: 0.05,
    },
  ],
  // Mở khoá theo cấp (Luật 4.2): làm thật mới mở — không mua bằng tiền thật.
  unlocks: [
    { id: "event_host", level: 2, label: "Tổ chức khai trương" },
    { id: "lot_house", level: 3, label: "Thuê nhà mặt tiền mở tiệm" },
  ],

  // Xóm quê (góp ý chủ dự án 10/2026): ít nhà cao tầng; nhà dân phần lớn là nhà cấp 4 mái ngói, vài nhà tranh,
  // lác đác nhà ống — sau này người chơi mua/xây nhà thì nâng cấp dần lên (DESIGN §5).
  housing: {
    tiers: [
      { id: "nha_tranh", name: "Nhà tranh vách tre", models: ["nha-tranh"], start: 0.25 },
      { id: "cap4", name: "Nhà cấp 4 mái ngói", models: ["nha-cap4", "nha-cap4-xanh"], start: 0.6 },
      { id: "ong1", name: "Nhà ống 1 lầu", models: ["nha-ong-1-lau"], start: 0.15 },
      { id: "ong2", name: "Nhà ống 2 lầu", models: ["nha-ong-2-lau"], start: 0 },
    ],
    shops: ["tiem-tap-hoa", "tiem-tap-hoa-trang", "nha-cap4", "nha-ong-1-lau"],
    office: "uy-ban",
    school: "truong-lang",
  },

  // Sự kiện (docs/USECASES.md UC-B5, nhóm K; DESIGN §9): người chơi tạo (khai trương), cá nhân (khách VIP), toàn xóm (mưa lớn).
  events: [
    {
      id: "khai_truong",
      name: "Khai trương",
      emoji: "🎉",
      scope: "player",
      minutes: 180,
      trigger: {
        kind: "player",
        cooldownDays: 3,
        costs: [
          { id: "phao_giay", label: "Pháo giấy", emoji: "🎊", price: 40_000 },
          { id: "bong_bong", label: "Chùm bong bóng", emoji: "🎈", price: 25_000 },
          { id: "bang_ron", label: "Băng rôn", emoji: "🪧", price: 35_000 },
        ],
      },
      effects: { demand: 1.8, discount: 0.1 },
      news: "🎉 {name} khai trương {shop} — giảm 10%, ghé ủng hộ nha!",
    },
    {
      id: "khach_vip",
      name: "Khách VIP",
      emoji: "🕴️",
      scope: "personal",
      minutes: 1,
      trigger: { kind: "per_hour", perHour: 0.35 },
      effects: {
        vip: { minMods: 2, patience: 0.8, tipMult: 5, repWin: 0.04, repLose: 0.05 },
      },
      news: "🕴️ Có khách sộp ghé {shop} — dặn kỹ lắm, làm chuẩn là được boa đậm",
    },
    {
      id: "mua_lon",
      name: "Mưa lớn toàn xóm",
      emoji: "⛈️",
      scope: "server",
      minutes: 90,
      trigger: { kind: "daily", chance: 0.15, from: 13 * 60, to: 19 * 60 },
      effects: { weather: "storm" },
      news: "⛈️ Đài báo chiều nay mưa lớn toàn xóm — lo dọn hàng vô trong",
    },
  ],

  // Thời tiết (docs/USECASES.md UC-B4, DESIGN §8): trời đổi theo khối 2 giờ, chiều hay mưa (kiểu Sài Gòn mùa mưa).
  // Mưa/bão: khách ngoài vỉa hè thưa hẳn, tiệm có mái đông hơn; nắng gắt: đồ uống lạnh bán chạy.
  weather: {
    blockMinutes: 120,
    persist: 0.5,
    forecastMinutes: 90,
    weights: {
      sunny: { "6": 4, "10": 6, "13": 5, "16": 3, "19": 2, "21": 2 },
      cloudy: { "6": 3, "12": 2, "16": 3, "21": 3 },
      rain: { "6": 1, "11": 1, "14": 3, "17": 3, "20": 1 },
      storm: { "6": 0, "12": 0.2, "16": 0.6, "19": 0.2, "21": 0 },
    },
    kinds: [
      {
        id: "sunny",
        name: "Nắng",
        emoji: "☀️",
        outdoor: 1,
        indoor: 1,
        category: { drink: 1.2 },
        delivery: { speed: 1, surcharge: 0, damage: 1 },
        dim: 0,
        rain: 0,
        news: "☀️ Trời nắng gắt — nước mát, trà sữa bán chạy",
        forecast: "☀️ Khoảng {time} trời hửng nắng lại",
      },
      {
        id: "cloudy",
        name: "Âm u",
        emoji: "🌫️",
        outdoor: 0.9,
        indoor: 1,
        category: {},
        delivery: { speed: 1, surcharge: 0, damage: 1 },
        dim: 0.18,
        rain: 0,
        news: "🌫️ Trời âm u, người ta ít ra đường hơn",
        forecast: "🌫️ Khoảng {time} trời kéo mây âm u",
      },
      {
        id: "rain",
        name: "Mưa",
        emoji: "🌧️",
        outdoor: 0.5,
        indoor: 1.15,
        category: { drink: 0.8, breakfast: 1.15 },
        delivery: { speed: 0.8, surcharge: 0.2, damage: 1.6 },
        dim: 0.35,
        rain: 0.55,
        news: "🌧️ Trời đổ mưa — xe đẩy vắng khách, tiệm có mái đông lên",
        forecast: "🌧️ Khoảng {time} có mưa — chuẩn bị dời vô chỗ có mái",
      },
      {
        id: "storm",
        name: "Bão",
        emoji: "⛈️",
        outdoor: 0.2,
        indoor: 1,
        category: { drink: 0.6, breakfast: 1.2 },
        delivery: { speed: 0.6, surcharge: 0.5, damage: 2.5 },
        dim: 0.55,
        rain: 1,
        news: "⛈️ Mưa bão! Ngoài đường gần như không ai, giao hàng có phụ phí bão",
        forecast: "⛈️ Khoảng {time} có giông bão — dọn hàng vô trong cho kịp",
      },
    ],
  },
};
